### ISSUE TITLE
Improve docs/website

### ISSUE THREAD

**Issue by nunomaduro** [nunomaduro/phpinsights#105]
Would be cool if someone could work on the website. What do we need? Ideas?

Here is the source code: https://github.com/nunomaduro/phpinsights/tree/master/docs.

Setup locally:

```bash
git clone https://github.com/nunomaduro/phpinsights
cd phpinsights
yarn
yarn run vuepress dev
```

**Comment by ricardovfreixo** [comment]
minor typo there

> git clone https://github.com/nunomaduro/phpinsights
> cd phpinsights/docs
> yarn
> yarn run vuepress dev

I'll see what I can contribute mate

**Comment by olivernybroe** [comment]
We get multiple issues about users not understanding what settings they can set.
Could be nice if we could have a section in the docs showing the arguments for each of the Sniffs we use. This way the user can easily figure out how to change configuration to their needs.

**Comment by syntaxseed** [comment]
I'm really interested in this project, but when I look at the screenshot of the report output... I then went to the docs to find out what all the percents & points mean, but couldn't find anything.

**Comment by olivernybroe** [comment]
@syntaxseed Yeah that might make sense to have a section explaining the values.
Basically the way it works is that it collects all sniffs which has ran and calculates the percentage of them which did not throw an error. 
It is not based on LOC.

**Comment by nunomaduro** [comment]
@syntaxseed Let's make sure to improve this together.
