### ISSUE TITLE
[Laravel Preset] Should Insights ignore useless override?

### ISSUE THREAD

**Issue by deleugpn** [nunomaduro/phpinsights#109]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| Library version  | latest

```
• [Code] Useless overriding method:
  app/Exceptions/Handler.php:42: Possible useless method overriding detected
  app/Exceptions/Handler.php:54: Possible useless method overriding detected
  app/Providers/EventServiceProvider.php:26: Possible useless method overriding detected
```

Laravel skeleton comes with some 'useless' overrides to show where developers may choose to do things related to Exception Handler or Event configuration. I'd prefer to keep these parts of the skeleton untouched instead of removing them to satisfy the tool, thus keeping standard Laravel skeleton.

**Comment by nunomaduro** [comment]
I have mixed feelings on this. Let's keep this open.

**Comment by AndreasHerss** [comment]
Personally, i like to keep the methods, even if not used, but yeah, the warning is a bit annoying.

perhaps some optional way to disable it, only for the default laravel files?

**Comment by nunomaduro** [comment]
It's in our plans to add something to ignore this on the future.

**Comment by nunomaduro** [comment]
No plans to work on this at this time.
