### ISSUE TITLE
[Laravel Preset] Should Insights ignore Telescope Provider?

### ISSUE THREAD

**Issue by bop10** [nunomaduro/phpinsights#110]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| Library version  | 1.3.0

First, i want to thank you for this great package.

I'm using Telescope in a Laravel application, and this appears:
`• [Complexity] Having `classes` with more than 5 cyclomatic complexity is prohibited - Consider refactoring:
  app/Providers/TelescopeServiceProvider.php: 6 cyclomatic complexity`

Since Telescope is an official Laravel package, should Insights ignore this provider?

Thanks
<!--
Love PHP Insights? Please consider supporting us via Patreon or OpenCollective:
👉  https://www.patreon.com/nunomaduro
👉  https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=66BYDWAT92N6L
--

**Comment by nunomaduro** [comment]
Sounds ok, can you pr that into: https://github.com/nunomaduro/phpinsights/blob/master/src/Application/Adapters/Laravel/Preset.php?
