### ISSUE TITLE
[Preset] Feature request Drupal 8 

### ISSUE THREAD

**Issue by killua99** [nunomaduro/phpinsights#118]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes

<!--
Love PHP Insights? Please consider supporting us via Patreon or OpenCollective:
👉  https://www.patreon.com/nunomaduro
👉  https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=66BYDWAT92N6L
--

New Preset for Drupal 8

**Comment by nunomaduro** [comment]
This issue has been fixed on the version `v1.5.0`.

Thanks for your work on this.
