### ISSUE TITLE
Complexity result superior to 100 

### ISSUE THREAD

**Issue by TomKlotzPro** [nunomaduro/phpinsights#119]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| Library version  | 1.3.1

## Description 

In case the project is empty, I get a result of 133.3%. 

This will change the style because there is 4 digit. 

## What to change : 

Put a limit of complexity result to 100. 

<img width="675" alt="Screenshot 2019-05-21 at 10 37 47" src="https://user-images.githubusercontent.com/23667211/58083205-d89ede80-7bb8-11e9-9be4-1ca2f49ada1f.png">

**Comment by LeonAlvarez** [comment]
Already reported #58

**Comment by TomKlotzPro** [comment]
Thank you @LeonAlvarez
