### ISSUE TITLE
[Insight for Laravel] Verify if there no dd() calls

### ISSUE THREAD

**Issue by nunomaduro** [nunomaduro/phpinsights#12]
To solve this issue, you should create a pull request adding the `Insight` described on the title.

**Comment by pxgamer** [comment]
Is there a way to view function call names at the moment? 🤔

**Comment by szepeviktor** [comment]
it is Squiz.PHP.DiscouragedFunctions.forbiddenFunctions in PHPCS

Could we add dump() and extract, compact and list?

**Comment by nunomaduro** [comment]
Exactly, good idea @szepeviktor.

@pxgamer You just need to add this code:
```php
                ForbiddenFunctionsSniff::class => [
                    'sizeof' => 'count',
                    'delete' => 'unset',
                    // Any other...
                ]
```

To https://github.com/nunomaduro/phpinsights/blob/c8e1069171bac1c057f08bda73273a5200c4ba6d/src/Application/DefaultPreset.php#L46.

Don't forget to test it locally to see if it works.

**Comment by pxgamer** [comment]
I'll take a look at it later, cheers. :+1:
