### ISSUE TITLE
Add ability to filter specific directories for analysis

### ISSUE THREAD

**Issue by JacobDB** [nunomaduro/phpinsights#121]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| Library version  | 1.0.0

I develop custom WordPress themes for many clients, and I'd love to use phpinsights as part of that process. These websites use Composer for PHP, Webpack for JavaScript, and Sass for CSS. To facilitate this, I use NPM/Node/Gulp to help automate my workflow.

I'm not sure if this is considered "best practice" for PHP projects, but my repositories have three code containing folders &ndash; `src`, `dev`, and `dist`. I work out of `src`, compile to `dev` for testing, and `dist` for deployment. My `composer.json` and `vendor` folders exist at the root of my project, with Gulp copying over the vendor files to the appropriate destination at compile.

Currently, if I run `phpinsights`, both `src` and `dist` seem to be analyzed, whereas I'd prefer to only analyze `src` (`dev` is in `.gitignore`, which I suspect is why it's not also analyzed). This effectively parses all my code twice, which creates a lot of extra noise in the output, and causes a bit of confusion. If I run `phpinsights analyse src`, I get an error that `composer.json` doesn't exist, because it's not within `src`.

Would it be possible to add the ability to only parse specific file/directories, or otherwise to ignore specific files/directories? Is this already possible, and I'm just missing how to configure this?

My root-level file structure is below to help illustrate what I'm talking about. If the real problem is how I'm structuring my projects, I'd really appreciate some guidance in understand a better way to organize this.

```
.
├── CHANGELOG.md
├── composer.json
├── composer.lock
├── CONTRIBUTING.md
├── dev
├── dist
├── gulpfile.js
├── gulp-tasks
├── LICENSE.md
├── node_modules
├── package.json
├── package-lock.json
├── README.md
├── src
├── vendor
└── webpack.config.js
```

<!--
Love PHP Insights? Please consider supporting us via Patreon or OpenCollective:
👉  https://www.patreon.com/nunomaduro
👉  https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=66BYDWAT92N6L
--

**Comment by JacobDB** [comment]
Ah, I completely missed the `config.php` thing. I see there's a way to exclude stuff. I'll try that and re-open if I still have trouble.

**Comment by nunomaduro** [comment]
@JacobDB Can you take a look on this https://github.com/nunomaduro/phpinsights/pull/87? It's a preset for wordpress to automatically discovery wordpress and ignore folders, etc.

**Comment by JacobDB** [comment]
I did see that pull request, and will review it and provide feedback when I have some time (hopefully by the end of the week) 🙂
