### ISSUE TITLE
[Question] How to configure public param $lineLimit in LineLengthSniff

### ISSUE THREAD

**Issue by davi5e** [nunomaduro/phpinsights#124]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | maybe?
| Library version  | 1.3

So, my entire code is intended have <120 characters per line and the default configuration ```LineLengthSniff``` uses is 80.

I know I could add it to ```remove``` and be done with it, but I'd much rather change the public parameter ```$lineLimit``` to enforce this sniff.

Is it possible?

Also, the same thing applies to pretty much any length-related sniff (e.g. ```FunctionLengthSniff```). 

Regards, DAVI

**Comment by olivernybroe** [comment]
Yep, you can customize it.

**Comment by olivernybroe** [comment]
Yep, it can be customised. 
For `LineLengthSniff` there are 3 properties to look for.

    /**
     * The limit that the length of a line should not exceed.
     *
     * @var integer
     */
    public $lineLimit = 80;

    /**
     * The limit that the length of a line must not exceed.
     *
     * Set to zero (0) to disable.
     *
     * @var integer
     */
    public $absoluteLineLimit = 100;

    /**
     * Whether or not to ignore comment lines.
     *
     * @var boolean
     */
    public $ignoreComments = false;


You can set them in your config file under `config` like so
```
LineLengthSniff::class => [
    'absoluteLineLimit' => 120, 
    'lineLimit' => 120,
    'ignoreComments' => false,
]
```

**Comment by davi5e** [comment]
Thank you @olivernybroe !

**Comment by paulomanrique** [comment]
@olivernybroe I tried that and didn't work for me :(

**Comment by davi5e** [comment]
```php
<?php

declare(strict_types=1);

use PHP_CodeSniffer\Standards\Generic\Sniffs\Files\LineLengthSniff;

return [
    // Other stuff

    'config' => [
        LineLengthSniff::class => [
            'absoluteLineLimit' => 120,
            'lineLimit' => 120,
            'ignoreComments' => false,
        ],
];
```
