### ISSUE TITLE
directory argument conflicts with required files

### ISSUE THREAD

**Issue by akosglue** [nunomaduro/phpinsights#129]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| Library version  | v1.3.1

I try to specify the directory argument, for example:
`php artisan insights app/Models/`

Then I get the error:
`   RuntimeException  : The file `composer.lock` must exist. You should run PHP Insights from the root of your project.
`

And the same for composer.json.

If I copy these 2 files into the specified directory, the analyzer can run. But I guess this is not the expectation that I need to copy paste those files.

**Comment by hudsonpereira** [comment]
Have you tried from the root of your project?

```
./vendor/bin/phpinsights app/Models/
```

**Comment by akosglue** [comment]
Yes.
running this: `./vendor/bin/phpinsights app/Models/`
gives me this error:
`Command "app/Models/" is not defined.`

This works as expected: `./vendor/bin/phpinsights -v`

Same error as in my first comment: `./vendor/bin/phpinsights analyze app/Models/`

**Comment by olivernybroe** [comment]
Yep this makes sense. What the error message means is that you have to run the insights from the root of your projects. You are not able to specify a directory or a file to only analyze.
The argument for a folder is so you can target your project root, not so you can analyze a subset of file only.

This is related to the issue #148.
