### ISSUE TITLE
[Insight for Laravel] Verify that there is no usages of requests outside FormRequests or Controllers

### ISSUE THREAD

**Issue by nunomaduro** [nunomaduro/phpinsights#13]
To solve this issue, you should create a pull request adding the `Insight` described on the title.

**Comment by ijpatricio** [comment]
Maybe leaving the classes where the the request can be used as configurable.

Think for example, DataTransferObjects. In https://github.com/spatie/data-transfer-object , a `fromRequest` constructor is adopted.

There might be more cases, so leaving calss / parent class as configurable might be a good solution.

**Comment by nunomaduro** [comment]
No plans to work on this at this time.
