### ISSUE TITLE
[Laravel] The `No setter` should not count Models' mutators

### ISSUE THREAD

**Issue by rodrigopedra** [nunomaduro/phpinsights#135]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| Library version  | 1.3.1

Laravel has a convenient way to define mutators on its Models by the defining a method named like this: `setFieldAttribute`. It will use this method dynamically to allow some logic when setting attributes.

(@nunomaduro I know you might know this by heart, I am just describing it for completeness).

PHP Insights should not count these mutators in the No Setters Sniffer, at least not in a Laravel project.

<!--
Love PHP Insights? Please consider supporting us via Patreon or OpenCollective:
👉  https://www.patreon.com/nunomaduro
👉  https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=66BYDWAT92N6L
--

**Comment by ManojKiranA** [comment]
i am having the same issue
