### ISSUE TITLE
PHP Insights version shown incorrectly

### ISSUE THREAD

**Issue by axelitus** [nunomaduro/phpinsights#136]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| Library version  | 1.3.1

Running `vendor/bin/phpinsights -V`or `vendor/bin/phpinsights --version` outputs the wrong version number: `PHP Insights v1.0.0`

<!--
Love PHP Insights? Please consider supporting us via Patreon or OpenCollective:
👉  https://www.patreon.com/nunomaduro
👉  https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=66BYDWAT92N6L
--

**Comment by nunomaduro** [comment]
Nice catch, can you make a pull request on this? Maybe add a new `RELEASE.md` explaining the steps on release a new version. Because we need to update this file: https://github.com/nunomaduro/phpinsights/blob/1173b539b84106467fc185fa74006e2ad9889108/bin/phpinsights#L28.

**Comment by axelitus** [comment]
@nunomaduro Is this the only place where the version number string is used/set/referenced? (I mean as a hard-coded string).

**Comment by axelitus** [comment]
Done! I've proposed the steps to verify before publishing a new release.

I did not include the fix for the version number as that would be better made upon a new release.

**Comment by nunomaduro** [comment]
This issue was been fixed. Thanks!
