### ISSUE TITLE
Output Insight class name for issues

### ISSUE THREAD

**Issue by axelitus** [nunomaduro/phpinsights#137]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| Library version  | 1.3.1

It would be nice if the Insight class would be output along with the issues as to know exactly which insight is evaluating to an error (and make it easier to add it to the exceptions in the config file).

Example:

Improve this:

```bash
• [Code] No setter:
  src/ValueObject.php:63: Setters are not allowed. Use constructor injection and behavior naming instead, e.g. changeName() instead of setName().
```
Like this:

```bash
• [Code] No setter:
  Insight: ObjectCalisthenics\Sniffs\NamingConventions\NoSetterSniff
  src/ValueObject.php:63: Setters are not allowed. Use constructor injection and behavior naming instead, e.g. changeName() instead of setName().
```

<!--
Love PHP Insights? Please consider supporting us via Patreon or OpenCollective:
👉  https://www.patreon.com/nunomaduro
👉  https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=66BYDWAT92N6L
--

**Comment by nunomaduro** [comment]
Good idea, maybe only with the `-v` option. Can you add a pull request on that? I would prefer something like: `src/ValueObject.php:63: (ObjectCalisthenics\Sniffs\NamingConventions\NoSetterSniff) Setters are not allowed.`

**Comment by Jibbarth** [comment]
@nunomaduro Do you think it's necessary to display Sniff ClassName on each line ? 
I was trying to implement it, and it seems that is the same sniff for each group ?

For example: 

```
• [Style] Else if declaration:
  src/Domain/Analyser.php:99: (PHP_CodeSniffer\Standards\PSR2\Sniffs\ControlStructures\ElseIfDeclarationSniff) Usage of ELSE IF is discouraged; use ELSEIF instead
  src/Domain/Analyser.php:104: (PHP_CodeSniffer\Standards\PSR2\Sniffs\ControlStructures\ElseIfDeclarationSniff) Usage of ELSE IF is discouraged; use ELSEIF instead
  src/Domain/Analyser.php:111: (PHP_CodeSniffer\Standards\PSR2\Sniffs\ControlStructures\ElseIfDeclarationSniff) Usage of ELSE IF is discouraged; use ELSEIF instead
``` 
See also the full report [phpinsights-full-report.txt](https://github.com/nunomaduro/phpinsights/files/3224523/phpinsights-full-report.txt)

I think adding the SniffClassName once by group is sufficient :thinking:

**Comment by nunomaduro** [comment]
Good idea, yeah, maybe:

• [Style] Else if declaration (PHP_CodeSniffer\Standards\PSR2\Sniffs\ControlStructures\ElseIfDeclarationSniff):

**Comment by axelitus** [comment]
@Jibbarth you beat me to it! ;) your PR looks great! This will be a great addition

**Comment by nunomaduro** [comment]
This is now available on the version `v1.4.0`.

**Comment by nunomaduro** [comment]
Thanks, again @Jibbarth !

**Comment by Jibbarth** [comment]
My pleasure 😊
