### ISSUE TITLE
composer require fail

### ISSUE THREAD

**Issue by cpj555** [nunomaduro/phpinsights#138]
![image](https://user-images.githubusercontent.com/19289096/58455892-5fbdfa80-8155-11e9-8fa6-b297c04ab7fd.png)

**Comment by cpj555** [comment]
php7.3 will throw the  "switch continue"  exception

**Comment by pxgamer** [comment]
I can't seem to replicate this (with PHP 7.3.5). 🤔

If you require another package, do you get the same error?

**Comment by nunomaduro** [comment]
@cpj555 Please use `composer require nunomaduro/phpinsights --dev -vvv`. And output the response.

**Comment by nunomaduro** [comment]
@cpj555 Please re-open the issue if the problem still exists.
