### ISSUE TITLE
How can I track down what a message means, and how to fix it?

### ISSUE THREAD

**Issue by JacobDB** [nunomaduro/phpinsights#141]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| Library version  | 1.4.0

I'm having a hard time understanding some of the warnings, and I can't seem to find any full documentation as to what each specific error indicates. For example, I'm getting the following error:

```sh
• [Code] Type hint declaration: (SlevomatCodingStandard\Sniffs\TypeHints\TypeHintDeclarationSniff)
  src/functions/advanced-custom-fields.php:13: Function __gulp_init_namespace___acf_delay_shortcode_expansion() does not have return type hint for its return value but it should be possible to add it based on @return annotation "void".
```

For the code:

```php
/**
 * Delay when shortcodes get expanded
 *
 * @return void
 */
function __gulp_init_namespace___acf_delay_shortcode_expansion() {
    remove_filter("acf_the_content", "do_shortcode", 11);
	add_filter("acf_the_content", "do_shortcode", 25);
}
add_action("acf/update_value/type=wysiwyg", "__gulp_init_namespace___acf_delay_shortcode_expansion");
```

I don't understand what it's asking me to fix; isn't `void` the "return type hint"?

Where can I find a more detailed reference on what each issue is, and how to fix it?

**Comment by JacobDB** [comment]
Ah, I just saw the reference to `SlevomatCodingStandard`, I'm looking there and will report back if this is helpful...

**Comment by pxgamer** [comment]
You can apply the type hint to the function, as well as a PHPDoc. That way PHP will actually verify it.

e.g.
```php
function __gulp_init_namespace___acf_delay_shortcode_expansion(): void
```

**Comment by nunomaduro** [comment]
It's a open issue for this: https://github.com/nunomaduro/phpinsights/issues/8

**Comment by JacobDB** [comment]
@pxgamer thanks, that does fix this particular error, but doesn't answer the question of how I can identify what each error is actually saying. I've still got dozens of things I'm trying to track down without much luck.

@nunomaduro thanks for pointing that out, I've subscribed to that issue and added my two cents.

I'll close in favor of #8.
