### ISSUE TITLE
Excluding stuff results in more files scanned (but not reported)

### ISSUE THREAD

**Issue by olivernybroe** [nunomaduro/phpinsights#143]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| Library version  | v1.5.0

So I added in the following to my exclude array
```
    'exclude' => [
        'bower_components',
        'node_modules',
        'vendor',
        '.phpstorm.meta.php',
    ],
```
And it goes from 560 files to 1163 files when scanning.

This also results in it actually crashing with a memory exhaust when more folders are added to the exclude array. So it is using a lot more memory the more files are added in exclude array.

**Comment by nunomaduro** [comment]
Can you add that to the default preset?

**Comment by olivernybroe** [comment]
@nunomaduro Oh sure, that kinda makes sense that it is in there. 
However I don't think adding it in is smart to do before we find what is causing it to use more memory when stuff is added to the `exclude` array. As merging it in will prob. result in a lot of users getting memory exhaust.

**Comment by olivernybroe** [comment]
This is the same issue as #145.
