### ISSUE TITLE
Added `excludes` to config start to overwrite existing from preset

### ISSUE THREAD

**Issue by ijpatricio** [nunomaduro/phpinsights#145]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| Library version  | 1.3.5

Running on Laravel 5.8.19.

When I was adding paths on `config/insights.php -> exclude key`
It turns out is not merging, but replacing, taking to erroneous behaviour.

It seems to me, the best way to explain is showing a `dd($config)` on `vendor/nunomaduro/phpinsights/src/Application/ConfigResolver.php`

Let's focus only on `exclude` key. Tried on a new fresh laravel app, just install phpinsights.
- Published config. (didnt add anything)
- Added `dd($config);` before the return on `resolve` method.
- Ran `php artisan insights`

Result:
![image](https://user-images.githubusercontent.com/26031459/58568402-20161200-822c-11e9-9a43-49975ba6ef4c.png)

All good until here, those are the default excludes from Laravel Preset.

But now, I go to `config/insights.php -> exclude key` and add a path `modules/Phpgrid` for a folder I want out...

Ran again, and the `dd` results like this:
![image](https://user-images.githubusercontent.com/26031459/58567831-045e3c00-822b-11e9-9cdb-d769e45e0a04.png)

#### Conclusion

The count is the same, 11 excludes, but `config` disappeared and `modules/PhpGrid` came in its place.

So, added excludes start to overwrite existing, instead of adding (extending)

**Comment by nunomaduro** [comment]
Can you work a pull request to fix this buddy? @ijpatricio

**Comment by ijpatricio** [comment]
Had to edit the original post, because i put ht e fisrt screenshot worng, still form other experiments lol

Now it's correct picture, and sure, I will try just right ahead to fix this.

**Comment by nunomaduro** [comment]
@ijpatricio Can you re-test this?
