### ISSUE TITLE
Test individual file

### ISSUE THREAD

**Issue by erwinw** [nunomaduro/phpinsights#148]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes

It would be great to get insights for individual PHP files; that way we can make improvements one file at a time.

**Comment by olivernybroe** [comment]
We should at the same time add support for specifying a directory to analyze, so I can analyze a directory of files alone.

**Comment by Jibbarth** [comment]
@erwinw Thanks for proposing this idea. 

It'll be available in the next release :wink:

**Comment by erwinw** [comment]
Just to leave the thought here: this also starts opening the way to say a VSCode extension! #exciting

**Comment by nunomaduro** [comment]
Never used a VSCode extension, can you give me some examples? @erwinw

**Comment by olivernybroe** [comment]
Because of this you should also be able to set it up as an external tool in PHPStorm ;)

**Comment by erwinw** [comment]
Vscode extensions add whatever functionality you want to the editor; for JavaScript I’m using an Eslint extension which inline with the code indicates syntax and style problems, as well as providing a summary of problems. Phpinsights would be perfect for that - it would be so good to immediately get feedback while coding! (And just for the record, I think Phpinsights is a great idea; it can be overwhelming to attempt to clean up a large code base but doing this file by file can make all the difference.)
