### ISSUE TITLE
Bringing people on board

### ISSUE THREAD

**Issue by nunomaduro** [nunomaduro/phpinsights#152]
Hey buddies, opening this issue as I would like to add 1 or 2 developers as maintainers of PHP Insights. **Who would like to help**? The goal is adding two developers that are able to perform triage on issues, validate/merge pull requests, and eventually add new releases.

**Comment by nunomaduro** [comment]
Looking at `https://github.com/nunomaduro/phpinsights/graphs/contributors` looks like @Jibbarth @olivernybroe @szepeviktor @xuanquynh maybe would like to help?

**Comment by olivernybroe** [comment]
@nunomaduro I would be up for helping out :)

**Comment by nunomaduro** [comment]
@olivernybroe Just added you as collaborator, Thanks! https://github.com/nunomaduro/phpinsights/invitations

**Comment by doganoo** [comment]
@nunomaduro do you have any requirements on availability and total amount of work per week/month?

**Comment by nunomaduro** [comment]
No requirements. Open source it's a hobby.

**Comment by xuanquynh** [comment]
@nunomaduro I think szepeviktor or Jibbarth is a good collaborator. They will do things well. I quit my job a month ago and I am looking for a new job now. I can not spend time supporting open source projects until I find a new job. When I am stable with the new life that may takes me one or two months, I will be still a volunteer supporter.

I hope I will come back to open source soon.

Thank you!

**Comment by Jibbarth** [comment]
Hey :raising_hand_man: 

Thanks for proposing. There are some parts in the project that are beyond my skills, but I'll be happy to help

**Comment by nunomaduro** [comment]
Added! Thanks! https://github.com/nunomaduro/phpinsights/invitations

**Comment by nunomaduro** [comment]
Sounds good for now, thanks everyone for the help.

**Comment by olivernybroe** [comment]
Welcome on board @Jibbarth!
