### ISSUE TITLE
ErrorException : Undefined offset: 48 in YodaHelper.php:168

### ISSUE THREAD

**Issue by RobertCordes** [nunomaduro/phpinsights#153]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| Library version  | 1.5.0

I was using PHP Insights with Laravel 5.7.x and everything was working fine. Then I updated Laravel to 5.8.x and now I get the following error when running `php artisan insights`:

```
 ErrorException  : Undefined offset: 48

  at /project-path/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/YodaHelper.php:168
    164|                $sideTokens = [];
    165|                $stopTokenCodes = self::getStopTokenCodes();
    166|                while (true) {
    167|                        $examinedTokenPointer++;
  > 168|                        $examinedToken = $tokens[$examinedTokenPointer];
    169|                        /** @var string|int $examinedTokenCode */
    170|                        $examinedTokenCode = $examinedToken['code'];
    171|                        if ($parenthesisDepth === 0 && $shortArrayDepth === 0 && isset($stopTokenCodes[$examinedTokenCode])) {
    172|                                break;
```

**Comment by olivernybroe** [comment]
Having some trouble reproducing this. Would you be able to make a simple example with this error?

**Comment by nunomaduro** [comment]
@olivernybroe @RobertCordes  I don't think this is our problem. You should report this to: slevomat/coding-standard

**Comment by RobertCordes** [comment]
Sorry @olivernybroe and @nunomaduro, I missed the GitHub notifications. Thanks for your quick answers. I will try to reproduce this with a simple example and report to slevomat/coding-standard if necessary.
