### ISSUE TITLE
Add "what others think about PHP Insights" page on the website

### ISSUE THREAD

**Issue by nunomaduro** [nunomaduro/phpinsights#161]
This resolve this issue you should work on the PHP Insights website.

The goal is simple: Add a section bellow the `get started` section with the best tweets about PHP Insights: [twitter.com/search?f=tweets&vertical=default&q=%22php%20insights%22&src=typd](https://twitter.com/search?f=tweets&vertical=default&q=%22php%20insights%22&src=typd).

How to setup the website locally? 

```bash
git clone https://github.com/nunomaduro/phpinsights
cd phpinsights/docs
yarn
yarn run vuepress dev
```

The framework used on the website: https://vuepress.vuejs.org.

**Comment by nunomaduro** [comment]
Where is an example on the https://phppackagedevelopment.com website:

<img width="1391" alt="Screenshot 2019-06-04 at 21 33 37" src="https://user-images.githubusercontent.com/5457236/58908304-7c879e80-8710-11e9-90ae-59a8b5f5ae0d.png">

**Comment by krisnaw** [comment]
Can I take it?

**Comment by nunomaduro** [comment]
@krisnaw Sure! Thanks!

**Comment by Jibbarth** [comment]
Thanks @krisnaw
