### ISSUE TITLE
It be cool to use custom existing `easy-coding-standard.yml`

### ISSUE THREAD

**Issue by Zolotov88** [nunomaduro/phpinsights#163]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| Library version  | 1.5.0

It be cool to use custom existing `easy-coding-standard.yml`

**Comment by nunomaduro** [comment]
Sorry, can you describe better your issue?

**Comment by Zolotov88** [comment]
I'm using EasyCodingStandard. I have easy-coding-standard.yml in my root. All is good) But wehen I use `./artisan insights -v` it seems like insights do not use `easy-coding-standard.yml`. It use another rules.

**Comment by olivernybroe** [comment]
So basically what you are requesting is if the ecs config is present, use that instead of our own?

**Comment by Zolotov88** [comment]
@olivernybroe Yes, you are right

**Comment by olivernybroe** [comment]
A problem with a custom config file like that is that we cannot tell if a sniff error should be part of Code, Complexity, Architecture or Style.
Right now we register the sniffs in classes so we know where to put them afterwards.

**Comment by Zolotov88** [comment]
Ok, I see. If so, I think that the ability to process individual files and folders and autofix is ​​very important.

**Comment by olivernybroe** [comment]
@Zolotov88 We now support processing individual files.🎉

I'll close this issue as this is prob. not something we will add support for as it will only complicate things as we have insights which is not from ECS. Having multiple config file is not something we will go for.

We have an issue for autofix which you can follow also #54. 
But thanks for reporting this to us! :)
