### ISSUE TITLE
Automatic docker build has failed 

### ISSUE THREAD

**Issue by Jibbarth** [nunomaduro/phpinsights#166]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| Library version  | 1.6.0

Looking at [travis build for 1.6.0](https://travis-ci.org/nunomaduro/phpinsights/builds/541623264), there is some fails :cry: 

```
Setting environment variables from repository settings
$ export DOCKER_PASSWORD=[secure]
The previous command failed, possibly due to a malformed secure environment variable.
Please be sure to escape special characters such as ' ' and '$'.
For more information, see https://docs.travis-ci.com/user/encryption-keys.
``` 

@nunomaduro May your password contains specials characters that should be escaped ? Then we could try restart a build :wink:

**Comment by nunomaduro** [comment]
Still not good? I have changed this.

**Comment by Jibbarth** [comment]
I relaunched the build for 1.6.0, but there is again an error.

But the message is clearer now :sweat_smile: 

```
$ export DOCKER_PASSWORD=[secure]
We were unable to parse one of your secure environment variables.
Please make sure to escape special characters such as ' ' (white space) and $ (dollar symbol) with \ (backslash) .
For example, thi$isanexample would be typed as thi\$isanexample. See https://docs.travis-ci.com/user/encryption-keys.
```

**Comment by olivernybroe** [comment]
@Jibbarth Oh lol, I also relaunched it and was just about to post the same results :)

**Comment by szepeviktor** [comment]
https://github.com/nunomaduro/phpinsights/commit/320780b4acb092777f8b08dd2b8e31230b84b0b4#commitcomment-34036318

@nunomaduro There is one already open

Maybe we could try docs.travis-ci.com/user/environment-variables/#defining-encrypted-variables-in-travisyml

**Comment by JustSteveKing** [comment]
Closing as no changes or updates for a couple of years. Will reinvestigate if this issue appears again
