### ISSUE TITLE
cant upgrade to v 1.6.0

### ISSUE THREAD

**Issue by michaelnguyen547** [nunomaduro/phpinsights#171]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| Library version  | 1.4.0

I m stuck @ v1.4.0, force v.1.60 will give this error

Problem 1
    - Conclusion: don't install sensiolabs/security-checker v6.0.0
    - Installation request for nunomaduro/phpinsights ^1.6 -> satisfiable by nunomaduro/phpinsights[v1.6.0].
    - Conclusion: remove symfony/polyfill-ctype v1.10.0
    - Installation request for sensiolabs/security-checker (locked at v5.0.3) -> satisfiable by sensiolabs/security-checker[v5.0.3].
    - Conclusion: don't install symfony/polyfill-ctype v1.10.0
    - nunomaduro/phpinsights v1.6.0 requires sensiolabs/security-checker ^6.0 -> satisfiable by sensiolabs/security-checker[6.0.x-dev, v6.0.0, v6.0.1].
    - sensiolabs/security-checker 6.0.x-dev requires symfony/polyfill-ctype ^1.11 -> satisfiable by symfony/polyfill-ctype[1.11.x-dev, v1.11.0].
    - sensiolabs/security-checker v6.0.1 requires symfony/polyfill-ctype ^1.11 -> satisfiable by symfony/polyfill-ctype[1.11.x-dev, v1.11.0].
    - Can only install one of: symfony/polyfill-ctype[1.11.x-dev, v1.10.0].
    - Can only install one of: symfony/polyfill-ctype[v1.11.0, v1.10.0].
    - Installation request for symfony/polyfill-ctype (locked at v1.10.0) -> satisfiable by symfony/polyfill-ctype[v1.10.0].

<!--
Love PHP Insights? Please consider supporting us via Patreon or OpenCollective:
👉  https://www.patreon.com/nunomaduro
👉  https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=66BYDWAT92N6L
--

**Comment by olivernybroe** [comment]
As far as I understand it (I suck at reading their messages), you have a lock for `symfony/polyfill-ctype` at v1.10.0, but v1.11.0, is required by `sensiolabs/security-checker`.

If this is not the case, could you please share your composer file (the dependencies and Dev dependencies section is enough)

**Comment by michaelnguyen547** [comment]
I run `composer update` and it worked. thanks
