### ISSUE TITLE
Not possible to remove ForbiddenSecurityIssues

### ISSUE THREAD

**Issue by EfeloPHP** [nunomaduro/phpinsights#172]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| Library version  | 1.6.0

I tried to remove the check ForbiddenSecurityIssues

```php
return [
    'preset' => 'symfony',

    'remove' => [
        ForbiddenSecurityIssues::class,
    ],
];
```

But I end up with this exception (It happened 😄) : 

In Results.php line 106:
  This should not happen  

PS : Adding the option "--disable-security-check" has no effect.

**Comment by Jibbarth** [comment]
Really good catch @EfeloPHP, thank you. 

For information, the option `--disable-security-check` will only don't throw an error code when phpinsights is launch, but in effect, it's doesn't disable the Insight. 

May the option name is wrong ? :roll_eyes:

**Comment by olivernybroe** [comment]
@Jibbarth Is this fixed now?

**Comment by nunomaduro** [comment]
Yes, his fix is merged.
