### ISSUE TITLE
UselessParenthesesSniff issue

### ISSUE THREAD

**Issue by michaelnguyen547** [nunomaduro/phpinsights#173]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| Library version  | 1.6.0

SlevomatCodingStandard\Sniffs\PHP\UselessParenthesesSniff raise on the below
`(a+ b) >= (c + d) ? a: c;` which the parentheses are required

**Comment by olivernybroe** [comment]
As far as I understand your parenthesis are not needed for that statement.
You can simply do `a+ b >= c + d ? a: c;`

**Comment by michaelnguyen547** [comment]
thanks for the insights. It makes sense.
