### ISSUE TITLE
[Windows] Color support in cmd.exe

### ISSUE THREAD

**Issue by askorad** [nunomaduro/phpinsights#176]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| Library version  | latest

Just need help... I am running phpinsights on PHPStorm terminal and the results are unreadable (see below). Can anyone help ?

`
?[33m[2019-06-13 08:29:20]?[39m `C:\wamp64\www\voPlatform`

      ?[42m         ?[49m            ?[42m         ?[49m            ?[42m         ?[49m            ?[43m         ?[49m
      ?[30;42;1m  80.8%  ?[39;49;22m            ?[30;42;1m  90.7%  ?[39;49;22m            ?[30;42;1m  85.0%  ?[39;49;22m            ?[30;43;1m  62.2%  ?[39;49;22m
      ?[42m         ?[49m            ?[42m         ?[49m            ?[42m         ?[49m            ?[43m         ?[49m

        ?[37;1mCode?[39;22m               ?[37;1mComplexity?[39;22m          ?[37;1mArchitecture?[39;22m            ?[37;1mStyle?[39;22m

Score scale: ?[31m◼?[39m 1-49 ?[33m◼?[39m 50-79 ?[32m◼?[39m 80-100

`

<!--
Love PHP Insights? Please consider supporting us via Patreon or OpenCollective:
👉  https://www.patreon.com/nunomaduro
👉  https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=66BYDWAT92N6L
--

**Comment by olivernybroe** [comment]
Could we get a little more information? :) 
What operation system are you using, which terminal are you using and what font are you using in that terminal.

**Comment by askorad** [comment]
Hi Oliver,

Thank you for your quick reply.

I am working on PhpStorm terminal :
PhpStorm 2018.2.2
Build #PS-182.4129.45, built on August 22, 2018
JRE: 1.8.0_152-release-1248-b8 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

And I am using the default font and I do not think that it can be changed…

I also tried on Windows PowerShell and I am facing the same issue



De : Oliver Nybroe <notifications@github.com>
Envoyé : jeudi 13 juin 2019 11:20
À : nunomaduro/phpinsights <phpinsights@noreply.github.com>
Cc : Vincent DAVID <vincent@askorad.fr>; Author <author@noreply.github.com>
Objet : Re: [nunomaduro/phpinsights] Unreadable results on PHPStorm terminal (#176)


Could we get a little more information? :)
What operation system are you using, which terminal are you using and what font are you using in that terminal.

**Comment by olivernybroe** [comment]
PHPStorm does not implement their own terminal, the uses the underlying default OS terminal or a custom one if set. Could you tell what is says in PHPStorm settings at `Tools -> Terminal -> Shell path`?

From the information you have given us, I would say I do not think it is related to PHPStorm, but it is a problem with windows terminal.

The characters you see is the ANSI color codes, because of a lack of support for it or it not being enabled. 

So some other information which could be nice for trying to figure it out.
- Windows version (the build number)
- php version (because of https://github.com/php/php-src/pull/2103)
- Is the ANSI color codes still there when if you add `--no-ansi`

**Comment by askorad** [comment]
You are right, it is using Windows terminal : the shell path is cmd.exe

I am running php 7.2.14 and my windows version is 17134.829 so not the latest which seems strange to me because Windows update is enabled on my machine…

I tried with –no-ansi  and even if I don’t get the colors, the results are much more readable 😊

Unfortunately, I am facing another issue : NunoMaduro\PhpInsights\Domain\Exceptions\InternetConnectionNotFound  : PHP Insights needs an internet connection to inspect security issues.

My machine is obviously connected to Internet…


De : Oliver Nybroe <notifications@github.com>
Envoyé : jeudi 13 juin 2019 13:46
À : nunomaduro/phpinsights <phpinsights@noreply.github.com>
Cc : Vincent DAVID <vincent@askorad.fr>; Author <author@noreply.github.com>
Objet : Re: [nunomaduro/phpinsights] Unreadable results on PHPStorm terminal (#176)


PHPStorm does not implement their own terminal, the uses the underlying default OS terminal or a custom one if set. Could you tell what is says in PHPStorm settings at Tools -> Terminal -> Shell path?

From the information you have given us, I would say I do not think it is related to PHPStorm, but it is a problem with windows terminal.

The characters you see is the ANSI color codes, because of a lack of support for it or it not being enabled.

So some other information which could be nice for trying to figure it out.

  *   Windows version (the build number)
  *   php version (because of php/php-src#2103<https://github.com/php/php-src/pull/2103>)
  *   Is the ANSI color codes still there when if you add --no-ansi

**Comment by olivernybroe** [comment]
To get the colored results, you have to make your terminal support ANSII color codes. Hopefully somebody else knows how to do this, I don't have Windows, so I unfortunately cannot test it myself.

If we find a solution for how to add the coloring in, then let's add it to the docs, as this is not the first time a question like this has been asked.

Regarding your other issue, could you open a new issue for that? I think it is related to us catching all exceptions from the package we are using for security checks and throwing a `InternetConnectionNotFound`.

**Comment by askorad** [comment]
Thanks a lot for your help.

I will open another issue for the Internet Connexion problem

De : Oliver Nybroe <notifications@github.com>
Envoyé : jeudi 13 juin 2019 15:18
À : nunomaduro/phpinsights <phpinsights@noreply.github.com>
Cc : Vincent DAVID <vincent@askorad.fr>; Author <author@noreply.github.com>
Objet : Re: [nunomaduro/phpinsights] Unreadable results on PHPStorm terminal (#176)


To get the colored results, you have to make your terminal support ANSII color codes. Hopefully somebody else knows how to do this, I don't have Windows, so I unfortunately cannot test it myself.

If we find a solution for how to add the coloring in, then let's add it to the docs, as this is not the first time a question like this has been asked.

Regarding your other issue, could you open a new issue for that? I think it is related to us catching all exceptions from the package we are using for security checks and throwing a InternetConnectionNotFound.

**Comment by pxgamer** [comment]
Are you using the legacy console in Windows 10?

If you right click on an open cmd window and go to the properties, it should have a checkbox at the bottom.

I was pretty sure that the normal cmd has support for colours.

**Comment by nunomaduro** [comment]
> Thanks a lot for your help.

This problem seems to be solved.

**Comment by askorad** [comment]
Checked or not checked, I have the same issue..
It’s a shame, but the most important are the figures
Thank’s for your help

De : Owen Voke <notifications@github.com>
Envoyé : mardi 25 juin 2019 07:59
À : nunomaduro/phpinsights <phpinsights@noreply.github.com>
Cc : Vincent DAVID <vincent@askorad.fr>; Author <author@noreply.github.com>
Objet : Re: [nunomaduro/phpinsights] [Windows] Color support in cmd.exe (#176)


Are you using the legacy console in Windows 10?

If you right click on an open cmd window and go to the properties, it should have a checkbox at the bottom.

I was pretty sure that the normal cmd has support for colours.

**Comment by olivernybroe** [comment]
@askorad Unfortunately this problem is not related to our package.
It's either an issue in your Windows setup, Core PHP or Symfony Console. 

There have been multiple issues reported on this in Symfony Console, I think your best bet is to follow the discussions in there, somewhere in the issues there might be a solution also. 
https://github.com/symfony/symfony/issues/19520


If anyone finds a easy solution, then we could add it in the docs.
