### ISSUE TITLE
UnusedFunctionParameterSniff does not work well with Laravel `magic`

### ISSUE THREAD

**Issue by michaelnguyen547** [nunomaduro/phpinsights#180]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| Library version  | 1.6.0

I can't remember what it called in Laravel but you can tell by looking at my code

```
    public function edit(State $state)
    {
        return view('admin.state.edit', compact('state'));
    }
```

I got `$state is never used` complaint. I am not sure if I can do anything about this or just ignore the complaint. I can possibly change `compact` to `['state' => $state ]` but I like the `compact` better.

**Comment by olivernybroe** [comment]
Thanks for reporting the issue! However we are already aware of this as it was reported in issue #52.
