### ISSUE TITLE
[internal] Increase line length

### ISSUE THREAD

**Issue by olivernybroe** [nunomaduro/phpinsights#184]
So right now this package has configuration which limits the line length to 80.

I think we should consider changing this to 120 which I think is a much more suitable line length.

We could also consider changing the default line length for our default preset to 120, as if we agree on 120 being the most optimal line length, it makes sense that the package agrees with it.

What are your guys opinion on this?

**Comment by nunomaduro** [comment]
I am fine with 80 chars. @Jibbarth What do you think?

**Comment by olivernybroe** [comment]
@nunomaduro There are a lot of places in our code where we do not follow the line length.

But if @Jibbarth agrees with having 80 chars length, then let's continue with that.

**Comment by Jibbarth** [comment]
I often config the line limit to 120 in my projects also. 
I found 80 is quite restrictive, but it may enforce code to have small functions without much indentation...

Or we can set lineLimit to 80 and absoluteLineLimit to 120 ? 
https://phpinsights.com/insights/style.html#line-length

**Comment by nunomaduro** [comment]
@Jibbarth That means that the coding fixer will apply breaking line on 120 only?

**Comment by olivernybroe** [comment]
The difference between the two parameters is if it reports a warning or an error.

So `absoluteLineLimit` will report an error, where `lineLimit` only reports a warning.
I like the idea of setting it to 80/120.

**Comment by nunomaduro** [comment]
Sounds good to me. Thanks @olivernybroe for bring this discussion up.

**Comment by olivernybroe** [comment]
Should we make this change to all presets also?

**Comment by nunomaduro** [comment]
No. This should be only for us.
