### ISSUE TITLE
[internal] Automatic doc generation in PR

### ISSUE THREAD

**Issue by olivernybroe** [nunomaduro/phpinsights#186]
Another internal post :) 

I have seen other packages are starting to use Netlify for doc hosting and one place where it really gives a great advantage is for PR's. 

Using Netlify we can set it up to build the docs on a PR, so we can see how it looks before it is merged in, without having to clone and build locally.

It would require a `netlify.toml` file containing
```
[build]
  base    = "docs"
  publish = "docs/.vuepress/dist"
  command = "yarn docs:build"
```
Don't know what work it would require in Netlify, but prob. not much.

**Comment by nunomaduro** [comment]
Never used `Netlify` before, so I am not sure about this.

**Comment by Jibbarth** [comment]
@olivernybroe Do you have examples of packages that use this? To see on PR how it is displayed?

**Comment by olivernybroe** [comment]
@jibbarth sure. This is a closed pr, but if you open up the information, there is a check called `netlify/deploy`. That is just a link to a static site with the docs from the pr.

https://github.com/nuwave/lighthouse/pull/803

**Comment by Jibbarth** [comment]
It look nice ! Is previews aren't indexed by search engines ? (I hope not, but I just thought about that :sweat_smile:)

Anyway, it could be interesting to have this :+1:

**Comment by olivernybroe** [comment]
Haha I have no idea if they are tbh. :D but don't think they are, as that would be really impractical.😂

**Comment by nunomaduro** [comment]
I think we should close this for now. It's a nice idea, let's maybe re-open this issue later alright?
