### ISSUE TITLE
PHP Insights needs an internet connection to inspect security issues.

### ISSUE THREAD

**Issue by merlin334** [nunomaduro/phpinsights#192]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| Library version  | 1.6.0

Hi Nuno,

Running:
php artisan insight
gives the following exception.

```php
Exception trace:

  1   Symfony\Component\HttpClient\Exception\TransportException::("Peer certificate cannot be authenticated with given CA certificates for "https://security.symfony.com/check_lock".")
      D:\www\laravel.test\laravel\vendor\symfony\http-client\Chunk\ErrorChunk.php:105

  2   Symfony\Component\HttpClient\Exception\TransportException::("Peer certificate cannot be authenticated with given CA certificates for "https://security.symfony.com/check_lock".")
      D:\www\laravel.test\laravel\vendor\symfony\http-client\Response\CurlResponse.php:264
```
- Tried it on 2 different desktops, 2 laptops and vmware all with windows 10.
- Tried with 3 different internet providers, one being tethering from mobile 4G network Vodafone.
- Tried on clean Laravel 5.8 install.
- Tried composer update nunomaduro/phpinsights
- Disabled antivirus, and firewall.

![insights](https://user-images.githubusercontent.com/9083576/59848814-c27a6e80-936e-11e9-880c-6c34511c2e13.JPG)

Any idea how I might fix this?
Thanks

<!--
Love PHP Insights? Please consider supporting us via Patreon or OpenCollective:
👉  https://www.patreon.com/nunomaduro
👉  https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=66BYDWAT92N6L
--

**Comment by olivernybroe** [comment]
Can you access the site directly without certificate issues? https://security.symfony.com/

Else this might be an issue you have to post on https://github.com/sensiolabs/security-checker.

**Comment by nunomaduro** [comment]
This is an issue of the security-checker package. Anyway, we should improve the code updating that generic exception to a specific one.

**Comment by merlin334** [comment]
Yes i tried that too.
![certificate](https://user-images.githubusercontent.com/9083576/59850411-dc1db500-9372-11e9-85d2-3234f1daa7e4.JPG)

**Comment by merlin334** [comment]
Updated to 1.7, same error.

**Comment by olivernybroe** [comment]
@merlin334 Does this error also happen if you run https://github.com/sensiolabs/security-checker directly?

**Comment by nunomaduro** [comment]
@olivernybroe If the error also happens, this is not our problem and we can close the issue.

**Comment by merlin334** [comment]
security-checker.phar works, but the composer one gives the same error.
Is there any way to skip this security check?
I guess we can close the issue.

**Comment by olivernybroe** [comment]
You can run with `disable-security-check`. 

Thank you for testing this out, I'll encourage you to report the issue on their Github. If it turns out to be a bug in some setup, then please tell us and we can consider adding it to the docs.🎉

**Comment by merlin334** [comment]
```disable-security-check``` didn't work, but in config/insights.php if you add ForbiddenSecurityIssues::class to ```'remove'=> [ ForbiddenSecurityIssues::class ]```, it works.
Also I opened a issue on https://github.com/sensiolabs/security-checker/issues/165.

**Comment by merlin334** [comment]
Fixed updating symfony/http-client to v4.3.2.

**Comment by johnbacon** [comment]
We're experiencing this again as of today.

**Comment by rpatew2c** [comment]
@johnbacon It seems the URL `repo.packagist.org` has changed or been removed. When I change the value of `ForbiddenSecurityIssues::PACKAGIST_ADVISORIES_URL` to `https://packagist.org/api/security-advisories/` [as noted on the packagist api doc page here ](https://packagist.org/apidoc#list-security-advisories) it works again
