### ISSUE TITLE
Not recognizing @Route annotation in Symfony

### ISSUE THREAD

**Issue by goncalomcunha** [nunomaduro/phpinsights#193]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| Library version  | 1.7.0

phpinsights is not recognizing the `@Route` annotation in Symfony, even though it is being used to define routes in the controller.

Message:
`Type Symfony\Component\Routing\Annotation\Route is not used in this file`

The code

```php
<?php declare(strict_types = 1);

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\Routing\Annotation\Route;

class MovieController extends AbstractController
{
    /**
     * @Route("/")
     */
    public function homepage(): JsonResponse
    {
        return $this->json(['message' => 'Hello']);
    }
```

These messages are also thrown:
`src/Controller/MovieController.php:14: Method \App\Controller\MovieController::homepage() does not need documentation comment.`
`Type Symfony\Component\Routing\Annotation\Route is not used in this file`

**Comment by olivernybroe** [comment]
What should it check for in the `@route` annotation?
Other than that it is a necessary doc block if there is a route annotation?

**Comment by goncalomcunha** [comment]
I think it could check, at least, if the HTTP method is defined

**Comment by Jibbarth** [comment]
You can configure the sniff `SlevomatCodingStandard\Sniffs\Namespaces\UnusedUsesSniff` by adding in your `phpinsights.php` the following configuration to search in annotation

```
\SlevomatCodingStandard\Sniffs\Namespaces\UnusedUsesSniff::class => [
    'searchAnnotations' => true
]
```

See https://phpinsights.com/insights/style.html#unused-uses

May be we should configure it by default to true for symfony preset

**Comment by nunomaduro** [comment]
`\SlevomatCodingStandard\Sniffs\Namespaces\UnusedUsesSniff::class => [
    'searchAnnotations' => true
]`

this should be on the default preset @Jibbarth.

**Comment by nunomaduro** [comment]
@Jibbarth Can we make a pull request on this?

**Comment by Jibbarth** [comment]
@nunomaduro I can do it. 

If the config should be on defaultPreset, then others preset should extend defaultPreset, isn't it?

**Comment by nunomaduro** [comment]
Should be on the core default preset.
