### ISSUE TITLE
Class 'Symfony\Component\Config\ConfigCache' not found

### ISSUE THREAD

**Issue by AhmadWaleed** [nunomaduro/phpinsights#194]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| nunomaduro/phpinsights version  | v1.7.0
| laravel/framework version  | v5.8.2

- Getting this error `Class 'Symfony\Component\Config\ConfigCache' not found` when running php artisan insights?

Already Tried: 
```bash
$ composer install 
$ composer update 
$ composer dump-autoload 
```

**Comment by olivernybroe** [comment]
Please use the template it helps us to not answer questions like which version you are running this on.

Try installing your composer dependencies again and recreate your autoload file.

**Comment by AhmadWaleed** [comment]
@olivernybroe I updated the issue according to the template and already tried steps which you mentioned above.

**Comment by olivernybroe** [comment]
I am not able to reproduce this. Tried with a fresh Laravel installation and then installing the package, but it did not fail.

Could you give the steps to reproduce it?

**Comment by nunomaduro** [comment]
@AhmadWaleed Can you share your composer.json?

**Comment by AhmadWaleed** [comment]
> I am not able to reproduce this. Tried with a fresh Laravel installation and then installing the package, but it did not fail.
> 
> Could you give the steps to reproduce it?
> 
> Also when I said install composer dependencies again I should prob. had been a little more specific. I meant delete the `vendor` folder so it has to install everything again, sometimes the vendor folder gets corrupt.

It worked after deleting the vendor folder and `composer update` thanks guys
