### ISSUE TITLE
`* Closing connection 0` warning

### ISSUE THREAD

**Issue by nunomaduro** [nunomaduro/phpinsights#198]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| Library version  | latest

Since we have included the version of the `v6.0` of symfony security we now see this message `* Closing connection 0`.

```
Interfaces ........................................................ 12.2 %
Globally ........................................................... 8.2 %
Traits ............................................................. 0.0 %

* Closing connection 0
[MISC] 97.8 pts on coding style and 0 security issues encountered

Press enter to see code issues...
```

**Comment by olivernybroe** [comment]
Hmm not able to reproduce this on my setup.

**Comment by olivernybroe** [comment]
@nunomaduro is this still happening for you?

**Comment by nunomaduro** [comment]
Let me check

**Comment by nunomaduro** [comment]
Yeah, still there.

<img width="701" alt="Screenshot 2019-08-29 at 13 00 51" src="https://user-images.githubusercontent.com/5457236/63935183-3d41c300-ca5d-11e9-809f-1c1a2c55718d.png">

**Comment by olivernybroe** [comment]
Hmm I think it might be related to the security checker. 
Looks like it is caused by Curl.

**Comment by olivernybroe** [comment]
This seemed to happen because of a old curl edition. Try updating the curl edition in php

https://github.com/php-curl-class/php-curl-class/issues/596

**Comment by nunomaduro** [comment]
True. Sounds fixed, thanks!
