### ISSUE TITLE
[Internal] Raise our own scores above 90

### ISSUE THREAD

**Issue by szepeviktor** [nunomaduro/phpinsights#203]
See current expectations in https://github.com/nunomaduro/phpinsights/blob/master/composer.json#L68

Suggested goal: `--min-quality=90 --min-architecture=90 --min-style=97.8`

**Comment by olivernybroe** [comment]
Damn, that sounds like actual work 😅

**Comment by szepeviktor** [comment]
To set an example for users.

**Comment by olivernybroe** [comment]
If you are up for it, a PR would be really welcome.

**Comment by szepeviktor** [comment]
:( https://github.com/nunomaduro/phpinsights/pull/214#issuecomment-509784434

**Comment by olivernybroe** [comment]
We can still try and raise the scores above 90, we just don't want the complexity score added. 

(sorry if I might have closed your PR for that reason alone)

**Comment by szepeviktor** [comment]
Okay, I leave it to you.
