### ISSUE TITLE
Mixed results on same code base.

### ISSUE THREAD

**Issue by michaelwps** [nunomaduro/phpinsights#206]
| Q                | A
| ---------------- | -----
| Bug report?      | possibly
| Feature request? | no
| Library version  | 1.7.0

i get mixed results between runing
`php artisan insights`

![image](https://user-images.githubusercontent.com/29801890/60388122-de160100-9a61-11e9-9a39-084a6f8794be.png)

`./vendor/bin/phpinsights`
![image](https://user-images.githubusercontent.com/29801890/60388149-1f0e1580-9a62-11e9-8df9-6f3c10315b5c.png)

**Comment by olivernybroe** [comment]
The difference is the config file.
The artisan command automatically uses the config from your config folder while with the bin edition you have to specify which config file manually :) 

So try specifying the `config` param when using bin path and see if it fixes it for you. 🧐
