### ISSUE TITLE
analyse sub dir error

### ISSUE THREAD

**Issue by smartyaunt** [nunomaduro/phpinsights#208]
vendor/bin/phpinsights  analyse app

In AnalyseCommand.php line 63:
  The file `composer.json` must exist. You should run PHP Insights from the root of your project.

-------------please help, thank

**Comment by Jibbarth** [comment]
:thinking: This feature is not released yet.

@smartyaunt Could you try by requiring dev-master version ? 

```
$ composer require nunomaduro/phpinsights:dev-master 
```

**Comment by smartyaunt** [comment]
@Jibbarth Thank Bro, it's work
