### ISSUE TITLE
[internal] Release 1.8.0

### ISSUE THREAD

**Issue by nunomaduro** [nunomaduro/phpinsights#210]
[TODO]

@Jibbarth Up to proceed with this release?

**Comment by Jibbarth** [comment]
Refs [changelog](https://github.com/nunomaduro/phpinsights/compare/v1.7.0...master)

To summarize, we have : 

## New feature: 

* Authorize analyse of one file or specific directory (#195)

## Improvments: 

* Configure search use in annotation (#196)
* Add changelog to website (#204)

## Fix:

* Merge config with default config (#196)


Before releasing, I think it could be great if we had **Add formating support** (#201). With this, the release will be more awesome :upside_down_face: 
WDYT @nunomaduro @olivernybroe ?

I also noticed that online docs is broken (https://phpinsights.com/ => got a 403 forbidden) 
@nunomaduro can you check why ?

**Comment by nunomaduro** [comment]
@Jibbarth Fixed for the 403.

**Comment by nunomaduro** [comment]
I will try to validate the `Add formating support` tonight or this weekend. But I can't promise.

**Comment by olivernybroe** [comment]
Sounds great! 
I also think it could be nice if formatting could be added before next release. 😀

The phpstan can wait for a future release, that one also need some love to make the code pretty 😉

**Comment by olivernybroe** [comment]
Hell yeah, now we got formatting support merged in! 👍 

Let's get the next release out and make our first tweet release on the dedicated twitter account 😮

**Comment by nunomaduro** [comment]
done. 🔥
