### ISSUE TITLE
The file `composer.json` must exist. You should run PHP Insights from the root of your project.

### ISSUE THREAD

**Issue by ramizmanked** [nunomaduro/phpinsights#217]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| Library version  | 1.7.0

I'm getting **The file `composer.json` must exist. You should run PHP Insights from the root of your project.** error while executing command  "./vendor/bin/phpinsights analyse ./index.php" in terminal. 

**Note:** It throws error even if I execute command from root of my project.

_Any help would be much appreciated._

![phpinsight_error](https://user-images.githubusercontent.com/30211166/61049457-26d69e00-a402-11e9-839f-81022ea40be0.png)

**Comment by akosglue** [comment]
may be related https://github.com/nunomaduro/phpinsights/issues/129

**Comment by akosglue** [comment]
@ramizmanked 
I tried to do the same as well.
As I understood from the comments in https://github.com/nunomaduro/phpinsights/issues/129, we cannot do it (yet). The first argument for a folder is only to specify the project root, not for an individual file or folder to be analyzed.

**Comment by akosglue** [comment]
And see this: https://github.com/nunomaduro/phpinsights/issues/208

**Comment by ramizmanked** [comment]
Thanks @akosglue for guiding me.

I got the solution from [here](https://github.com/nunomaduro/phpinsights/issues/208#issuecomment-508361216) if anyone is looking for.

**Comment by olivernybroe** [comment]
Yep, when the next release is out this will be fixed! 
Until then you have to use the master branch for this to work.
