### ISSUE TITLE
Publishing Laravel resources

### ISSUE THREAD

**Issue by judgej** [nunomaduro/phpinsights#218]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| Library version  | 1.7.0

When running as a Laravel artisan command, it provides the instruction:

    [ERROR] First, publish the configuration using: php artisan vendor:publish

Many packages do this, and they shouldn't IMO. This will publish config files and resources from ALL installed packages that have not yet published these things. Instead, the instructions need to limit any effects to this package only:

    php artisan vendor:publish "NunoMaduro\PhpInsights\Application\Adapters\Laravel\InsightsServiceProvider"

<!--
Love PHP Insights? Please consider supporting us via Patreon or OpenCollective:
👉  https://www.patreon.com/nunomaduro
👉  https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=66BYDWAT92N6L
--

**Comment by xuanquynh** [comment]
"php artisan vendor:publish" command will show a list of things for you to choose. Just run it and pick the right thing for you.

**Comment by judgej** [comment]
Ah, yes, shows how long since I used that command without options!
