### ISSUE TITLE
0.0% Complexity score is not aligned

### ISSUE THREAD

**Issue by szepeviktor** [nunomaduro/phpinsights#22]
![kép](https://user-images.githubusercontent.com/952007/57349921-47614e00-715c-11e9-9639-b18ae5bc111d.png)

**Comment by nunomaduro** [comment]
Can I see that source code? 😆

**Comment by szepeviktor** [comment]
No :( 100k sloc and not open-source.

**Comment by nunomaduro** [comment]
Alright, but 0.0 it’s impossible. Possible a bug.

**Comment by szepeviktor** [comment]
I think 1.0% (1-9) would also ruin the output

**Comment by nunomaduro** [comment]
Alright, to this issue we just need to make sure that this method https://github.com/nunomaduro/phpinsights/blob/9a4ae0ff7975b554102a10fae3cf08c3d6b6c998/src/Application/Console/Style.php#L277 returns a 5 chars string.
