### ISSUE TITLE
Missing logo in the website

### ISSUE THREAD

**Issue by nunomaduro** [nunomaduro/phpinsights#223]
**Goal**: Perform a pull request on the website (https://github.com/nunomaduro/phpinsights/tree/master/docs)  adding the `gif` to the website, just like in our readme.

<img width="1536" alt="Screenshot 2019-07-17 at 11 46 43" src="https://user-images.githubusercontent.com/5457236/61402726-975d3f00-a888-11e9-925b-ee5c604298f2.png">

**Comment by caneco** [comment]
on it…

**Comment by ibrahim-mubarak** [comment]
I suppose we can close this issue?

**Comment by nunomaduro** [comment]
Yes, thank you!
