### ISSUE TITLE
ForbiddenSecurityIssues: Show other results even if ForbiddenSecurityIssues fails

### ISSUE THREAD

**Issue by FFDevelopment** [nunomaduro/phpinsights#229]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| Library version  | 1.7.0

Because you never know, if you always have an available internet connection, it would be nice to skip ForbiddenSecurityIssues, if no internet connection is available.

I mean, if you don't have an internet connection, you could still get the other results. In the current situation, you would not get any results.

**Comment by olivernybroe** [comment]
In the master branch we have support for skipping it with a parameter.

**Comment by olivernybroe** [comment]
@Jibbarth Am I remembering wrong about you fixing this or was it something related?

**Comment by Jibbarth** [comment]
:thinking: We have a `--disable-security-check` option but it only  don't throw an error code when phpinsights is launched. But we can remove the insight in the `phpinsights.php` file. 

IMO, @FFDevelopment is right, and we should add error on insight when there is no connection to still get results.

**Comment by olivernybroe** [comment]
@jibbarth sounds good! I think you are right, that might be the right direction.

**Comment by Jibbarth** [comment]
Fix will be available in 1.10 or now in dev-master ! Thank you @FFDevelopment for the issue :+1:
