### ISSUE TITLE
How not to omit issues?

### ISSUE THREAD

**Issue by szepeviktor** [nunomaduro/phpinsights#23]
> +1257 issues omitted

**Comment by nunomaduro** [comment]
You can now pass the option `-v` to display all issues. https://github.com/nunomaduro/phpinsights/commit/fec71b4efff4d4fb2dd3a5981d80c752621d81c2

**Comment by szepeviktor** [comment]
Thanks.

**Comment by eusonlito** [comment]
Hi @nunomaduro, I'm using Laravel. There are any option on `config/insights.php` to set option as fixed?

**Comment by olivernybroe** [comment]
@eusonlito Currently no, 

However not sure if that also belongs in the config file or simply a custom command. 

You could for example in Laravel create a new command which runs php insights with the arguments you want. However, I would recommend you to open a new issue with this, and we can discuss it. 👍

**Comment by eusonlito** [comment]
@olivernybroe ok! done in https://github.com/nunomaduro/phpinsights/issues/376
