### ISSUE TITLE
ErrorException  : Undefined index: scope_closer

### ISSUE THREAD

**Issue by learn2develop** [nunomaduro/phpinsights#234]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| Library version  | 1.7

 ErrorException  : Undefined index: scope_closer

```php
}
    204| 
    205|                        $token = $tokens[$pointer];
    206|                        if (in_array($token['code'], TokenHelper::$typeKeywordTokenCodes, true)) {
  > 207|                                $pointer = $token['scope_closer'] + 1;
    208|                                continue;
    209|                        }
    210|                        if (self::isAnonymousFunctionUse($phpcsFile, $pointer)) {
    211|                                $pointer++;
```

 Exception trace:
  1   Illuminate\Foundation\Bootstrap\HandleExceptions::handleError("Undefined index: scope_closer", "vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/UseStatementHelper.php")
      vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/UseStatementHelper.php:207

  2   SlevomatCodingStandard\Helpers\UseStatementHelper::getUseStatementPointers(Object(NunoMaduro\PhpInsights\Domain\File))
      vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/UseStatementHelper.php:149

**Comment by olivernybroe** [comment]
What code did this fail on?
What insight is it failing on?

This error might look like it is not related to us, but to [`SlevomatCodingStandard`.](https://github.com/slevomat/coding-standard)

**Comment by learn2develop** [comment]
I have simply installed it on my Laravel 5.8, run the artisan command and the error showed up. It is difficult to say which code it did failed on as my Laravel installation is quite big. 

I do not know what do you mean by the second question?

**Comment by olivernybroe** [comment]
Well according to the part of the stack trace you gave us, I can see that it is probably caused by a `use` statement.

All the stuff we check for is displayed in what we call a insight. So for example if you have a useless  use statement, that is an insight checking for that. Under the hood it is using phpcs sniffs, and one of those sniffs are giving the error you are seeing. 
With the full exception trace, I should be able to see which one it is.

**Comment by learn2develop** [comment]
Hmm, ok so it trips over this file https://github.com/etrepat/baum/blob/master/src/Baum/Generators/stubs/model.php. Is this something for your package or for the `SlevomatCodingStandard`?

**Comment by olivernybroe** [comment]
Looking at the file, it does not look like it is valid php. Considering that it is a stub you should probably exclude it from code analysis. https://phpinsights.com/insights/#configure-insights

**Comment by learn2develop** [comment]
Excluded, thanks for help
