### ISSUE TITLE
Can't make it work with Lumen. 

### ISSUE THREAD

**Issue by neoplomero** [nunomaduro/phpinsights#235]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? |no
| Library version  | 1.7.^

- Hey Lads. Can't make this work properly with Lumen. What I can't make work is the configuration. I'm trying to use the laravel preset or any other change in the config and it is not working. I already set the app.php file on bootstrap to load the config files.

Any idea why? maybe I'm missing something. Any documentation around or? Thanks in advance

<!--
Love PHP Insights? Please consider supporting us via Patreon or OpenCollective:
👉  https://www.patreon.com/nunomaduro
👉  https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=66BYDWAT92N6L
--

**Comment by olivernybroe** [comment]
How do you run phpinsights? With the artisan command or the bin file?

**Comment by neoplomero** [comment]
I was running with the bin file bu twas't picking the configs. I wanted to run it with artisan but was giving me troubles. The solution was:

Added the command on kernel:

```
use NunoMaduro\PhpInsights\Application\Adapters\Laravel\Commands\InsightsCommand;

protected $commands = [
    InsightsCommand::class,
];
```
In the AppServiceRepository:

```
use NunoMaduro\PhpInsights\Application\Injectors\Repositories as PHPInsightsRepositories;

// in Register()
$repositories = $this->app->make(PHPInsightsRepositories::class)->__invoke();
foreach ($repositories as $abstract => $concrete) {
    $this->app->bind($abstract, $concrete);
}
```
In Bootstrap/App.php

`uncommented $app->register(App\Providers\AppServiceProvider::class);`

And Manually copied the config file:

`cp vendor/nunomaduro/phpinsights/stubs/laravel.php Config/insights.php`

and loaded the config  In Bootstrap/App.php:

Then everything worked fine and did a double backflip together with my chair.

**Comment by olivernybroe** [comment]
Nice that you found a solution!

I am not a Lumen user, but why did our service provider not work for you?

**Comment by neoplomero** [comment]
Mostly because of an error:

` Call to undefined method Laravel\Lumen\Application::configPath()`

+

Time

**Comment by olivernybroe** [comment]
Ah thanks. 
So we need to replace the right side of the array here
```
        $this->publishes([
            __DIR__ . '/../../../../stubs/laravel.php' => $this->app->configPath('insights.php'),
        ], 'config');
```

with a method that get's the config path correctly depending on if it's Lumen or Laravel.
So if it's Lumen the method is called `getConfigurationPath` and if Laravel `configPath`.

**Comment by andrewnclark** [comment]
Decided to take a look into this, figured it was pretty straight forward on the surface of things. However, having changed the above code to detect Lumen and call `getConfigurationPath` instead, it became apparent that `vendor:publish` isn't support by Lumen so the config available.

I'm happy to continue work on this but I'm guessing everyone's Lumen project tackles configuration differently (just based on the lack of a standard folder/publish system). 

I'm open to any ideas/direction and will continue to look at options in the mean time.

**Comment by olivernybroe** [comment]
@andrewnclark Thank you for looking into this.

You are totally right, Lumen does not have a publish command. In Lumen we have the `configure` method in `Application` which loads a file into the configuration. 

Obviously using `.env` for configs isn't feasible in this scenario. So we have to make another solution. 

I think we should for the first solution just fix it with docs. So in our docs we basically just link our config file and say that they should add this file to their repo in the path they want it in and then in their `bootstrap/app.php`, they should run `$app->configure` to load the file.

This way we have a solution that works, without having to do a lot of custom stuff.

@andrewnclark You are more than welcome to create this PR! ❤️ 
Will you be up for doing the doc solution also?

**Comment by andrewnclark** [comment]
Not a problem I'll put something together in the next few days around my work schedule. Happy to help.

**Comment by olivernybroe** [comment]
Thanks @andrewnclark!
