### ISSUE TITLE
Would it be possible to add hyperlinks to Insights output?

### ISSUE THREAD

**Issue by peterfox** [nunomaduro/phpinsights#237]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| Library version  | 1.7.0

It would be great to add links in the terminal output in some fashion that could open the IDE or open the code on github. I often find it slow to try and track down the line that needs to be changed. If this isn't possible then it would be good to explore other options maybe to streamline highlighting where the problems are.

<!--
Love PHP Insights? Please consider supporting us via Patreon or OpenCollective:
👉  https://www.patreon.com/nunomaduro
👉  https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=66BYDWAT92N6L
--

**Comment by olivernybroe** [comment]
Good idea, I have been thinking about how to do this for some time.
Haven't found any official information on how to implement it, but might be able to mix something together by looking at how other tools do it.

**Comment by Gummibeer** [comment]
https://plugins.jetbrains.com/plugin/7677-awesome-console
will solve it for PHPStorm without any changes. I bet that there are similar plugins for vscode and all the others.

**Comment by olivernybroe** [comment]
Sounds awesome. 
We could recommend users to install that plugin in the docs until phpstorm is able to handle it themselves.

**Comment by nunomaduro** [comment]
@Gummibeer Maybe can you pull request to the website that information?

**Comment by olivernybroe** [comment]
I just tested out the plugin and it works like a charm. A big fan of adding it to the docs.

@peterfox The plugin solved the problem for phpstorm and vscode is already able to do this.
Is this also a solution for you?

**Comment by peterfox** [comment]
@olivernybroe it's good enough for me.

**Comment by Jibbarth** [comment]
It'll be available in 1.10 or now in dev-master ! Thanks for the issue :+1:
