### ISSUE TITLE
 About Unused parameter

### ISSUE THREAD

**Issue by sohaha** [nunomaduro/phpinsights#239]
Please ignore the others first. According to the following example, 

$aaa and $bbb are anonymous functions of the same structure. 

In case of using $value, there is a way not to prompt "Unused parameter $key"

![20190808172710](https://user-images.githubusercontent.com/18098083/62691747-e28aed80-ba01-11e9-9ff0-bad6cbe70e7e.png)

```php
<?php
$aaa = static function ($key, $value) {
    var_dump($value);
};

$bbbb = static function ($key, $value) {
    var_dump($key);
};

// $c Uncertain
// one
$ccc = 'aaa';
$$ccc("k", "v");

// tow
$ccc = 'bbbb';
$$ccc("k", "v");
```

**Comment by olivernybroe** [comment]
You could silence the error on the whole file. 
Obviously in `bbb` you could just remove the variable `value`.

**Comment by sohaha** [comment]
> You could silence the error on the whole file.
> Obviously in `bbb` you could just remove the variable `value`.

No, I mean aaa's mistake, not bbb.

**Comment by olivernybroe** [comment]
Yes, that's why I said you could silence the error on the whole file by adding the file in the `exclude` array.

You could also remove it by adding the following annotation to phpdocs for that function `@phpcsSuppress`.

**Comment by olivernybroe** [comment]
Another solution would be to completely remove the insight about unused parameters
