### ISSUE TITLE
Colors in CI

### ISSUE THREAD

**Issue by guillaumebriday** [nunomaduro/phpinsights#241]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| Library version  | 1.7

Hey! Thank you for your work, it's very good!

There is a [dedicated section](https://phpinsights.com/continuous-integration.html#continuous-integration) for CI which it's great but do you know how to enable colors in the Web terminal ?

I use GitLab CI, and it's all black:

<img width="639" alt="Screenshot 2019-08-12 at 23 33 41" src="https://user-images.githubusercontent.com/8252238/62900341-2f502a80-bd5a-11e9-91d2-8519f6da8d49.png">

Thank you in advance

**Comment by Jibbarth** [comment]
Could you try with `--ansi` option ?

**Comment by guillaumebriday** [comment]
Ok I have colors now, but it seems that Gitlab does not reset lines on `\r` so the results are still weird

cf: https://gitlab.com/guillaumebriday/todolist-backend-laravel/-/jobs/271203328

I don't think you can do anything more here

Thank you for your help!
