### ISSUE TITLE
Add ability to config excluding path

### ISSUE THREAD

**Issue by robsontenorio** [nunomaduro/phpinsights#243]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| Library version  | -

Hi @olivernybroe ! I am using Lighthouse and would be nice to add ability to exclude entire paths, not only files. Once we know, most of time those parameters will not be used in those methods.

```php
'config' => [
        \SlevomatCodingStandard\Sniffs\Functions\UnusedParameterSniff::class => [
            'exclude' => [
                'src/Path/To/My/File.php',
                'app/GraphQL/Mutations',
            ],
        ],
    ],
```

```graphql
public function resolve($rootValue, array $args, GraphQLContext $context, ResolveInfo $resolveInfo)
    {
      //
    }
```

**Comment by robsontenorio** [comment]
Another example (wont work)

```bash
 [Style] Line length:
  resources/lang/en/validation.php:103: Line exceeds 80 characters; contains 90 characters
  resources/lang/en/validation.php:104: Line exceeds 80 characters; contains 99 characters
  resources/lang/en/validation.php:112: Line exceeds 80 characters; contains 84 characters
```

```php
'config' => [
     LineLengthSniff::class => [
            'exclude' => [
                'resources/lang/*'
            ]
        ]
]
```

**Comment by olivernybroe** [comment]
For adding support for the following we need to update the class [`SniffDecorator`](https://github.com/nunomaduro/phpinsights/blob/master/src/Domain/Sniffs/SniffDecorator.php).

In this file we have the method `pathsAreEqual`, which has to used some advanced logic that actually checks paths and regexs also.

The best scenario here would be to use the `Symfony\Component\Finder\Iterator\ExcludeDirectoryFilterIterator`, as that one actually handles all of this for us and we don't have to support it ourself.

**Comment by Jibbarth** [comment]
In 1.10 we can now pass folder in exclude config for an Insight :wink: Thanks for the suggestion :+1:
