### ISSUE TITLE
Remove file for an Insights:class

### ISSUE THREAD

**Issue by neoplomero** [nunomaduro/phpinsights#246]
| Q                | A
| ---------------- | -----
| Feature request? | yes

Would be great to be able to remove a file just for a given class.  :) So the file is not evaluated by that class but it is by all the other insights classes.

<!--
Love PHP Insights? Please consider supporting us via Patreon or OpenCollective:
👉  https://www.patreon.com/nunomaduro
👉  https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=66BYDWAT92N6L
--

**Comment by olivernybroe** [comment]
Do you mean this?
https://phpinsights.com/insights/#configure-insights-2

**Comment by neoplomero** [comment]
Indeed, I do.
