### ISSUE TITLE
"Press any key" is really just ENTER

### ISSUE THREAD

**Issue by szepeviktor** [nunomaduro/phpinsights#25]
other keys won't make it continue

**Comment by nunomaduro** [comment]
Can you make a pull request to fix this buddy? You just have to edit this line: https://github.com/nunomaduro/phpinsights/blob/9a4ae0ff7975b554102a10fae3cf08c3d6b6c998/src/Application/Console/Style.php#L262.

**Comment by szepeviktor** [comment]
I hope you were referring to this solution.
