### ISSUE TITLE
Add ability to export results from 'php artisan code:analyse'

### ISSUE THREAD

**Issue by calvinchiulele** [nunomaduro/phpinsights#261]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| Library version  | 1.9.0

Hi all contributors from PHPInsights. Open source community wouldn't be the same without you!
Can we have a feature in phpinsights to export the result issued from the command 'php artisan code:analyse' to JSON and txt formats?

<!--
Love PHP Insights? Please consider supporting us via Patreon or OpenCollective:
👉  https://www.patreon.com/nunomaduro
👉  https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=66BYDWAT92N6L
--

**Comment by nunomaduro** [comment]
Did you tried `--format=json`?

**Comment by calvinchiulele** [comment]
> Did you tried `--format=json`?

I didn't found it on 'php artisan code:analyse' but I found it on 'vendor/bin/phpinsights' binary.

Thanks for the help.

**Comment by nunomaduro** [comment]
It may be a bug.

**Comment by FFDevelopment** [comment]
@calvinchiulele `php artisan code:analyse` is not phpinsights. it's larastan

**Comment by calvinchiulele** [comment]
> @calvinchiulele `php artisan code:analyse` is not phpinsights. it's larastan

Thank you. I made confusion about the packages.
