### ISSUE TITLE
[Docs] Add favicon

### ISSUE THREAD

**Issue by olivernybroe** [nunomaduro/phpinsights#264]
In our documentation we do not show our icon which is a big shame now that @caneco did such a nice job.

You can find the icon to use for favicon under `art/heart.svg`. 
This has to be added in vuepress. In their docs they have a simple example of how to do it [here](https://vuepress.vuejs.org/config/#head).

**Comment by nunomaduro** [comment]
For newcomers - here is the source code: https://github.com/nunomaduro/phpinsights/tree/master/docs.

Setup locally:

```bash
git clone https://github.com/nunomaduro/phpinsights
cd phpinsights
yarn
yarn run vuepress dev
```
