### ISSUE TITLE
[feat] Add .bat file

### ISSUE THREAD

**Issue by olivernybroe** [nunomaduro/phpinsights#266]
In both `phpcs` and `phpmd` they have a `.bat` file to run the system directly on Windows without having to add `php` in front of it.

I think this package should also add this in for easier usage on Windows. 

Adding this in would also solve the problem of being able to run phpinsights via the phpstorm plugin.

Here are the bat files from [phpmd](https://github.com/phpmd/phpmd/blob/master/src/bin/phpmd.bat) and [phpcs](https://github.com/squizlabs/PHP_CodeSniffer/blob/master/bin/phpcs.bat) for reference.

**Comment by pxgamer** [comment]
These seem to be generated automatically by Composer on Windows. 🤔

**Comment by olivernybroe** [comment]
@pxgamer Ah did not know that, cool!

Why do most of the packages include a .bat file then 🤔 

I also found a way to generate them even if you are running composer install from inside a docker. https://github.com/composer/composer/issues/7370

**Comment by pxgamer** [comment]
I have no idea 🤷‍♂
