### ISSUE TITLE
Problems with Laravel viewAny Policy

### ISSUE THREAD

**Issue by ibrahim-mubarak** [nunomaduro/phpinsights#267]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| Library version  | 1.9.0

I have the following piece of code 

```php
    /**
     * @SuppressWarnings("unused")
     *
     * @param \Illuminate\Foundation\Auth\User|null $user
     *
     * @return bool
     */
    public function viewAny(?User $user = null)
    {
        return true;
    }
```

This generates `Unused parameter $user.` 
However removing `$user` results in Laravel denying access to guests.

Should phpinsights respect `SuppressWarnings`? I wouldn't want to disable the sniff for the entire file just because of one variable.

**Comment by olivernybroe** [comment]
Try using `@phpcsSuppress SlevomatCodingStandard.Functions.UnusedParameter` and see if that works.

**Comment by ibrahim-mubarak** [comment]
It works perfectly, thanks.
Should we be adding this to the docs?

**Comment by nunomaduro** [comment]
@ibrahim-mubarak You can contribute with that. Here is the guide on how setup the website locally:

```
git clone https://github.com/nunomaduro/phpinsights
cd phpinsights
yarn
yarn run vuepress dev
```
