### ISSUE TITLE
rfc: adds `packaging` column

### ISSUE THREAD

**Issue by nunomaduro** [nunomaduro/phpinsights#270]
Today we have some `insights` in the `Architecture` metrics that are not related to `Architecture` of the application.

This proposal is about creating `chore` or `packaging` column that aggregates all the insights concerning:

- Missing license
- Composer.lock outdated
- etc

**Comment by olivernybroe** [comment]
Hmm I like that idea, I think `chore` is the better name here as that is also kinda following the naming you would use in a commit for a change like that.
