### ISSUE TITLE
Add checkstyle formatter

### ISSUE THREAD

**Issue by Gummibeer** [nunomaduro/phpinsights#274]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| Library version  | latest

ScrutinizerCI supports custom commands if they produce a XML file in checkstyle format.
This would allow to see the phpinsights "errors" in the ScrutinizerCI web UI instead of scrolling through the TravisCI/CircleCI logs.

https://scrutinizer-ci.com/docs/tools/custom-commands/

**Comment by Jibbarth** [comment]
Great news ! It's already implemented => PR #271 

However, it's not released yet. Could you try with `dev-master` version ?

**Comment by Gummibeer** [comment]
Ah, cool. Will Test it tomorrow. Thanks!

**Comment by Gummibeer** [comment]
@Jibbarth it's missing in the console help description.
https://github.com/nunomaduro/phpinsights/blob/9b0418e31641febfc4c9a111d9b91259ab35c38f/src/Application/Console/Definitions/AnalyseDefinition.php#L66-L72

`encoding="UTF-8"` is missing in the opening `<?xml?>` tag. 

It should be noted that the file paths are relative to the path given to `analyse` command and not to the XML file, which is okay/logical because no file is created by command.

I still try to find out what the problem is but ScrutinizerCI seems to have problems parsing the file (no error is listed). My first idea was that every error has it's own file entry - this should be fixed anyway. Now I try to find out if it's something related to escaping. Or if the paths are wrong.

**Comment by dmitryuk** [comment]
@Gummibeer your remarks are fixed in the PR. Please try again )
