### ISSUE TITLE
PHPCodeSniffer ruleset.xml file support

### ISSUE THREAD

**Issue by danilocorrea87** [nunomaduro/phpinsights#276]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| Library version  | latest

## Doubt

I have a personal project that already uses a custom set of PHPCodeSniffer + Slevomat in xml file.
I did some testing with PHPinsigths and found it amazing (Congratulations)

I was wondering if there is any way for PHPInsights to use my custom PHPcs file (xml) as rules, as it keeps alerting me to standard CodeSniffer rules that I'm not using anymore.

Thanks.

<!--
Love PHP Insights? Please consider supporting us via Patreon or OpenCollective:
👉  https://www.patreon.com/nunomaduro
👉  https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=66BYDWAT92N6L
--

**Comment by olivernybroe** [comment]
@danilocorrea87 Hi thank you for using our package.

I am sorry to say, but that is prob. not something we will do, a reason to it can be found in this other issue https://github.com/nunomaduro/phpinsights/issues/163#issuecomment-505330110

**Comment by danilocorrea87** [comment]
Thanks for the feedback @olivernybroe .

I just wanted to take one more doubt, in theory I could import all my custom rules that are in my xml file to phpinsights, right?

Thanks! =)

**Comment by olivernybroe** [comment]
@danilocorrea87 

Well, you can only add the ones which we have categorised into the different matrices. If it is not in one of them it cannot be added. 
However if you have some rules you think we should include, you are more than welcome to PR them in 😄

A feature for adding a custom rule in a specific matrix from a config file would also be really cool to have, but is unfortunately not something we support yet.

**Comment by danilocorrea87** [comment]
Nice, thanks for the feedback @olivernybroe 

I'll take a look at the project, I found it very cool.
