### ISSUE TITLE
Ignore `vendor` directory by default

### ISSUE THREAD

**Issue by mikeerickson** [nunomaduro/phpinsights#277]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| Library version  | v1.8.0

I am running PHP Insights with a few laravel-zero projects and it seems it is NOT ignoring the `vendor` directory as I receive a number of issues related to files in `vendor/src/Illuminate`

<!--
Love PHP Insights? Please consider supporting us via Patreon or OpenCollective:
👉  https://www.patreon.com/nunomaduro
👉  https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=66BYDWAT92N6L
--

**Comment by nunomaduro** [comment]
It's already the case, weird. Can you update to the latest version?

**Comment by mikeerickson** [comment]
I am running `composer require nunomaduro/phpinsights:1.9` but it seems either the reported version is 1.8.0 or composer is not installing the correct version. 



```bash
❯ ./vendor/bin/phpinsights --version
PHP Insights v1.8.0
```
 
composer.json reports

```bash
...
"require": {
    "nunomaduro/phpinsights": "^1.9",
}
...
```

**Comment by olivernybroe** [comment]
@mikeerickson Looks like we forgot to bump the version number in our config file 😥 

Hmm this is weird, it should be skipping it. I just created a new project and there it seems to work.

Could you add steps for reproducing it?

**Comment by mikeerickson** [comment]
@olivernybroe I will install the latest build and give it a whirl.

**Comment by olivernybroe** [comment]
If this is still an issue then I'll reopen this issue 😄
