### ISSUE TITLE
Docker version is not current

### ISSUE THREAD

**Issue by mikeerickson** [nunomaduro/phpinsights#278]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| Library version  | 1.0.0

The docker version is not the latest build.  Looking at the container on docker hub, it seems that a build version of 1.2 exists, but the latest version is 1.0.0

Can you please build a new version of 1.9.0?

https://hub.docker.com/r/nunomaduro/phpinsights/tags

**Comment by nunomaduro** [comment]
Yeah - I would love if someone could take this. I don't use this myself. I don't understand shit about what is happening on travis.

**Comment by ptt-homme** [comment]
Hi,

I would love to help you on this, if you need ping me :)!

Le jeu. 26 sept. 2019 à 10:04, Nuno Maduro <notifications@github.com> a
écrit :

**Comment by mikeerickson** [comment]
@nunomaduro I can assist, I use docker quite a bit personally.  Or, if @ptt-homme has more immediate time to contribute, lets do it!  

@nunomaduro I assume you have the credentials for your account on http://hub.docker.com

**Comment by danilocorrea87** [comment]
I think this issue can be closed @Jibbarth = )
