### ISSUE TITLE
Add custom rules to a matrix in config

### ISSUE THREAD

**Issue by olivernybroe** [nunomaduro/phpinsights#284]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes

This feature is to allow adding a custom rule inside a matrix from the config file.

Some users have closed source phpcs rules which they want to use together with our package or they simply wanna use a rule we do not acknowledge.
For allowing this, I think our config file should have the possibility for adding new classes to a matrix, directly from the config file.

**Comment by Jibbarth** [comment]
@olivernybroe Could you provide an example of what you think ? I'm not sure to understand :thinking:

**Comment by olivernybroe** [comment]
Sure, 

So let's say I have a custom sniff in my own project and I want to use that sniff with phpinsights. 

Right now I cannot do this. 

My suggestion is then that I can add this custom sniff to the config file. However the problem here is that we do not know what type of insight this is. So when I add the custom sniff I should also have the possibility to specify which type of insight it is.

Does it makes sense, else I can come with a more specific scenario :)

**Comment by Jibbarth** [comment]
Hmm :thinking: 

When you speak about sniff, is that a Sniff that use PhpCodeSniffer for example ?

If your custom sniff implement Sniff or Insight interface, you can [add it](https://phpinsights.com/insights/#add-insights) into phpinsights.


For example, if I require [this package](https://github.com/sirbrillig/phpcs-variable-analysis), I can add it into configuration file like this : 

```
// phpinsights.php
    'add' => [
        \NunoMaduro\PhpInsights\Domain\Metrics\Code\Code::class => [
            \VariableAnalysis\Sniffs\CodeAnalysis\VariableAnalysisSniff::class,
        ],
    ],
```

Or maybe I still not understand :sweat_smile:

**Comment by olivernybroe** [comment]
Oh yeah, haha my bad :D 

I totally forgot that we had that feature 😂

Thanks
