### ISSUE TITLE
exclude's in config file is ignored

### ISSUE THREAD

**Issue by akosglue** [nunomaduro/phpinsights#286]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| Library version  | dev-master , "reference": "8a60fbc1b847b81be85ca37e7632badcbf4bd7a4"

<img width="869" alt="insights" src="https://user-images.githubusercontent.com/17706334/66555462-fe6c5600-eb4e-11e9-85bf-065c1dcd26ed.png">

As seen in the screenshot, channels, console, Kernel is analyzed, however this was not the case a few days ago, before I composer updated.

<!--
Love PHP Insights? Please consider supporting us via Patreon or OpenCollective:
👉  https://www.patreon.com/nunomaduro
👉  https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=66BYDWAT92N6L
--

**Comment by akosglue** [comment]
I execute this: `php artisan insights -v`
I have seen that refactoring commit related to configurations, I thought as well that it is related.

**Comment by akosglue** [comment]
I have just tried this one as well: `./vendor/bin/phpinsights -v`
But it is the same, excluded files and removed sniffs are ignored.

**Comment by olivernybroe** [comment]
@akosglue Try running `./vendor/bin/phpinsights` where you specify the config file as a parameter instead and see if that works.

**Comment by akosglue** [comment]
Well, that is indeed correct:
`./vendor/bin/phpinsights --config-path="config/insights.php"`
53 files analyzed.

without that option for the config: 
`./vendor/bin/phpinsights -v`
72 files.


I have also installed a brand new laravel app with insights.
It seems to be okay there, even without specifying the config route.

So, most likely, it has something to do with my setup.

**Comment by akosglue** [comment]
it is the content of the config:
`<?php

declare(strict_types=1);

use NunoMaduro\PhpInsights\Domain\Insights\Composer\ComposerMustBeValid;
use NunoMaduro\PhpInsights\Domain\Insights\ForbiddenDefineFunctions;
use NunoMaduro\PhpInsights\Domain\Insights\ForbiddenNormalClasses;
use NunoMaduro\PhpInsights\Domain\Insights\ForbiddenPrivateMethods;
use NunoMaduro\PhpInsights\Domain\Insights\ForbiddenTraits;
use NunoMaduro\PhpInsights\Domain\Metrics\Architecture\Classes;
use SlevomatCodingStandard\Sniffs\Namespaces\AlphabeticallySortedUsesSniff;
use SlevomatCodingStandard\Sniffs\TypeHints\DeclareStrictTypesSniff;
use SlevomatCodingStandard\Sniffs\TypeHints\DisallowMixedTypeHintSniff;
use SlevomatCodingStandard\Sniffs\TypeHints\TypeHintDeclarationSniff;

return [

    /*
    |--------------------------------------------------------------------------
    | Default Preset
    |--------------------------------------------------------------------------
    |
    | This option controls the default preset that will be used by PHP Insights
    | to make your code reliable, simple, and clean. However, you can always
    | adjust the `Metrics` and `Insights` below in this configuration file.
    |
    | Supported: "default", "laravel", "symfony"
    |
    */

    'preset' => 'laravel',

    /*
    |--------------------------------------------------------------------------
    | Configuration
    |--------------------------------------------------------------------------
    |
    | Here you may adjust all the various `Insights` that will be used by PHP
    | Insights. You can either add, remove or configure `Insights`. Keep in
    | mind that all added `Insights` must belong to a specific `Metric`.
    |
    */

    'add' => [
        Classes::class => [
        ],
    ],

    'remove' => [
        AlphabeticallySortedUsesSniff::class,
        DeclareStrictTypesSniff::class,
        DisallowMixedTypeHintSniff::class,
        ForbiddenDefineFunctions::class,
        ForbiddenNormalClasses::class,
        ForbiddenTraits::class,
        TypeHintDeclarationSniff::class,
        ComposerMustBeValid::class,
    ],

    'config' => [
        ForbiddenPrivateMethods::class => [
            'title' => 'The usage of private methods is not idiomatic in Laravel.',
        ],
    ],

    'exclude' => [
        'app/Exceptions/Handler.php',

        'app/Providers/EventServiceProvider.php',
        'app/Providers/AppServiceProvider.php',
        'app/Providers/AuthServiceProvider.php',
        'app/Providers/RouteServiceProvider.php',
        'app/Providers/BroadcastServiceProvider.php',

        'app/Http/Middleware/CheckForMaintenanceMode.php',
        'app/Http/Middleware/Authenticate.php',
        'app/Http/Middleware/EncryptCookies.php',
        'app/Http/Middleware/RedirectIfAuthenticated.php',
        'app/Http/Middleware/VerifyCsrfToken.php',
        'app/Http/Middleware/TrustProxies.php',

        'app/Http/Controllers/Auth/VerificationController.php',
        'app/Http/Controllers/Auth/RegisterController.php',
        'app/Http/Controllers/Controller.php',

        'app/Http/Kernel.php',

        'app/Console/Kernel.php',

        'routes/channels.php',
        'routes/console.php',
    ],
];
`

**Comment by olivernybroe** [comment]
Thanks for testing it out. 

Hmm so you are saying something in your config is causing it to not work, but when you specify the config file as a parameter it works?

**Comment by akosglue** [comment]
Yes, exactly.

**Comment by olivernybroe** [comment]
@akosglue Not really sure why it isn't working with your config file specifically tbh.

**Comment by akosglue** [comment]
The thing is that it works with --config-path and it works with a brand new installation.
I will investigate a little bit further, if anyone stumbles upon this problem.

**Comment by akosglue** [comment]
Well, I reproduced the issue. I provide the steps below:

`composer create-project --prefer-dist laravel/laravel blog ^6`

`cd blog`

`composer require nunomaduro/phpinsights dev-master`

`php artisan vendor:publish --provider="NunoMaduro\PhpInsights\Application\Adapters\Laravel\InsightsServiceProvider"`

`php artisan insights`
(27 files analyzed)

`php artisan insights --config-path="config/insights.php"` 
(27 files analyzed)

So far so good. Now I edit config/insights.php: I add 
`    'exclude' => [
        'routes/channels.php',
        'routes/console.php',
    ],`

`php artisan insights`
(27 files analyzed --> NOT ok, I expect 25 files)

`php artisan insights --config-path="config/insights.php"`
(25 files analyzed, as I expect)

So, I still think that the config/insights.php file is ignored when I don't specify the config-path.

**Comment by Jibbarth** [comment]
Thanks you @akosglue for this detailled issue :+1: I'll try to reproduce and fix it.

**Comment by akosglue** [comment]
Now it works as expected, thank you for the fix ;-)

**Comment by olivernybroe** [comment]
Thanks for reporting it and detailed description :)

**Comment by lupinitylabs** [comment]
I still encounter this exact same problem on version 2.2.0. 
When putting an insights.php in the config dir of the app, it is ignored unless I invoke phpinsights using
```
vendor/bin/phpinsights --config-path="config/insights.php"
```

**Comment by AlexMartinFR** [comment]
I also have the same problem on a fresh project.

Can I do anything to help you debug this issue?

**Comment by akosglue** [comment]
I guess you can reproduce it with these steps?
https://github.com/nunomaduro/phpinsights/issues/286#issuecomment-540749295

**Comment by AlexMartinFR** [comment]
I got it.

I was running PHP Insights with the following command:

`./vendor/bin/phpinsights`
_(29 files analyzed)_

When doing so, the config file is ignored.

However, when we run it via artisan, the config file is properly taken into account:

`php artisan insights`
(28 files analyzed)


I can see that we made the same mistake, @lupinitylabs 🙃
