### ISSUE TITLE
PHP Insights takes about 2 minutes to complete the analysis

### ISSUE THREAD

**Issue by simobern** [nunomaduro/phpinsights#289]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| Library version  | 1.9

Running `php artisan insight` on Laravel 5.8 app takes about 2 minutes to complete the analysis for 166 files.

Time:
real    1m52.239s
user    0m18.047s
sys     0m21.774s

**Comment by akosglue** [comment]
Just a side note to this: I have also experienced that recently the analysis became slower than before. However, I still can go on with it.

**Comment by olivernybroe** [comment]
As more insights has been added, and now also support for phpcs fixer, the runtime is longer :) 

However could you check that only the right files which you want analysed is running?

**Comment by simobern** [comment]
> As more insights has been added, and now also support for phpcs fixer, the runtime is longer :)
> 
> However could you check that only the right files which you want analysed is running?

Yes, I confirm that.

**Comment by olivernybroe** [comment]
@simobern Thanks. 

Hmm I think it would be good for somebody to look into the runtime and see what exactly is taking a long time, we might be able to do some clever stuff to reduce it. 

Another solution might be to add a parameter to only run it on files with changes as you prob. often don't need to run it on all files, but only the files you changed.

**Comment by olivernybroe** [comment]
Both me and @Jibbarth have added some PR's recently which improves the speed and reduces the memory load. It is currently in master branch, hope this helps on your speed problems. 

We already have issue #354 about processing only changed files and #390 for adding parallelization which also should speed this up.

If somebody has other ideas to improve the speed, then please open an issue about that 👍
