### ISSUE TITLE
Disable sniffs locally

### ISSUE THREAD

**Issue by JacobDB** [nunomaduro/phpinsights#290]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| Library version  | 1.9

In some cases, I've run in to situations where I want to disable a sniff for a specific case, but not globally. For example, when writing WordPress filter, sometimes some additional parameters are required for the filter to function, even if those parameters are unused. It'd be great to be able to locally exclude a specific function from a particular sniff.

**Comment by olivernybroe** [comment]
You can disable a specific sniff for a whole file

**Comment by olivernybroe** [comment]
Some sniffs can also be disabled with a doc comment #267.

If this does not solve your problems, please tell us what exactly you are looking for and we can reopen the issue.

**Comment by d8vjork** [comment]
@olivernybroe Sorry for replying here, but how about disabling a specific sniff for a path/directory or a pattern? This is an example of what I'm trying on my Laravel (which makes more sense to be under the preset rather than setup this on each of my Laravel based projects):

```php
// ...

'config' => [
        \ObjectCalisthenics\Sniffs\Classes\ForbiddenPublicPropertySniff::class => [
            'exclude' => [
                'app/Listeners/*',
                'app/Events/*',
                'app/Mail/*',
            ],
        ],
        \SlevomatCodingStandard\Sniffs\Functions\UnusedParameterSniff::class => [
            'exclude' => [
                '*Policy.php',
            ],
        ],

// ...
```
