### ISSUE TITLE
bug: changes indicator with empty statement

### ISSUE THREAD

**Issue by nunomaduro** [nunomaduro/phpinsights#295]
Just noticed the following issue while working with PHP Insights. @Jibbarth do you know what is it?

<img width="524" alt="Screenshot 2019-10-20 at 15 15 48" src="https://user-images.githubusercontent.com/5457236/67160049-b1596280-f34c-11e9-814f-948aa1d5b329.png">

**Comment by olivernybroe** [comment]
Pretty sure it's because it just want you to remove the empty line. 
However it does look weird when it's an empty line it want you to change only.

**Comment by Jibbarth** [comment]
:thinking: Maybe we should add a dictionnary of messages for Fixer for some of them. Or increase the diff size. WDYT ?

**Comment by Jibbarth** [comment]
Here it's how look when we increase diff size. 
![image](https://user-images.githubusercontent.com/3168281/67162429-2edc9d00-f364-11e9-888f-3b895cffc99d.png)

@nunomaduro Is it better ?

**Comment by olivernybroe** [comment]
I think this is better when talking about these simple line deletes, so users can actually see where to do it. 

How does it look with all other diffs then?

**Comment by JustSteveKing** [comment]
No movement for a couple of years, closing with a view to look into if it becomes an issue moving forward
