### ISSUE TITLE
[Question] What is the source for saying private methods in Laravel aren't idiomatic?

### ISSUE THREAD

**Issue by yakryder** [nunomaduro/phpinsights#298]
On config generation, this was put in my `phpinsights` config:

```php
'config' => [
        ForbiddenPrivateMethods::class => [
            'title' => 'The usage of private methods is not idiomatic in Laravel.',
        ],
]
```

A cursory google was unable to turn up a source for private methods not being idiomatic, and on the surface -- and admittedly as a php newcomer -- it seems strange to me.

**Comment by JustSteveKing** [comment]
This is something that can be improved in wording and documentation
