### ISSUE TITLE
ForbiddenFunctionsSniff [Duplicate]

### ISSUE THREAD

**Issue by ghost** [nunomaduro/phpinsights#299]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| Library version  | 1.9.0

Just discovered that the ForbiddenFunctionsSniff is available in Style and Code.

**Comment by nunomaduro** [comment]
Can you handle it? You just need to remove the respective insights from one section in the docs and the source code itself.

**Comment by nunomaduro** [comment]
Here is an example: https://github.com/nunomaduro/phpinsights/pull/296/files.

**Comment by FFDevelopment** [comment]
@nunomaduro In which part should it be removed? Style or Code?

**Comment by nunomaduro** [comment]
What do you think? 👍

**Comment by FFDevelopment** [comment]
I prefer to remove it in Style.

**Comment by nunomaduro** [comment]
Correct! 👍

**Comment by Jibbarth** [comment]
Fixed in 1.10 :+1:
