### ISSUE TITLE
False positive: Method does not need documentation comment

### ISSUE THREAD

**Issue by enumag** [nunomaduro/phpinsights#302]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| Library version  | 1.9.0

I got this report from PHPInsight:

```
• [Code] Type hint declaration:
  src/ReadModel/Internal/Builder/MonthlyBalanceMovements.php:110: Method \App\ReadModel\Internal\Builder\MonthlyBalanceMovements::getAllocatedPaymentsTotal() does not need documentation comment
```

The method in question looks like this:

```
	/**
	 * @deprecated
	 */
	public function getAllocatedPaymentsTotal(): Money
	{
		// ...
	}
```

The `@deprecated` annotation is necessary here in order to not let my team use this method in any new code. This case should not be reported.

**Comment by olivernybroe** [comment]
One way to fix this is by adding the following setting to that sniff in your config file 
`allAnnotationsAreUseful`.
https://github.com/slevomat/coding-standard/#slevomatcodingstandardtypehintstypehintdeclaration-

**Comment by JustSteveKing** [comment]
Closing for now
