### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by dmitryuk** [nunomaduro/phpinsights#305]
Hello, guys do you plan to rollout a new release? Where are interesting features which we are waiting so much and too long )
Thank you

**Comment by nunomaduro** [comment]
I am going to review this weekend and release it. ✨

**Comment by dmitryuk** [comment]
No release yet (

**Comment by nunomaduro** [comment]
cc @Jibbarth Do you think can you lead this? You have done most of the work in this release.

**Comment by Jibbarth** [comment]
Sure, I can do it tonight/tomorrow :wink:

**Comment by Jibbarth** [comment]
Done :tada:
