### ISSUE TITLE
UnusedVariableSniff reports false positives

### ISSUE THREAD

**Issue by enumag** [nunomaduro/phpinsights#307]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| Library version  | 1.9.0

Ofc I know this sniff isn't yours but comes from https://github.com/slevomat/coding-standard. But I read somewhere that you don't want phpinsights to report false positives in which case you might want to consider disabling this sniff until it's fixed.

The problem is that the sniff reports `$value` as unused in this code:

```php
function (iterable $items): void {
	foreach ($items as $key => $value) {
		echo $key;
	}
}
```

Which is technically correct because the variable is indeed unused. However declaration of the variable can't be avoided since we need the `$key` variable and there is no way to only declare `$key`.

**Comment by nunomaduro** [comment]
Can you try :

```
function (iterable $items): void {
	foreach ($items as $key => $_) {
		echo $key;
	}
}

```

**Comment by enumag** [comment]
Ah, the sniff actually is "fixed", but the fix is disabled by default. You need to set [this](https://github.com/slevomat/coding-standard/blob/5e698edfe9923b1fa797b407f83d211a406e1957/SlevomatCodingStandard/Sniffs/Variables/UnusedVariableSniff.php#L64) to `true`. I'd send a PR but I'm not quite sure where the default sniffs are configured.

No, `$_` does not work.

**Comment by nunomaduro** [comment]
Yeah - send a pull request plz.

**Comment by enumag** [comment]
Can you tell me where to configure this? I'm new to phpinsights so I'm not sure.

**Comment by nunomaduro** [comment]
Here: https://github.com/nunomaduro/phpinsights/blob/master/src/Application/DefaultPreset.php.

**Comment by nunomaduro** [comment]
Thanks.
