### ISSUE TITLE
Dependency version mismatch for Laravel 5.8.x - symfony/finder

### ISSUE THREAD

**Issue by brunocfalcao** [nunomaduro/phpinsights#31]
Hi Nuno,

Laravel 5.8.x uses the version ^4.2 of symfony/finder.

But this package needs the 4.3.x-dev, giving the following requirements error:

![image](https://user-images.githubusercontent.com/34269950/57416994-eccefd00-7202-11e9-947c-a0770564c956.png)

Is there a reason to have this 4.3.x-dev version? If not, I would propose to downgrade to 4.2.x.

Thanks, and great work!
Bruno

**Comment by nunomaduro** [comment]
That's the reason why this package is not released yet. 👌🏻

**Comment by brunocfalcao** [comment]
Sure, I was testing it because it says on the readme how to use it under the Laravel scope.

No prob, will wait then 👌🏻

**Comment by nunomaduro** [comment]
@brunocfalcao Don't hesitate to contribute buddy. We are near the launch.

**Comment by szepeviktor** [comment]
🚀

**Comment by nunomaduro** [comment]
@brunocfalcao Should be good now, decided to drop the dependency at the moment.
