### ISSUE TITLE
Argument 1 passed to NunoMaduro\PhpInsights\Domain\Insights\Insight::shouldSkipFile() must be of the type string, integer given

### ISSUE THREAD

**Issue by dominikzogg** [nunomaduro/phpinsights#315]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| Library version  | v1.10.0

Fatal error: Uncaught TypeError: Argument 1 passed to NunoMaduro\PhpInsights\Domain\Insights\Insight::shouldSkipFile() must be of the type string, integer given, called in /home/travis/build/chubbyphp/chubbyphp-doctrine-db-service-provider/vendor/nunomaduro/phpinsights/src/Domain/Insights/Insight.php on line 73 and defined in /home/travis/build/chubbyphp/chubbyphp-doctrine-db-service-provider/vendor/nunomaduro/phpinsights/src/Domain/Insights/Insight.php:55

https://travis-ci.org/chubbyphp/chubbyphp-doctrine-db-service-provider/jobs/612943256?utm_medium=notification&utm_source=email

I run this tests on a daily base, so the config / src did no change, a vendor could.

**Comment by Jibbarth** [comment]
Thank you for reporting this @dominikzogg  :+1:  I created a PR to fix it

**Comment by Jibbarth** [comment]
@dominikzogg Could you retry with 1.10.2 version ? Thanks

**Comment by sudkumar** [comment]
@Jibbarth Thank you for the fix. I am using this inside a Laravel bootstrapped project. I tried the release `v1.10.2` but have similar/different 😕  issue

```bash
$ php artisan insights

Symfony\Component\Debug\Exception\FatalThrowableError:

Argument 1 passed to NunoMaduro\PhpInsights\Domain\Configuration::resolveIde()
must be of the type string, null given, called in
[workspace]/vendor/nunomaduro/phpinsights/src/Domain/Configuration.php on line 202

at [workspace]/vendor/nunomaduro/phpinsights/src/Domain/Configuration.php:252
    248|             }
    249|             return true;
    250|         };
    251|     }
  > 252|     private function resolveIde(string $ide): FileLinkFormatterContract
    253|     {
    254|         $links = [
    255|             =>
    256|             =>

```

<details>

<summary>
Exception trace:
</summary>

```bash
  1   NunoMaduro\PhpInsights\Domain\Configuration::resolveIde()
      [workspace]/vendor/nunomaduro/phpinsights/src/Domain/Configuration.php:202

  2   NunoMaduro\PhpInsights\Domain\Configuration::resolveConfig()
      [workspace]/vendor/nunomaduro/phpinsights/src/Domain/Configuration.php:90

  3   NunoMaduro\PhpInsights\Domain\Configuration::__construct()
      [workspace]/vendor/nunomaduro/phpinsights/src/Application/ConfigResolver.php:73

  4   NunoMaduro\PhpInsights\Application\ConfigResolver::resolve("[workspace]")
      [workspace]/vendor/nunomaduro/phpinsights/src/Application/Adapters/Laravel/Commands/InsightsCommand.php:38

  5   NunoMaduro\PhpInsights\Application\Adapters\Laravel\Commands\InsightsCommand::handle()
      [workspace]/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:32

```
</details>


Please let me know if you need any further details.

```
PHP 7.2.22
Laravel 6.5.0
OS Mac OS 10.14.6
```

**Comment by Jibbarth** [comment]
Hi @sudkumar ! Could you please open a new issue ? And provide your configuration file ? Thanks :+1:

**Comment by sudkumar** [comment]
Alright. I thought it was similar. Sorry. I will open a new one.
