### ISSUE TITLE
Config reading and error handling

### ISSUE THREAD

**Issue by kyobul** [nunomaduro/phpinsights#321]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| Library version  | 1.10.3

Laravel 6.5, Laragon local server on Windows 10, command line with Cmder. PHP is 7.3.11

1st problem : When using` .\vendor\bin\phpinsights.bat` command : all directories and files in _config/insights.php exclude[]_ are ignored (which is unexpected). When errors are encountered in analysis : throws detailed php error wit stack trace (which is ok and expected) .

2nd problem : when using `php artisan insights` command :  all directories and files in _config/insights.php exclude[]_ are taken in account and skipped (which is expected). When php errors are encountered, detailed error log is thrown except on some files when it will pause and hang forever (must then close terminal) if some specific syntax error is encountered, like for example `class MyClass extends Illuminate\Database\Eloquent\Model; {` (with the semi-colon as typo).

3d problem : if Laravel Telescope is enabled it replaces the normal debug_backtrace log and throws Telescope error messages, which are all the same, starting with : `file_get_contents(): Filename cannot be empty`

<!--
Love PHP Insights? Please consider supporting us via Patreon or OpenCollective:
👉  https://www.patreon.com/nunomaduro
👉  https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=66BYDWAT92N6L
--

**Comment by olivernybroe** [comment]
Thanks for reporting the issues! 

1. This is actually not a bug. Phpinsight can be run without Laravel, so if you run the .bat file directly, you will have to pass in the path to the config file when running it through the .bat file.

2. Good catch, have not experienced this myself. Normally it throws a parse error, however in that specific scenario it just hangs. I have opened an issue with it #322.

3. Hmm interesting, seems like we either have to disable telescope when running with `php artisan` or check the type of the exception and if it's a telescope exception then get the previous exception.

**Comment by JustSteveKing** [comment]
Closing for now, stale issue
