### ISSUE TITLE
Hangs on some invalid php code

### ISSUE THREAD

**Issue by olivernybroe** [nunomaduro/phpinsights#322]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| Library version  | master

When running phpinsights on the following code snippet, it hangs.

```
<?php

class MyClass extends Illuminate\Database\Eloquent\Model; {
```

Normally in other scenarios it throws a parse error exception, however in this scenario
it just hangs up the terminal. 

Reported in #321, but separated to its own issue.

**Comment by 50bhan** [comment]
@olivernybroe I looked into this bug. It seems the "slevomat coding standard package" will throw a fatal error and because of using "@" for suppressing errors, no errors will thrown and it just hung up.

**Comment by olivernybroe** [comment]
@50bhan Thanks for looking into this.

Seems like the solution of suppressing errors might not be viable enough then. The reason the `@` notation was used, is because when a php file it is trying to evaluate has for example an unclosed php comment, it gives warning messages in the terminal. However we don't want those, we want an insight telling us this instead.
