### ISSUE TITLE
phpinsights by composer

### ISSUE THREAD

**Issue by ghost** [nunomaduro/phpinsights#329]
Hi,

is there a reason why phpinsights is currently not being delivered via the composer update function?

Since version 1.10.0 I have the feeling that I always have to require a new version by `composer require nunomaduro/phpinsights:(version) --dev`.

**Comment by nunomaduro** [comment]
Can you show me your `composer.json` file?

**Comment by olivernybroe** [comment]
Haven't been able to reproduce this. 
If this keeps happening, then please provide some details like the `composer.json` and we can reopen this issue.
