### ISSUE TITLE
Composer/composer required version clashes with sf 5

### ISSUE THREAD

**Issue by fredericbarthelet** [nunomaduro/phpinsights#331]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| Library version  | 1.11.1

Hi,

PhpInsights current version requires `"composer/composer": "^1.7"`
Composer versions 1.7 to 1.9.1 (latest on v1 master) requires : 
```
"symfony/console": "^2.7 || ^3.0 || ^4.0",
"symfony/filesystem": "^2.7 || ^3.0 || ^4.0",
"symfony/finder": "^2.7 || ^3.0 || ^4.0",
"symfony/process": "^2.7 || ^3.0 || ^4.0"
```

This prevents SF 5 installation.

Composer version 2.x release now supports symfony v5 versions for all before mentioned package. I would therefor recommend support for `"composer/composer": "^2.0"`.

Will produce a PR accordingly if you are OK with the change

**Comment by nunomaduro** [comment]
@fredericbarthelet Yes - you can work in a pull request for this. Thanks!

**Comment by nanawel** [comment]
Hi, is there an estimated date for this PR?

**Comment by nunomaduro** [comment]
@nanawel what do you mean?

**Comment by nanawel** [comment]
Sorry, I was wondering when the incompatibility with sf5 packages would be resolved. I thought I couldn't install the latest version of phpinsights because of this incompatiblity, but the error I was having turned out to be because of another dependency issue.
You can ignore my question :) Thanks

**Comment by Jibbarth** [comment]
As composer:v1.10.0 is [released](https://github.com/composer/composer/releases/tag/1.10.0), the compatibility between SF5 and PHPInsights is now ok on dev-master :raised_hands:
