### ISSUE TITLE
Fails on empty namespace

### ISSUE THREAD

**Issue by chrisgraham** [nunomaduro/phpinsights#333]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| Library version  | 1.11.1

This fails:

```
<?php

namespace {
}
```

I think it's because you expect a name, e.g.

```
<?php

namespace foo {
}
```

Fix by replacing:
```
                    $namespace = $this->getNamespaceName($tokens, $i);
```
with:
```
                    $namespace = $this->getNamespaceName($tokens, $i);
                    if ($namespace !== false) {
                        $collector->addNamespace($namespace);
                    }
```

**Comment by olivernybroe** [comment]
Thank you for analysing this error and providing a fix for it. 
You are more than welcome to submit a PR with it if you are up for it.

**Comment by chrisgraham** [comment]
I was just testing different lints and felt an obligation to report any issue(s) found - but I don't have time to invest in actively pushing code to projects, sorry.

**Comment by olivernybroe** [comment]
@chrisgraham No worries. Thanks for reporting. 
Just wanted to give the opportunity now that you also provided a fix for it 😃
