### ISSUE TITLE
Does not work with a `namespace()` method name

### ISSUE THREAD

**Issue by aocneanu** [nunomaduro/phpinsights#334]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| Library version  | 1.11.1

Hello,

If I use insights on a class that has a method called `namespace()` the following error is thrown

```
Symfony\Component\Debug\Exception\FatalThrowableError  : Argument 1 passed to NunoMaduro\PhpInsights\Domain\Collector::addNamespace() must be of the type string, bool given, called in /Users/adi/code/enso/vendor/nunomaduro/phpinsights/src/Domain/Analyser.php on line 166
```

Thank you for this awesome package!

<!--
Love PHP Insights? Please consider supporting us via Patreon or OpenCollective:
👉  https://www.patreon.com/nunomaduro
👉  https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=66BYDWAT92N6L
--

**Comment by 50bhan** [comment]
@olivernybroe I think this issue can be closed, right?
