### ISSUE TITLE
[Proposal] Color for file:line when no FileLinkFormatter is set

### ISSUE THREAD

**Issue by sierrafayad** [nunomaduro/phpinsights#336]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes/no
| Library version  | 1.11.1

I was using insights without setting an IDE (even if set, it doesn't work on Windows 10 anyway, I'm using cmder) and noticed that it would be nice to have the file:line clearly differentiated from rest of the line 

Default color from `formatFileLine`
![image](https://user-images.githubusercontent.com/4095810/70820311-54a38280-1da6-11ea-8687-006555f2bd15.png)

Trying some variations.
![image](https://user-images.githubusercontent.com/4095810/70820512-d4315180-1da6-11ea-9c0e-16e0fd81e362.png)
![image](https://user-images.githubusercontent.com/4095810/70821005-02636100-1da8-11ea-99a3-5d5b0c91fb5f.png)
![image](https://user-images.githubusercontent.com/4095810/70821064-24f57a00-1da8-11ea-887d-ea6827867b4f.png)

![image](https://user-images.githubusercontent.com/4095810/70821454-1fe4fa80-1da9-11ea-856a-d77ddd0508ef.png)

If this is something desirable, I would like to send a PR to add it.

Also we should pick a color for it 😅

<!--
Love PHP Insights? Please consider supporting us via Patreon or OpenCollective:
👉  https://www.patreon.com/nunomaduro
👉  https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=66BYDWAT92N6L
--

**Comment by olivernybroe** [comment]
I like the idea a lot :smiley: 
What about using different colors for each insight category? This way you can also quickly see if you scrolled to a new category of issues. 

@caneco any great ideas for colors? :pray:

**Comment by sierrafayad** [comment]
We would need to modify the `formatFileLine` signature to get the current category and add a default argument, maybe something like this,  
`formatFileLine(Details $detail, string $directory, string $category = '')` 

I'm not quite sure where should the getter for the category based color should go, or if it can just be a function inside `Application\Console\Formatters\Console.php` something like
`getCategoryColor(string $category)`
```php
if (
    $this->supportHyperLinks &&
    $formattedLink !== '' &&
    $detailString !== ''
) {
    ...
} else {
    $color = 'cyan';  //CategoryColor getter would go here.
    $detailString = sprintf(
        '<fg=%s>%s</>',
        $color,
        $detailString
    );
}
```
This should only set a color if the FileLinkFormatter is set to the NullFileLinkFormatter or the result of `format(...)` returns and empty string

**Comment by olivernybroe** [comment]
@sierrafayad Sounds great. 
Yep it should just be a method inside `Console` as the coloring right now is only something we use for console output. 

Why don't we wanna change the color if there is a `FileLinkFormatter`?

**Comment by sierrafayad** [comment]
Good question! I'm not sure if the link would override the color or if coloring it would mess with the link.
I don't have a system to test that at the moment but I will set up something later today and test that.

**Comment by sierrafayad** [comment]
Sorry for the delay, coloring a link doesn't seem to affect the behavior.

**Comment by olivernybroe** [comment]
@sierrafayad Totally!
Sorry for forgetting to follow up on this. 😄

**Comment by sierrafayad** [comment]
Closing, as it was Merged 😃
