### ISSUE TITLE
Is DisallowArrayTypeHintSyntaxSniff still valid?

### ISSUE THREAD

**Issue by acurrieclark** [nunomaduro/phpinsights#338]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| Library version  | 1.11.1

In the latest [PSR-5 fig standards for PHPDoc](https://github.com/php-fig/fig-standards/blob/master/proposed/phpdoc.md#abnf), the format for array typing has been updated to use the:

```php
/**
* @var int[]
*/
```
rather than the
```php
/**
* @var array<int>
*/
```
format.

The former is also the preferred format for the PhpStorm IDE, not that you should be swayed by a single IDE.

I realise that PSR-5 is still in draft, but is it worth perhaps rethinking the `SlevomatCodingStandard\Sniffs\TypeHints\DisallowArrayTypeHintSyntaxSniff` sniff?

**Comment by nunomaduro** [comment]
For me both are wrong, that should be:

```
/**
* @var array<int, int>
*/
```

cc @Jibbarth @olivernybroe

**Comment by acurrieclark** [comment]
Well, there is a lesson learned. I should have read the PSR-5 draft more clearly.

Thanks for the feedback.
