### ISSUE TITLE
PHP 7.4 support && slevomat/coding-standard

### ISSUE THREAD

**Issue by shandyDev** [nunomaduro/phpinsights#340]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| Library version  | latest

Hi,
How about update dependencies slevomat/coding-standard to 6.0 https://github.com/slevomat/coding-standard/releases ?
It have only 2 BC sniffs.

**Comment by olivernybroe** [comment]
Sounds like a good idea. You are welcome to create a PR 👍 

Doing this change, we would prob. have to do a BC ourself, as users could have custom stuff for those sniffs.

**Comment by schrapel** [comment]
Just noticed this error when trying to install `symplify/easy-coding-standard`

**Comment by nunomaduro** [comment]
What error?

**Comment by schrapel** [comment]
@nunomaduro Sorry for not being clear. Just composer install conflicts not an actual error with either packages. The package I mentioned above already requires ^6.0

https://github.com/Symplify/EasyCodingStandard/blob/master/composer.json#L26

**Comment by nunomaduro** [comment]
The version `v1.12` is out, and fixes this issue.
