### ISSUE TITLE
Proposal: disable output of progress bar via CLI option

### ISSUE THREAD

**Issue by axit-joost** [nunomaduro/phpinsights#345]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| Library version  | 1.11.1

I'm trying to run phpinsights in a pre-commit hook, using husky and lint-staged. While that does work, the Progress Bar is appended to the console output:

```sh
 +67 issues omitted

[ERROR] The code quality score is too low

[ERROR] The complexity score is too low

[ERROR] The architecture score is too low

[ERROR] The style score is too low


✨ See something that needs to be improved? Create an issue or send us a pull request: https://github.com/nunomaduro/phpinsights
    0/406 [░░░░░░░░░░░░░░░░░░░░░░░░░░░░]   0%

  4/406 [░░░░░░░░░░░░░░░░░░░░░░░░░░░░]   0%

  8/406 [░░░░░░░░░░░░░░░░░░░░░░░░░░░░]   1%

 12/406 [░░░░░░░░░░░░░░░░░░░░░░░░░░░░]   2%

 16/406 [▓░░░░░░░░░░░░░░░░░░░░░░░░░░░]   3%

 20/406 [▓░░░░░░░░░░░░░░░░░░░░░░░░░░░]   4%

 24/406 [▓░░░░░░░░░░░░░░░░░░░░░░░░░░░]   5%

 28/406 [▓░░░░░░░░░░░░░░░░░░░░░░░░░░░]   6%

 32/406 [▓▓░░░░░░░░░░░░░░░░░░░░░░░░░░]   7%

 35/406 [▓▓░░░░░░░░░░░░░░░░░░░░░░░░░░]   8%

 39/406 [▓▓░░░░░░░░░░░░░░░░░░░░░░░░░░]   9%

 41/406 [▓▓░░░░░░░░░░░░░░░░░░░░░░░░░░]  10%
```
I would like to propose the addition of a command line argument to disable the progress bar. Alternatively, I would propose the progress bar not being shown whenever the `-n` argument is passed.

I believe this will also be helpful in other CI or pipeline scenarios.

<!--
Love PHP Insights? Please consider supporting us via Patreon or OpenCollective:
👉  https://www.patreon.com/nunomaduro
👉  https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=66BYDWAT92N6L
--

**Comment by olivernybroe** [comment]
Hi, thanks for using the tool! 
What you a proposing is actually already possible :smile: 
We use the stderr for progress bar and other unrelated information for the result, so simply by only looking at stdout you will get the results alone. 

Is that something you can use with your setup? I do not use those tools myself.
