### ISSUE TITLE
Build failed cause its done with PHP 7.4

### ISSUE THREAD

**Issue by dominikzogg** [nunomaduro/phpinsights#346]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| Library version  | 1.12.0

I test my libraries with PHP 7.2, 7.3 and 7.4. The start failing cause `SlevomatCodingStandard\Sniffs\TypeHints\PropertyTypeHintSnif` was added by default. Would be cool if this sniff would be disabled by default or at least if the min version within composer.json is less than 7.4.

See:
- https://travis-ci.org/chubbyphp/chubbyphp-static-file/jobs/644008580?utm_medium=notification&utm_source=email
- https://travis-ci.org/chubbyphp/chubbyphp-config/jobs/644010256?utm_medium=notification&utm_source=email

**Comment by nunomaduro** [comment]
@dominikzogg maybe you can add a if condition here? https://github.com/nunomaduro/phpinsights/blob/9a04c09c97364f127a5350e08410c6819eb1283c/src/Domain/Metrics/Code/Comments.php

**Comment by olivernybroe** [comment]
@dominikzogg A quick fix you can do in your config file is adding
```
PropertyTypeHintSniff::class => [
    'enableNativeTypeHint' => false,
],
```

**Comment by dominikzogg** [comment]
@nunomaduro all my libraries / projects which using phpinsights and probably many more have this issue now. Would prefer if you would revert this as a default, and then searching for a better solution.

**Comment by dominikzogg** [comment]
@olivernybroe thanks for the suggestion, but i think there are many libraries / projects out there having this issue now.

**Comment by olivernybroe** [comment]
A solution for this has now been merged into master.
