### ISSUE TITLE
[Preset] WordPress

### ISSUE THREAD

**Issue by nunomaduro** [nunomaduro/phpinsights#35]
To perform this task you just have two:

1. Create a new folder `WordPress` within: https://github.com/nunomaduro/phpinsights/tree/master/src/Application/Adapters
2. Add a new instruction on the readme.

**Comment by szepeviktor** [comment]
Could we name the folder *WordPress*?

**Comment by nunomaduro** [comment]
Sure, done! Do you work with WordPress buddy?

**Comment by szepeviktor** [comment]
[Yes](https://github.com/szepeviktor), I run Laravel and WordPress sites.

**Comment by nunomaduro** [comment]
Nice! Fell free to work in this issue. Should be easy. You can check the example within the Symfony repository.

**Comment by szepeviktor** [comment]
Free falling is my favorite.

**Comment by killua99** [comment]
I'm trying to build the Preset for it. I'm getting few errors not quite sure why, perhaps you could provide some help with these

```php
PHP Fatal error:  Uncaught TypeError: Argument 2 passed to SlevomatCodingStandard\Helpers\FunctionHelper::getParametersTypeHints() must be of the type integer, null given, called in /Volumes/Projects/www/xxxxx.com.dev.synot.io/site/vendor/slevomat/coding-standard/SlevomatCodingStandard/Sniffs/TypeHints/DisallowArrayTypeHintSyntaxSniff.php on line 150 and defined in /Volumes/Projects/www/xxx.com.dev.synot.io/site/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/FunctionHelper.php:143
```

**Comment by dingo-d** [comment]
Yeah, I can confirm that running this as is in a WordPress project will fail on the PHPCS sniffs

```bash
PHP Fatal error:  Cannot declare class PHPCompatibility\Sniffs\FunctionUse\RequiredToOptionalFunctionParametersSniff, because the name is already in use in my-project/vendor/phpcompatibility/php-compatibility/PHPCompatibility/Sniffs/FunctionUse/RequiredToOptionalFunctionParametersSniff.php on line 0

Fatal error: Cannot declare class PHPCompatibility\Sniffs\FunctionUse\RequiredToOptionalFunctionParametersSniff, because the name is already in use in my-project/vendor/phpcompatibility/php-compatibility/PHPCompatibility/Sniffs/FunctionUse/RequiredToOptionalFunctionParametersSniff.php on line 0
```

Not sure if `vendor` folder should be included or not when running the checks.

**Comment by olivernybroe** [comment]
@dingo-d The vendor folder should be excluded, however we should already have code that does this.  
We don't scan the vendor folder, as that is not code you have written.

**Comment by dingo-d** [comment]
Yup, noticed that there is a default exclusion list. I'll try to debug why the scan fails on non-bedrock projects.

**Comment by nunomaduro** [comment]
No plans to work on this at this time. Feel free to make a pull request with this feature.
