### ISSUE TITLE
Add min-requirements to config file

### ISSUE THREAD

**Issue by olivernybroe** [nunomaduro/phpinsights#361]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes

Add a new array to config file specifying to minimum requirements.

## Details
Right now the min requirements can only be supplied as running arguments, however as the same values are often required for these, I think they should be added to the config file.

Our Configuration class should then have methods for returning the min value, so we don't read from input or config directly, but look into our config class for it. 
If input args are specified they have higher priority then config file.

I suggest the following structure
```
'requirements' => [
     'min-quality' => 0,
     'min-complexity' => 0,
     'min-architecture' => 0,
     'min-style' => 0,
     'disable-security-check' => false,
]
```

## Implementation
One way this could be implemented is outlined here.
-  Add methods to `Configuration` class for getting the values
- Change `input->getOption` calls to getters from `Configuration` class in `AnalyseCommand`
- Make `ConfigResolver` resolve the requirements (check if they are in input else take them from config) to the `Configuration` class.
- Add default values in stub files.

**Comment by devyk** [comment]
I would be glad to dive in. I'll start working work on this issue.
