### ISSUE TITLE
Better readability

### ISSUE THREAD

**Issue by ghost** [nunomaduro/phpinsights#37]
Make the results of code, complexity, architecture and style more readable. With the dark color, the results are hard to read.

**Comment by szepeviktor** [comment]
Could you share a screenshot?

**Comment by FFDevelopment** [comment]
![Capture](https://user-images.githubusercontent.com/47126617/57585059-162da880-74e3-11e9-8123-48d06a0bcbfe.PNG)

**Comment by nunomaduro** [comment]
I think that is actually a problem from your theme. Can you tell me the theme of your terminal and the terminal you use?

**Comment by FFDevelopment** [comment]
I don't have a theme in Laravel Homestead.

**Comment by stephenlake** [comment]
I can't replicate this on my side, I always natural colours:

![Screenshot from 2019-05-18 12-45-30](https://user-images.githubusercontent.com/1300442/57968437-df381680-796a-11e9-9e04-1f6dbc5c7ffb.png)

**Comment by FFDevelopment** [comment]
@stephenlake which system do you use if you can't replicate this?

**Comment by stephenlake** [comment]
A little bit of everything, except Windoze. Judging by that font style from your terminal screenshot, I'm guessing you're running homestead on Windoze?

**Comment by FFDevelopment** [comment]
yes it runs on windows 10

**Comment by preliot** [comment]
Same here. Followed [https://phpinsights.com/get-started.html#within-laravel](url) to the letter on a Windows 10 64 bits environment for a Laravel application.

Hard to read, because of contrast in the collored boxes for code, complexity, architecture and style. Virtually not readable when in 80-100 scale.

**Comment by olivernybroe** [comment]
We are using the ascii colors. What terminal are you using?

A suggestion could be to make a bigger contrast on the colors, like this
![image](https://user-images.githubusercontent.com/5870441/59106719-614aa800-8937-11e9-8960-5e49c319692d.png)

**Comment by nunomaduro** [comment]
@caneco Maybe can help here.

**Comment by nunomaduro** [comment]
No plans to work on this at this time.

**Comment by enigmatic-user** [comment]
I have the same problem on a Windows 10 (21H2) machine using Take Command v28 as terminal (same in CMD and PowerShell); it looks like in the first screenshot from @ghost.

It seems that the fg=black definition in the Console constants QUALITY, COMPLEXITY, STRUCTURE, and STYLE doesn't work correctly on Windows (at least not on my system); when I change it to fg=white, the percentages are clearly readable.

I couldn't find out yet what the problem with a black foreground is, but maybe it could be changed to white so that all users can see the percentages without using workarounds like selecting the text with the mouse.

**Comment by JustSteveKing** [comment]
> I have the same problem on a Windows 10 (21H2) machine using Take Command v28 as terminal (same in CMD and PowerShell); it looks like in the first screenshot from @ghost.
> 
> It seems that the fg=black definition in the Console constants QUALITY, COMPLEXITY, STRUCTURE, and STYLE doesn't work correctly on Windows (at least not on my system); when I change it to fg=white, the percentages are clearly readable.
> 
> I couldn't find out yet what the problem with a black foreground is, but maybe it could be changed to white so that all users can see the percentages without using workarounds like selecting the text with the mouse.

Yeah I think unfortunately we have a tendency to only test this on mac at times. Happy to accept a PR on this?

**Comment by JustSteveKing** [comment]
> Unfortunately 14 of the tests failed on my system (Windows 10 / XAMPP 8.1.6, which features PHP 8.1.6) directly after cloning the forked repository and running `composer install`, before I had changed anything. Not sure if this is a Windows problem, too. The tests haven't been run on GitHub after creating the PR:
> 
> > First-time contributors need a maintainer to approve running workflows.
> 
> Since it's a micro-change, I don't think I can possibly have caused any problems - the same 14 tests failed after the modification.

Thanks for this, just running the workflows not for due diligence. Both @cmgmyr and myself are in the process of planning the next stable version which will hopefully see some performance improvements alongside stability in the testing.

As soon as these workflows have ran I will merge, from the files I can see that it is only UI changing for the terminal so it shouldn't effect anything else

**Comment by JustSteveKing** [comment]
@enigmatic-user new release includes this fix. As this is an accessibility fix I thought it made sense to get it out as soon as possible.

Thanks for your contribution!

**Comment by enigmatic-user** [comment]
@JustSteveKing Thank you very much for merging this so quickly - and for working on this great package!

**Comment by JustSteveKing** [comment]
> @JustSteveKing Thank you very much for merging this so quickly - and for working on this great package!

You're most welcome!

I don't do much on the package atm though! We are planning the next major release atm though 🙂
