### ISSUE TITLE
Double checks?

### ISSUE THREAD

**Issue by FFDevelopment** [nunomaduro/phpinsights#38]
I'm not sure if this is just a mistake or is it possible that some checks will be executed twice?

Checks like `Nullable type for null default value` or `Useless parentheses`

**Comment by szepeviktor** [comment]
Could you proved a snippet of your output?

**Comment by FFDevelopment** [comment]
Duplicates

[Code](https://github.com/nunomaduro/phpinsights/blob/c1a99b3c5c343578c1e87f3beff0a26e48226dca/src/Domain/Metrics/Code/Code.php)
UnusedVariableSniff::class
RequireCombinedAssignmentOperatorSniff::class
UselessParenthesesSniff::class
UselessSemicolonSniff::class

[Comments](https://github.com/nunomaduro/phpinsights/blob/c1a99b3c5c343578c1e87f3beff0a26e48226dca/src/Domain/Metrics/Code/Comments.php)
NullTypeHintOnLastPositionSniff::class
NullableTypeForNullDefaultValueSniff::class

**Comment by szepeviktor** [comment]
Thank you.

Is a part of the actual output availble for us?

**Comment by FFDevelopment** [comment]
I have already mentioned which entries occur twice in my result.

**Comment by szepeviktor** [comment]
That is OK.

It would be highly beneficial to actually see a snippet of the output.

**Comment by nunomaduro** [comment]
@FFDevelopment Can you try again with the latest version? Perform a `composer update nunomaduro/phpinsights`.

**Comment by FFDevelopment** [comment]
It has already been updated to the latest version.

**Comment by nunomaduro** [comment]
Alright, I need you to send me the exact output you get from the console.

**Comment by FFDevelopment** [comment]
These are the results of 3 different projects

project 1
• [Code] Forbidden public property:
• [Code] 2 unused private attributes:
• [Code] No setter:
• [Code] Useless parentheses:
• [Code] Element name minimal length:
• [Code] Useless overriding method:
• [Code] Disallow empty:
• [Code] Unused parameter:
• [Code] Useless parentheses:
• [Code] Empty comment:
• [Code] Nullable type for null default value:
• [Code] Todo:
• [Code] Nullable type for null default value:
• [Code] Useless constant type hint:
• [Code] Static closure:
• [Complexity] Having `classes` with more than 5 cyclomatic complexity is prohibited - Consider refactoring:
• [Architecture] Class trait and interface length:
• [Architecture] Property per class limit:
• [Architecture] The name property in the `composer.json` contains the default value
• [Architecture] Function length:
• [Style] Line endings:
• [Style] Object operator indent:
• [Style] Line length:
• [Style] Camel caps method name:
• [Style] Doc comment spacing:

project 2
• [Code] Forbidden public property:
• [Code] 2 unused private attributes:
• [Code] Useless parentheses:
• [Code] Element name minimal length:
• [Code] Useless overriding method:
• [Code] Unused parameter:
• [Code] Useless parentheses:
• [Code] Empty comment:
• [Code] Nullable type for null default value:
• [Code] Nullable type for null default value:
• [Code] Static closure:
• [Architecture] The name property in the `composer.json` contains the default value
• [Architecture] Function length:
• [Style] Line endings:
• [Style] Object operator indent:
• [Style] Line length:
• [Style] Doc comment spacing:

project 3
• [Code] Forbidden public property:
• [Code] 2 unused variables:
• [Code] Element name minimal length:
• [Code] 2 unused variables:
• [Code] Useless overriding method:
• [Code] Disallow implicit array creation:
• [Code] Unused parameter:
• [Code] Empty comment:
• [Code] Static closure:
• [Architecture] The name property in the `composer.json` contains the default value
• [Architecture] Function length:
• [Style] Line endings:
• [Style] Object operator indent:
• [Style] Line length:
• [Style] Doc comment spacing:

All projects have the same version of php insights

**Comment by nunomaduro** [comment]
Fixed in https://github.com/nunomaduro/phpinsights/commit/676958de0b982a55908b53e2c0e2d0f980f16950.
