### ISSUE TITLE
Disable insight for path

### ISSUE THREAD

**Issue by enumag** [nunomaduro/phpinsights#380]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| Library version  | 1.14.0

I'd like to disable some insights but only for a subset of classes and leave them enabled elsewhere. Maybe it's already possible but I can't found it in the [docs](https://phpinsights.com/insights/).

Use case:

One thing I really like is the `NunoMaduro\PhpInsights\Domain\Insights\ForbiddenNormalClasses` insight. I really want to use it. However due to Doctrine's internals (generated proxies), Doctrine entities can't be final so I'd like to disable this rule for them in order to not pollute phpinsights output.

**Comment by olivernybroe** [comment]
Hi, take a at https://phpinsights.com/insights/#configure-insights-2

I think that might be what you are looking for.

**Comment by enumag** [comment]
yes you're right... should have looked more carefully

thanks

**Comment by olivernybroe** [comment]
No problem 👍
