### ISSUE TITLE
when install this, i got errors

### ISSUE THREAD

**Issue by sciracioglu** [nunomaduro/phpinsights#381]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| Library version  | x.y.z

i got this error.

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for symfony/console (locked at v5.0.5) -> satisfiable by symfony/console[v5.0.5].
    - Conclusion: don't install phploc/phploc 5.0.0
    - Installation request for nunomaduro/phpinsights ^1.14 -> satisfiable by nunomaduro/phpinsights[v1.14.0].
    - Conclusion: don't install sebastian/version 2.0.1|install phploc/phploc 5.0.0
    - Conclusion: remove sebastian/version 2.0.1|install phploc/phploc 5.0.0
    - nunomaduro/phpinsights v1.14.0 requires phploc/phploc ^5.0|^6.0 -> satisfiable by phploc/phploc[5.0.0, 6.0.0, 6.0.1, 6.0.2, 6.0.x-dev].
    - phploc/phploc 6.0.0 requires sebastian/version ^3.0 -> satisfiable by sebastian/version[3.0.0, 3.0.x-dev].
    - phploc/phploc 6.0.1 requires sebastian/version ^3.0 -> satisfiable by sebastian/version[3.0.0, 3.0.x-dev].
    - phploc/phploc 6.0.2 requires sebastian/version ^3.0 -> satisfiable by sebastian/version[3.0.0, 3.0.x-dev].
    - phploc/phploc 6.0.x-dev requires sebastian/version ^3.0 -> satisfiable by sebastian/version[3.0.0, 3.0.x-dev].
    - Can only install one of: sebastian/version[3.0.0, 2.0.1].
    - Can only install one of: sebastian/version[3.0.x-dev, 2.0.1].
    - Installation request for sebastian/version (locked at 2.0.1) -> satisfiable by sebastian/version[2.0.1].

**Comment by nunomaduro** [comment]
PHP Insights requires PHP 7.3+, and PHPUnit 9.0+. Do you have those?

**Comment by shawnlindstrom** [comment]
PHPUnit 9+ solved this for me when upgrading from Laravel 6 to 7 because Laravel's PHPUnit dependency is set to ^8.5. It's worth noting Laravel 7's PHP depedency is ^7.2.5.

**Comment by olivernybroe** [comment]
@shawnlindstrom Yes, however we require `PHP 7.3+` with Laravel because one of the packages we depend on when using Laravel 7, requires `PHP 7.3`.  

But great hat you are up and running now!
