### ISSUE TITLE
[Question] Removal of SyntaxSniff

### ISSUE THREAD

**Issue by olivernybroe** [nunomaduro/phpinsights#388]
SyntaxSniff is a sniff that checks if the file has correct php syntax, however this sniff is really heavy to run as it runs `shell_exec` to execute a `php -l` command.

I am wondering if we actually needs this sniff as we now have a bunch of checks we do to check if a file is valid.

@50bhan You were the one who worked on fixing some bugs with invalid code, do you think we can remove this sniff?

**Comment by Jibbarth** [comment]
@olivernybroe I think this one is already taken care in PR #373 

I have to continue it to require php-parallel-lint, but the SyntaxSniff is removed in it :wink:

**Comment by olivernybroe** [comment]
Oh right 🤦‍♂ totally forgot about that...
