### ISSUE TITLE
Add parallelization

### ISSUE THREAD

**Issue by olivernybroe** [nunomaduro/phpinsights#390]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| Library version  | 2.0

This issue is about adding parallelization to speed up the tool.
Adding parallelization so all the insights can run at once or so each file is analysed in parallel would be awesome.

I am not sure which is best to add parallelization to, or if it is worth adding parallelization to both.

**Comment by Jibbarth** [comment]
I think we can close this issue now :tada:
