### ISSUE TITLE
Latest version throws a fatal error because of the missing SlevomatCodingStandard

### ISSUE THREAD

**Issue by jakzal** [nunomaduro/phpinsights#394]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| Library version  | 1.14

**Steps to reproduce**

```bash
mkdir issue &&
   cd issue &&
   composer require nunomaduro/phpinsights --dev --no-interaction &&
  ./vendor/bin/phpinsights --version
```

**Expected outcome**

PhpInsights version is displayed.

**Actual outcome**

```
Fatal error: Uncaught NunoMaduro\PhpInsights\Domain\Exceptions\InvalidConfiguration: Unable to config "SlevomatCodingStandard\Sniffs\Commenting\DocCommentSpacingSniff" insight, class doesn't exists. in /issue/vendor/nunomaduro/phpinsights/src/Domain/Configuration.php:319
Stack trace:
#0 /issue/vendor/symfony/options-resolver/OptionsResolver.php(956): NunoMaduro\PhpInsights\Domain\Configuration::NunoMaduro\PhpInsights\Domain\{closure}(Array)
#1 /issue/vendor/symfony/options-resolver/OptionsResolver.php(823): Symfony\Component\OptionsResolver\OptionsResolver->offsetGet('config')
#2 /issue/vendor/nunomaduro/phpinsights/src/Domain/Configuration.php(259): Symfony\Component\OptionsResolver\OptionsResolver->resolve(Array)
#3 /issue/vendor/nunomaduro/phpinsights/src/Domain/Configuration.php(107): NunoMaduro\PhpInsights\Domain\Configuration->resolveConfig(Array)
#4 /issue in /issue/vendor/nunomaduro/phpinsights/src/Domain/Configuration.php on line 319
```

**Comment by mbalandis** [comment]
+1 getting same issue. It simply doesn't work!

**Comment by olivernybroe** [comment]
What PHP version are you running, I was not able to reproduce it.

**Comment by 50bhan** [comment]
I just installed on php 7.2 and it's OK!

![Screenshot from 2020-04-21 12-25-25](https://user-images.githubusercontent.com/36772278/79840660-72739a80-83cb-11ea-96cb-157357f84e70.png)

**Comment by mbalandis** [comment]
It probably works now because today I ran composer update and slevomat has fixed it. It wasn't working yesterday haha.

https://share.getcloudapp.com/xQuW091L

**Comment by jakzal** [comment]
Yept, yesterday it was failing consistently on PHP 7.2-7.4: https://travis-ci.com/github/jakzal/toolbox/builds/161003916

It's fixed today: https://travis-ci.com/github/jakzal/toolbox/builds/161189079

I guess we can close here.

**Comment by olivernybroe** [comment]
Good thing you have it working now! 👍
