### ISSUE TITLE
How to override Preset removals?

### ISSUE THREAD

**Issue by rodrigopedra** [nunomaduro/phpinsights#398]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes (maybe)
| Library version  | 1.14.0

Version 1.14.0 removed the `StaticClosureSniff` from the Laravel Preset. I couldn't find any related issue to get some reasoning about the removal.

As I would like to keep this sniff on the projects I work with, I tried adding it in my local `config/insights.php` to have it back, but adding it back does not override the Preset configuration, so it has no effects.

Is there a way we can override Preset removals?

Thanks a lot for this great package.

<!--
Love PHP Insights? Please consider supporting us via Patreon or OpenCollective:
👉  https://www.patreon.com/nunomaduro
👉  https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=66BYDWAT92N6L
--

**Comment by olivernybroe** [comment]
@rodrigopedra Actually no.

Our merging strategy does not support this, however I think this should be supported as you of course should be able to add it back in.


 @nunomaduro Could you explain the reasoning behind the removal?

**Comment by rodrigopedra** [comment]
Hi @olivernybroe thanks for the response. I might have some time two weeks from now to look into this. Right now I am very busy.

From first sight it seems we will need to cross compare removed and added between preset and userland config (filter out userland added insights from the preset's removed array and filter out userland removed insights from the preset's added array) before merging them.

If that is the way to go and someone else have the time to do it earlier, please be my guest. Otherwise I'll take a look in a couple of weeks.

Thanks again.
