### ISSUE TITLE
Packages defines global functions

### ISSUE THREAD

**Issue by ShawnMcCool** [nunomaduro/phpinsights#40]
I noticed that phpinsights defines global Laravel functions in your application. So if you've modified these functions to have different behavior etc, then yours fail because composer bootstraps packages first.

So, I can't use it basically.

**Comment by nunomaduro** [comment]
Thanks for reporting this @ShawnMcCool.

**Comment by nunomaduro** [comment]
@ShawnMcCool This issue has been fixed. Please perform `composer update nunomaduro/phpinsights` and try again.

**Comment by ShawnMcCool** [comment]
Works like a charm, thanks.
