### ISSUE TITLE
Sniffs documentation

### ISSUE THREAD

**Issue by SandroMiguel** [nunomaduro/phpinsights#415]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| Library version  | x.y.z

Is there any documentation explaining the reasons for each insight?

For example:
_Forbidden setter: Setters are not allowed. Use constructor injection and behavior naming instead._

Where I can find information explaining why I shouldn't use setters?

**Comment by 50bhan** [comment]
@SandroMiguel I believe you can find the description here: https://phpinsights.com/insights/code.html#forbidden-setter .

**Comment by SandroMiguel** [comment]
Thank you for the response @50bhan.
As I can see, only some Insights have the "official explanation".
For example, the insight description for "Forbidden setter" is "This sniff disallows setter methods." but this doesn't tell me **why**.
But yeah, now I got something.
