### ISSUE TITLE
ComposerMustBeValid: config option for version check

### ISSUE THREAD

**Issue by marvinschroeder** [nunomaduro/phpinsights#417]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| Library version  | 1.14.0

Would be great to have a config option to disable the "version" check of the composer.json of ComposerMustBeValid.

• [Architecture] Composer.json is not valid:
composer.json: The version field is present, it is recommended to leave it out if the package is published on Packagist.

So if we develop a package which must have a `<version>` in its composer.json we can disable the check of the version, but not the whole ComposerMustBeValid check, to reach 100% in ARCHITECTURE but still get the composer.json checked.

**Comment by Jibbarth** [comment]
The composer validator has now an option to disable version check. https://github.com/composer/composer/pull/8802

However, that could work only when using ComposerV2.

But maybe we should configure level to raise issue ($errors, $publishErrors, $warnings)

**Comment by Jibbarth** [comment]
Thank you @akosglue to add this feature :100:
