### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by wreckitq** [nunomaduro/phpinsights#418]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| Library version  | 1.14

![image](https://user-images.githubusercontent.com/34129273/85940397-4eda4c80-b946-11ea-9669-c1c828f67ab8.png)

<!--
Love PHP Insights? Please consider supporting us via Patreon or OpenCollective:
👉  https://www.patreon.com/nunomaduro
👉  https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=66BYDWAT92N6L
--

**Comment by 50bhan** [comment]
You need to update PHPUnit to ^9.0. Use this link for more detailed information and command: https://phpinsights.com/get-started.html#within-laravel

**Comment by wreckitq** [comment]
oh, dear. forget about that, thanks so much @50bhan!
it's solving the problem
