### ISSUE TITLE
phpinsights error

### ISSUE THREAD

**Issue by realodix** [nunomaduro/phpinsights#423]
| Q                | A
| ---------------- | -----
| Bug report?      | yes/no
| Feature request? | no
| Library version  | v1.14.0

https://github.com/realodix/urlhub

![Untitled](https://user-images.githubusercontent.com/1314456/89648166-015be280-d8e9-11ea-99d9-89c121a163ec.png)

**Comment by 50bhan** [comment]
I cloned your repo and ran `php artisan insights` and it worked. Could you give us more details? I'm not able to reproduce you issue.

![Screenshot_2020-08-07_22-45-31](https://user-images.githubusercontent.com/36772278/89675994-18f29580-d900-11ea-93f0-340a747f51c0.png)
