### ISSUE TITLE
SniffDecorator.php is throwing Runtime Exception

### ISSUE THREAD

**Issue by bsomeshwer** [nunomaduro/phpinsights#424]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| Library version  | 1.14

I'm getting the following issue when I run the below command:

`vendor/bin/phpinsights --no-interaction --min-quality=90 --min-complexity=80 --min-architecture=80 --min-style=95 --config-path=config/insights.php`

![image](https://user-images.githubusercontent.com/39646194/89651730-f9e50b00-d8e1-11ea-9a18-efc31e17dfbd.png)

I'm using "nunomaduro/phpinsights": "^1.14"

**My Observation:**

This issue is not there in the version 1.13 but I've seen this issue has been fixed in 1.14 as well but still getting the same issue.
Because when install package version with "^" symbol it is always fetching latest package i.e; version 1.14. 

Also, when I see the code in SniffDecorator.php file on git repo 1.14 version I'm not seeing below piece of code

```
set_error_handler(static function (): bool {
            throw new \RuntimeException();
        }, E_NOTICE);
```

But when I download the package into my application using "composer require" command then inside "vendor/nunomaduro" I'm able to see the same lines of code mentioned above. This particular code snippet causing an issue. 

I guess the gip available on git repo might not be properly made. 

Hope you understand the issue and you gonna fix that in current latest branch/tag. 

Thanks

<!--
Love PHP Insights? Please consider supporting us via Patreon or OpenCollective:
👉  https://www.patreon.com/nunomaduro
👉  https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=66BYDWAT92N6L
--

**Comment by 50bhan** [comment]
Hi, thank you for reporting this issye. But unfortunately I can't reproduce your problem! I just installed the latest version (1.14) and everything seems fine: 
![Screenshot_2020-08-07_22-02-53](https://user-images.githubusercontent.com/36772278/89672792-7c79c480-d8fa-11ea-8874-1503a2c3418e.png)

About your mentioned piece of code, you can see it in V14.0  here => https://github.com/nunomaduro/phpinsights/blob/4e9672fdb78b7d0ea2708f6303ca134986d6af1a/src/Domain/Insights/SniffDecorator.php#L63

**Comment by bsomeshwer** [comment]
Hi @50bhan ,

I'm giving you the path here:

> 1. Go to tags
> 2. Next, click on tag v1.14.0 
> 3. Next, download the Source code (zip)
> ![image](https://user-images.githubusercontent.com/39646194/89773986-985faf00-db22-11ea-94db-f8fefe1711cd.png)
> 4. And then go to below path \phpinsights-1.14.0 (1)\phpinsights-1.14.0\src\Domain\Insights\SniffDecorator.php
> 5. And at line number 63 we can see the piece of code that causing an issue.

I thought this is causing an issue but not sure. If this is not the issue then I can help you with my composer.json file and Laravel & PHP versions so that you can replicate it from your side.

**Comment by bsomeshwer** [comment]
Here is my composer.json

```
"require": {
        "php": "^7.3",
        "barryvdh/laravel-cors": "^0.11.2",
        "doctrine/dbal": "^2.8",
        "fideloper/proxy": "^4.0",
        "google/recaptcha": "^1.2",
        "laravel/framework": "5.6.*",
        "laravel/passport": "^6.0",
        "laravel/tinker": "^1.0",
        "league/flysystem-aws-s3-v3": "~1.0",
        "maatwebsite/excel": "^3.1",
        "matthewbdaly/laravel-azure-storage": "^1.3",
        "moneyphp/money": "^3.2",
        "predis/predis": "^1.1",
        "sentry/sentry-laravel": "^0.11.0"
    },
    "require-dev": {
        "behat/behat": "^3.4",
        "filp/whoops": "^2.0",
        "fzaninotto/faker": "^1.4",
        "mockery/mockery": "^1.0",
        "nunomaduro/collision": "^2.0",
        "phpunit/phpunit": "^7.0",
        "friendsofphp/php-cs-fixer": "^2.13",
        "mavimo/phpstan-junit": "^0.3.0",
        "nunomaduro/phpinsights": "^1.12",
        "phpstan/phpstan": "^0.12.8"
    },
    "autoload": {
        "classmap": [
            "database/seeds",
            "database/factories"
        ],
        "psr-4": {
            "App\\": "app/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "extra": {
        "laravel": {
            "dont-discover": [
            ]
        }
    },
```

> PHP 7.3.19-1+ubuntu18.04.1+deb.sury.org+1 (cli)
> Zend Engine v3.3.19
> Zend OPcache v7.3.19-1+ubuntu18.04.1+deb.sury.org+1
> 
> Laravel Framework 5.6.40

**Comment by 50bhan** [comment]
@bsomeshwer Yes I added that piece of code to fix another bug. I believe your problem is not related to that code and failure is occurring somewhere else, but yes, that piece of code is responsible for throwing that exception. 

So, I just installed a new Laravel project (V5.6.40) and installed `phpinsights` on it. You can see everything is fine:
![Screenshot from 2020-08-10 16-48-18](https://user-images.githubusercontent.com/36772278/89782196-0f4c7600-db2a-11ea-9928-33215ae52967.png)

I think it might related to one of your classes/files and `phpinsights` can't analyze it and it fails. Can you find out that class/file? That way I can test analyzer and find the point of failure.

**Comment by bsomeshwer** [comment]
Okay @50bhan.
`phpinsights` can't analyse the file and it fails. If this is the case then is there any way to know which file causing an issue by `phpinsights` ? Because scanning was done for all the files and at the end it was throwing  this error. I'm unable to figure it out which file causing an issue by `phpinsights` and which file `phpinsights` unable to analyse. 

If you see below image: all the files (224/224 = 100%) have been scanned and at the end it was returning this output.
![image](https://user-images.githubusercontent.com/39646194/89887927-bdb8ef80-dbec-11ea-9bfd-f37844302d4b.png)

**Comment by 50bhan** [comment]
@bsomeshwer Thank you for your help. You can comment that piece of code in `SniffDecorator` and then run `phpinsights` again. This way it's possible to find the point of failure.

**Comment by bsomeshwer** [comment]
Hi @50bhan , After commented out those line I did not get any error It was success and shown some suggestions to modify the files as ususal.

But here in this case I just want to know which file is causing an issue and which file is failed to read by `phpinsights`.

Would you mind if I would suggest you that displaying error message with file information that which file is causing an issue and which file is failed to read/analyse by `phpinsights` instead of throwing the "Runtime Exception" there on the console?
Because, there is no use of that error message "Runtime Exception" to the end user.

**Comment by bsomeshwer** [comment]
@50bhan , Btw, executing the command after commenting out the lines specified I'm getting other error as follows:

![image](https://user-images.githubusercontent.com/39646194/89899907-98ce7780-dc00-11ea-9954-bc23285324bb.png)

![image](https://user-images.githubusercontent.com/39646194/89900101-e9de6b80-dc00-11ea-926c-9d6a01019766.png)
 
![image](https://user-images.githubusercontent.com/39646194/89900176-011d5900-dc01-11ea-88c9-d309d037c6c6.png)

**Comment by 50bhan** [comment]
@bsomeshwer It's really weird! Because if everything is fine, there is no need to throw an exception. That code will get triggered if something goes wrong. I believe you had these warnings before you commented out that code, right? Because in the first photo, I can see the warnings. Anyway, can you test you code with `dev-master`?

**Comment by bsomeshwer** [comment]
I believe you had these warnings before you commented out that code, right?   - Yes
Because in the first photo, I can see the warnings - True

I didn't notice that. My apologies.

Anyhow, can't we see which file causing an issue rather than showing  that "RuntimeException" error as follows:

![image](https://user-images.githubusercontent.com/39646194/89904236-4bed9f80-dc06-11ea-8486-9447c6fcda1d.png)

**Comment by bsomeshwer** [comment]
@50bhan 
Interestingly this issue is not there in 1.13 version.

**Comment by 50bhan** [comment]
@bsomeshwer Can you put `dd($this->fileInfo);` in this catch block? https://github.com/nunomaduro/phpinsights/blob/1f26a9fd84dd22ccb44372a768c745016b0f92a6/src/Domain/File.php#L55

It might help to find that file which causing exception.

**Comment by bsomeshwer** [comment]
Hi @50bhan , I did that but no luck. Again I'm getting same issue. Control not entering into catch block.

Here is the o/p:
![image](https://user-images.githubusercontent.com/39646194/90144866-f992b700-dd9c-11ea-9ecc-c7046618a025.png)

![image](https://user-images.githubusercontent.com/39646194/90145112-3b236200-dd9d-11ea-8501-4eed4f7a6c64.png)

**Comment by bsomeshwer** [comment]
Hi @50bhan,

Any update on this? How can we handle this?

Thanks

**Comment by olivernybroe** [comment]
hi @bsomeshwer Could you try and run with verbose output, so we can see some data on this `RuntimeException`?

**Comment by 50bhan** [comment]
@bsomeshwer Hi, sorry for delay. I had a busy week. As @olivernybroe said, verbose output will be a good idea to track the problem down.

**Comment by bsomeshwer** [comment]
Hi @50bhan , Sorry for the delay. I was on vacation. We are using 1.13.0 version which is not throwing the above error. 

We can close this issue. Thanks

**Comment by 50bhan** [comment]
@bsomeshwer It's OK. Actually the main point was solving your problem as well as any potential bug in version 14.0. Anyway, let me know if I can help you with your issue.

**Comment by bsomeshwer** [comment]
Thanks @50bhan , I'll send you here the verbose output. Let us check if that helps.

**Comment by bsomeshwer** [comment]
Hi @50bhan / @olivernybroe ,

As I said, this issue is not there with 1.13.0 version that we are currently using but this 1.13 version has one security alert so, definitely we need to upgrade to 1.14 version. 

But when I use 1.14 version I'm getting same issue as above..

![image](https://user-images.githubusercontent.com/39646194/115356890-b74a3100-a1d9-11eb-9159-7dfc9d95be7e.png)

Please see my first comment for more information.

I'm not getting any exception message like which is causing issue. Could you please help me to resolve that.

Thanks

**Comment by bsomeshwer** [comment]
Please find the latest screens below:

Exception trace:
at /var/www/vendor/nunomaduro/phpinsights/src/Domain/Insights/SniffDecorator.php:64
NunoMaduro\PhpInsights\Domain\Insights\SniffDecorator::NunoMaduro\PhpInsights\Domain\Insights\{closure}() at n/a:n/a
array_diff() at /var/www/vendor/nunomaduro/phpinsights/src/Domain/Insights/InsightCollectionFactory.php:118
NunoMaduro\PhpInsights\Domain\Insights\InsightCollectionFactory->getInsights() at /var/www/vendor/nunomaduro/phpinsights/src/Domain/Insights/InsightCollectionFactory.php:91
NunoMaduro\PhpInsights\Domain\Insights\InsightCollectionFactory->get() at /var/www/vendor/nunomaduro/phpinsights/src/Application/Console/Analyser.php:58
NunoMaduro\PhpInsights\Application\Console\Analyser->analyse() at /var/www/vendor/nunomaduro/phpinsights/src/Application/Console/Commands/AnalyseCommand.php:70
NunoMaduro\PhpInsights\Application\Console\Commands\AnalyseCommand->__invoke() at n/a:n/a
call_user_func() at /var/www/vendor/nunomaduro/phpinsights/src/Application/Console/Commands/InvokableCommand.php:37
NunoMaduro\PhpInsights\Application\Console\Commands\InvokableCommand->execute() at /var/www/vendor/symfony/console/Command/Command.php:255
Symfony\Component\Console\Command\Command->run() at /var/www/vendor/symfony/console/Application.php:1009
Symfony\Component\Console\Application->doRunCommand() at /var/www/vendor/symfony/console/Application.php:273
Symfony\Component\Console\Application->doRun() at /var/www/vendor/symfony/console/Application.php:149
Symfony\Component\Console\Application->run() at /var/www/vendor/nunomaduro/phpinsights/bin/phpinsights:35
{closure}() at /var/www/vendor/nunomaduro/phpinsights/bin/phpinsights:36

![image](https://user-images.githubusercontent.com/39646194/115357276-1ad45e80-a1da-11eb-8776-71afa0cd74d5.png)

**Comment by 50bhan** [comment]
@bsomeshwer Still can't reproduce your issue. But from looking into the stack trace, I think it might be related to the config. Can you post your config to see if there is an issue there?

**Comment by bsomeshwer** [comment]
@50bhan , Could you please let me know which config you are referring to?

**Comment by bsomeshwer** [comment]
> @bsomeshwer Still can't reproduce your issue. But from looking into the stack trace, I think it might be related to the config. Can you post your config to see if there is an issue there?

Yeah, surprisingly it's not occurring in all machines. I'm able to reproduce it where as one of my teammate can not reproduce and it's all working fine in his machine.

**Comment by bsomeshwer** [comment]
@50bhan , Here is the insights.php config file.

```
<?php

declare(strict_types=1);

use NunoMaduro\PhpInsights\Domain\Insights\ForbiddenDefineFunctions;
use NunoMaduro\PhpInsights\Domain\Insights\ForbiddenDefineGlobalConstants;
use NunoMaduro\PhpInsights\Domain\Insights\ForbiddenFinalClasses;
use NunoMaduro\PhpInsights\Domain\Insights\ForbiddenNormalClasses;
use NunoMaduro\PhpInsights\Domain\Insights\ForbiddenPrivateMethods;
use NunoMaduro\PhpInsights\Domain\Insights\ForbiddenTraits;
use NunoMaduro\PhpInsights\Domain\Metrics\Architecture\Classes;
use NunoMaduro\PhpInsights\Domain\Sniffs\ForbiddenSetterSniff;
use ObjectCalisthenics\Sniffs\Classes\ForbiddenPublicPropertySniff;
use PHP_CodeSniffer\Standards\Generic\Sniffs\Commenting\TodoSniff;
use PHP_CodeSniffer\Standards\Generic\Sniffs\PHP\ForbiddenFunctionsSniff;
use PHP_CodeSniffer\Standards\PEAR\Sniffs\WhiteSpace\ObjectOperatorIndentSniff;
use PhpCsFixer\Fixer\Operator\BinaryOperatorSpacesFixer;
use PhpCsFixer\Fixer\Whitespace\MethodChainingIndentationFixer;
use SlevomatCodingStandard\Sniffs\Classes\SuperfluousAbstractClassNamingSniff;
use SlevomatCodingStandard\Sniffs\Classes\SuperfluousExceptionNamingSniff;
use SlevomatCodingStandard\Sniffs\Classes\SuperfluousInterfaceNamingSniff;
use SlevomatCodingStandard\Sniffs\Commenting\DocCommentSpacingSniff;
use SlevomatCodingStandard\Sniffs\Commenting\UselessFunctionDocCommentSniff;
use SlevomatCodingStandard\Sniffs\Namespaces\AlphabeticallySortedUsesSniff;
use SlevomatCodingStandard\Sniffs\TypeHints\DeclareStrictTypesSniff;
use SlevomatCodingStandard\Sniffs\TypeHints\DisallowArrayTypeHintSyntaxSniff;
use SlevomatCodingStandard\Sniffs\TypeHints\DisallowMixedTypeHintSniff;
use SlevomatCodingStandard\Sniffs\TypeHints\ParameterTypeHintSniff;
use SlevomatCodingStandard\Sniffs\TypeHints\PropertyTypeHintSniff;
use SlevomatCodingStandard\Sniffs\TypeHints\ReturnTypeHintSniff;

return [

    /*
    |--------------------------------------------------------------------------
    | Default Preset
    |--------------------------------------------------------------------------
    |
    | This option controls the default preset that will be used by PHP Insights
    | to make your code reliable, simple, and clean. However, you can always
    | adjust the `Metrics` and `Insights` below in this configuration file.
    |
    | Supported: "default", "laravel", "symfony", "magento2", "drupal"
    |
    */

    'preset' => 'laravel',
    /*
    |--------------------------------------------------------------------------
    | IDE
    |--------------------------------------------------------------------------
    |
    | This options allow to add hyperlinks in your terminal to quickly open
    | files in your favorite IDE while browsing your PhpInsights report.
    |
    | Supported: "textmate", "macvim", "emacs", "sublime", "phpstorm",
    | "atom", "vscode".
    |
    | If you have another IDE that is not in this list but which provide an
    | url-handler, you could fill this config with a pattern like this:
    |
    | myide://open?url=file://%f&line=%l
    |
    */

    'ide' => null,
    /*
    |--------------------------------------------------------------------------
    | Configuration
    |--------------------------------------------------------------------------
    |
    | Here you may adjust all the various `Insights` that will be used by PHP
    | Insights. You can either add, remove or configure `Insights`. Keep in
    | mind that all added `Insights` must belong to a specific `Metric`.
    |
    */

    'exclude' => [
        'config',
        'storage',
        'resources',
        'bootstrap',
        'nova',
        'database',
        'server.php',
        '_ide_helper.php',
        '_ide_helper_models.php',
        'public',
    ],

    'add' => [
        Classes::class => [
            ForbiddenFinalClasses::class,
        ],
    ],

    'remove' => [
        // Code
        DeclareStrictTypesSniff::class,
        DisallowMixedTypeHintSniff::class,
        ForbiddenDefineFunctions::class,
        ForbiddenNormalClasses::class,
        ForbiddenTraits::class,
        ForbiddenDefineGlobalConstants::class => [
            'ignore' => ['LARAVEL_START'],
        ],
        ForbiddenFunctionsSniff::class => [
            'forbiddenFunctions' => [
                'dd'   => null,
                'dump' => null,
            ],
        ],
        ForbiddenPublicPropertySniff::class,
        ForbiddenSetterSniff::class,
        TodoSniff::class,
        DisallowArrayTypeHintSyntaxSniff::class,
        PropertyTypeHintSniff::class,
//        TypeHintDeclarationSniff::class,
        // Architecture
        SuperfluousAbstractClassNamingSniff::class,
        SuperfluousExceptionNamingSniff::class,
        SuperfluousInterfaceNamingSniff::class,
        // Style
        ObjectOperatorIndentSniff::class,
        DocCommentSpacingSniff::class,
        BinaryOperatorSpacesFixer::class,
        MethodChainingIndentationFixer::class,
    ],

    'config' => [
        ForbiddenPrivateMethods::class => [
            'title' => 'The usage of private methods is not idiomatic in Laravel.',
        ],
    ],

];

```

**Comment by bsomeshwer** [comment]
do we need to change anything in the configuration file?

**Comment by 50bhan** [comment]
@bsomeshwer Sure! I found the problem. In the `remove` section, you shouldn't specify functions for a sniff! Just add the name of the class and that's it.

Look at `ForbiddenDefineGlobalConstants` and `ForbiddenFunctionsSniff` classes! They should be like this:

```
    'remove' => [
        // Code
        DeclareStrictTypesSniff::class,
        DisallowMixedTypeHintSniff::class,
        ForbiddenDefineFunctions::class,
        ForbiddenNormalClasses::class,
        ForbiddenTraits::class,
        ForbiddenDefineGlobalConstants::class,
        ForbiddenFunctionsSniff::class,
        ForbiddenPublicPropertySniff::class,
        ForbiddenSetterSniff::class,
        TodoSniff::class,
        DisallowArrayTypeHintSyntaxSniff::class,
        PropertyTypeHintSniff::class,
//        TypeHintDeclarationSniff::class,
        // Architecture
        SuperfluousAbstractClassNamingSniff::class,
        SuperfluousExceptionNamingSniff::class,
        SuperfluousInterfaceNamingSniff::class,
        // Style
        ObjectOperatorIndentSniff::class,
        DocCommentSpacingSniff::class,
        BinaryOperatorSpacesFixer::class,
        MethodChainingIndentationFixer::class,
    ],
```

**Comment by bsomeshwer** [comment]
Hi @50bhan , Thank you!
I have made the changes as you suggested and it's all working fine now.
Thanks a lot!!

**Comment by 50bhan** [comment]
@bsomeshwer Great! Glad it worked 🙂
