### ISSUE TITLE
Install - Composer .json wrong config

### ISSUE THREAD

**Issue by MatPoot** [nunomaduro/phpinsights#425]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| Library version  | master

Install issues, Laravel 7.0+

I have a running project that I'd like to try phpinsights on. 

I'm getting the same issue as https://github.com/nunomaduro/phpinsights/issues/397

However, the stated solution also gets the same error as well

`C:\xampp\htdocs>composer require --dev phpunit/phpunit
Using version ^9.3 for phpunit/phpunit
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for phar-io/version (locked at 2.0.1) -> satisfiable by phar-io/version[2.0.1].
    - phpunit/phpunit 9.3.0 requires phar-io/version ^3.0.2 -> satisfiable by phar-io/version[3.0.2].
    - phpunit/phpunit 9.3.1 requires phar-io/version ^3.0.2 -> satisfiable by phar-io/version[3.0.2].
    - phpunit/phpunit 9.3.2 requires phar-io/version ^3.0.2 -> satisfiable by phar-io/version[3.0.2].
    - phpunit/phpunit 9.3.3 requires phar-io/version ^3.0.2 -> satisfiable by phar-io/version[3.0.2].
    - phpunit/phpunit 9.3.4 requires phar-io/version ^3.0.2 -> satisfiable by phar-io/version[3.0.2].
    - phpunit/phpunit 9.3.5 requires phar-io/version ^3.0.2 -> satisfiable by phar-io/version[3.0.2].
    - phpunit/phpunit 9.3.x-dev requires phar-io/version ^3.0.2 -> satisfiable by phar-io/version[3.0.2].
    - phpunit/phpunit 9.4.x-dev requires phar-io/version ^3.0.2 -> satisfiable by phar-io/version[3.0.2].
    - Conclusion: don't install phar-io/version 3.0.2
    - Installation request for phpunit/phpunit ^9.3 -> satisfiable by phpunit/phpunit[9.3.0, 9.3.1, 9.3.2, 9.3.3, 9.3.4, 9.3.5, 9.3.x-dev, 9.4.x-dev].

Installation failed, reverting ./composer.json to its original content.
`

Composter file is as follows:

`{
    "name": "laravel/laravel",
    "type": "project",
    "description": "The Laravel Framework.",
    "keywords": [
        "framework",
        "laravel"
    ],
    "license": "MIT",
    "require": {
        "php": "^7.2.5",
        "fideloper/proxy": "^4.2",
        "fruitcake/laravel-cors": "^1.0",
        "guzzlehttp/guzzle": "^7.0",
        "laravel/framework": "^7.0",
        "laravel/tinker": "^2.0",
        "laravel/ui": "^2.0"
    },
    "require-dev": {
        "facade/ignition": "^2.0",
        "fzaninotto/faker": "^1.9.1",
        "mockery/mockery": "^1.3.1",
        "nunomaduro/collision": "^4.1",
        "phpunit/phpunit": "^8.5"
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/"
        },
        "classmap": [
            "database/seeds",
            "database/factories"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "scripts": {
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi"
        ]
    }
}
`

<!--
Love PHP Insights? Please consider supporting us via Patreon or OpenCollective:
👉  https://www.patreon.com/nunomaduro
👉  https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=66BYDWAT92N6L
--

**Comment by 50bhan** [comment]
@MatPoot You should use this command `composer require --dev phpunit/phpunit:^9.0 --update-with-dependencies` before installing `Phpinsights`.

**Comment by MatPoot** [comment]
Fixed it; it seems that the --update-with-dependencies part is mandatory; the normal log when I'm installing something already says its looking for dependancies and satisfying them so I thought it was okay.

Thank you.
