### ISSUE TITLE
phploc 7 is not allowed

### ISSUE THREAD

**Issue by garak** [nunomaduro/phpinsights#427]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| Library version  | latest

Currently only phploc 5 and 6 are allowed. Version 7 should be allowed too.

**Comment by nunomaduro** [comment]
Can you make a pull request on that?

**Comment by garak** [comment]
sure!

**Comment by Jibbarth** [comment]
Thank you @garak :raised_hands:
