### ISSUE TITLE
When is 2.0 coming out, why its stated in the docs, but there are no signs of it

### ISSUE THREAD

**Issue by juslintek** [nunomaduro/phpinsights#431]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| Library version  | 1.14.0

Wonder when version 2.0 is coming out, really want the fix feature as mentioned here: https://phpinsights.com/get-started.html#fixing-errors-automatically

**Comment by nunomaduro** [comment]
I am with 0 time for this project. I think @olivernybroe too.

Maybe @Jibbarth ?

**Comment by nunomaduro** [comment]
Otherwise we may need to ask for contributors on twitter, it may be the best option here.

**Comment by olivernybroe** [comment]
Yes I am unfortunately also down to 0 time, as my spare time is on pestphp at the moment. 

Might be worth asking for contributors yep. 

I think @50bhan is also spending time here 😄

**Comment by 50bhan** [comment]
@nunomaduro I think we just need to finish #414 for V2.0 (based on prior road map) and after that we are all set.

**Comment by nunomaduro** [comment]
Already, lets see if @Jibbarth or youtself @50bhan wanna work on the #414

**Comment by olivernybroe** [comment]
So it seems like #414 is done now, however I think making v2 release without fixing #436 might be a bad user experience.

WDYT?

**Comment by 50bhan** [comment]
@olivernybroe Agree! And I believe it's nice to have a look into #430, because `symfony` users can't install `phpinsights` right now.

**Comment by Jibbarth** [comment]
@olivernybroe Agree with you. It would be better to jump to v2 without abandoned project as dependencies.

@50bhan I just check the #430. For me, it's not related to symfony, just to an other dependency. I think I provided a solution in the issue :wink:
