### ISSUE TITLE
 Call to a member function addDetails() on null

### ISSUE THREAD

**Issue by Algeneralo** [nunomaduro/phpinsights#434]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| Library version  | 1.14
| Larave version  | 7.0

I just installed the library and tried to use the command `php artisan insights` but I got an error.
![image](https://user-images.githubusercontent.com/32073999/91594724-043b7780-e96b-11ea-8a63-6a8038adf871.png)

Note: I am using windows as an OS

**Comment by 50bhan** [comment]
@Algeneralo I think your issue might be duplicate of #350. The cause of the error is mixed line endings. If you want to get rid of it quickly, fix your line ending, otherwise I will see if I can find a suitable workaround.

**Comment by 50bhan** [comment]
@Algeneralo BTW, I can't really create a file with mixed line endings! Which IDE/Editor do you use?

**Comment by Algeneralo** [comment]
> @Algeneralo I think your issue might be duplicate of #350. The cause of the error is mixed line endings. If you want to get rid of it quickly, fix your line ending, otherwise I will see if I can find a suitable workaround.

what do you mean by "fix your line ending"?
I'm using PhpStorm as an IDE

**Comment by 50bhan** [comment]
@Algeneralo I mean end of line character is mixed (some lines ended with "\n" and some with "\r\n" or something). Of course I'm not sure that your problem is related to this, but I just guess because in #350 the error was the same as yours and the problem was mixed line endings.

**Comment by Algeneralo** [comment]
@50bhan do you have a solution for that issue?

**Comment by 50bhan** [comment]
@Algeneralo Unfortunately I'm not able to reproduce this issue! So I just assumed the problem is from mixed line ending. If you can send me your trouble maker file, I can find a workaround.

**Comment by Algeneralo** [comment]
@nunomaduro any help with this issue?

**Comment by Algeneralo** [comment]
I tracked the issue and there was a comma here
![image](https://user-images.githubusercontent.com/32073999/93026722-c5ffb280-f610-11ea-9af4-cf255a6741e2.png)
