### ISSUE TITLE
Can't install on PHP 8 (RC3)

### ISSUE THREAD

**Issue by mwi-gofore** [nunomaduro/phpinsights#446]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| Library version  | master

Cannot install on PHP 8;
```
- nunomaduro/phpinsights dev-master requires php ^7.4 -> your php version (8.0.0RC3) does not satisfy that requirement.
```

**Comment by nunomaduro** [comment]
https://github.com/nunomaduro/phpinsights/pull/444

**Comment by mwi-gofore** [comment]
moved to #448 apparently

**Comment by Jibbarth** [comment]
#448 is merged :tada:
