### ISSUE TITLE
Referenced sniff "PHPCompatibility" does not exist

### ISSUE THREAD

**Issue by saimonh3** [nunomaduro/phpinsights#449]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| Library version  | 1.14.0

Whenever I run the command, I always get the following error. I see a similar issue https://github.com/nunomaduro/phpinsights/issues/426

<img width="700" alt="Screen Shot 2020-12-23 at 6 07 40 PM" src="https://user-images.githubusercontent.com/13016829/102994801-fcbb6200-4549-11eb-86eb-e28024abb176.png">

**Comment by 50bhan** [comment]
@saimonh3 Could you tell me what your PHP version is?

**Comment by saimonh3** [comment]
@50bhan I'm on PHP 7.4

**Comment by 50bhan** [comment]
@saimonh3 So, please run it again with verbose output.

**Comment by saimonh3** [comment]
@50bhan Nevermind, I removed vendor dir, and composer install again, seems working fine now.
