### ISSUE TITLE
the custom config of LineLengthSniff doesn't work for me.

### ISSUE THREAD

**Issue by miguelselectra** [nunomaduro/phpinsights#450]
| Q                | A
| the custom config of LineLengthSniff doesn't work for me. | -----
| Bug report?      | no
| Feature request? | no
| Library version  | 1.14.0

Hi guys, 
I found trouble trying to change the config/insights.php in a Laravel project. When I try to change the values it doesn't change anything when I run the PHPInsight.
![image](https://user-images.githubusercontent.com/54810616/103097417-71080b00-4607-11eb-99c5-6b796f918b9e.png)
config/insights.php
Any idea what could be going on?

<!--
Love PHP Insights? Please consider supporting us via Patreon or OpenCollective:
👉  https://www.patreon.com/nunomaduro
👉  https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=66BYDWAT92N6L
--

**Comment by 50bhan** [comment]
@miguelselectra Could you please test your code with the dev-master branch?

**Comment by miguelselectra** [comment]
> @miguelselectra Could you please test your code with the dev-master branch?

I did it but the behavior does not change 🤔

**Comment by 50bhan** [comment]
@miguelselectra Unfortunately I can't reproduce your issue and everything seems fine.

How do you run the `phpInsights`? Via `php artisan insights` or './vendor/bin/phpinsights analyse` command?

**Comment by miguelselectra** [comment]
> @miguelselectra 
> How do you run the `phpInsights`? Via `php artisan insights` or './vendor/bin/phpinsights analyse` command?

The second one, I tried with this one:
vendor/bin/phpinsights analyse app/Exports/Subscriber.php

**Comment by 50bhan** [comment]
@miguelselectra Can you pass the config file through command parameters and check if it's working?

`./vendor/bin/phpinsights analyse app/Exports/Subscriber.php --config-path=PATH/TO/CONFIG/FILE`

**Comment by ibeona** [comment]
Hello @50bhan , 
I'm following this issue, with config path, it seems to works well, yes!
