### ISSUE TITLE
Configuring custom indent style for PHP-CS-Fixer

### ISSUE THREAD

**Issue by gerryd** [nunomaduro/phpinsights#451]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| Library version  | 1.13.0

I would like to configure PHP-CS-Fixer with a custom indentation style. With native PHP-CS-Fixer, this can be done by using `setIndent()` when creating the configuration, but it is not clear to me how this should work when running through PHP Insights.

Any hints? Thanks!

**Comment by Jibbarth** [comment]
Hi @gerryd :wave: 

Sorry for the delay :sweat_smile:  

I just checked, it's not possible currently. 

But it would be "easy" to implements.

I see two way of handling this: 

### A global config
By global config, I think to a `indent` option that could be in `phpinsights.php` config file.
```php
<?php
// phpinsights.php

return [
    // ... 
    'indent' => '  ',
]
```

We would have to: 
* Add an indent option in config file (with default with 4 space)
* Pass this configuration to the FixerLoader
* Create a WhitespacesFixerConfig and set it to Fixer if it's an instance of WhitespacesAwareFixerInterface
* Add the `PhpCsFixer\Fixer\Whitespace\IndentationTypeFixer` in Style metrics

### Per fixer config

That would allow to specify indent for each fixer that implement `WhitespacesAwareFixerInterface`
So in `phpinsights.php`, in config key, something like this : 

```php
<?php
// phpinsights.php

return [
    // ...
    'configure' => [
        PhpCsFixer\Fixer\Basic\BraceFixer::class => [
            'indent' => '  ',
		]
    ]
]
```

We would have to: 
* In FixerLoader, if configuration contains indent AND Fixer instance of WhitespacesAwareFixerInterface, set a WhitespacesFixerConfig only for this fixer.

I don't know what would be the better way, maybe the first solution. WDYT ? Do you want provide a PR for a such feature ?

**Comment by Jibbarth** [comment]
Done in #502 
Thank you @gerryd :+1:
