### ISSUE TITLE
Security Checker

### ISSUE THREAD

**Issue by pedroufv** [nunomaduro/phpinsights#455]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | yes
| Library version  | 1.15.0

There is a problem with the Security Checker, every time it fails and I therefore had to disable it to continue using it in CI

https://github.com/nunomaduro/phpinsights/blob/master/src/Domain/Insights/ForbiddenSecurityIssues.php

This file uses a package that has recently become deprecated: https://github.com/sensiolabs/security-checker

**Comment by Jibbarth** [comment]
Hello ! 

We already provide a fix for the 1.14.x version. 

The 1.15.0 version you mention doesn't exist. Did you mean dev-master ?

If it's the case, we 'll soon backport the fix on it. 

Thanks
