### ISSUE TITLE
PHP8 Constructor Property Promotion error

### ISSUE THREAD

**Issue by tarlepp** [nunomaduro/phpinsights#457]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| Library version  | 1.14.1

If we're using PHP8 and new `Constructor Property Promotion` feature it seems like PHP Insights doesn't understand that those parameters are actually used.

`src/Foo.php`:
```php
<?php

namespace App;

class Foo
{
    public function __construct(private Bar $bar)
    {
    }

    public function foo(): void
    {
        $this->bar->bar();
    }
}
```

`src/Bar.php`:
```php
<?php

namespace App;

class Bar
{
    public function bar(): void
    {
        // do something...
    }
}
```

And when I run PHP Insights I get error;

```
src/Foo.php:7: Unused parameter $bar.
```

Which is not true.

**Comment by Jibbarth** [comment]
Hi @tarlepp 

Thanks for reporting :+1: 

It seems that the Sniff rule is `SlevomatCodingStandard\Sniffs\Functions\UnusedParameterSniff` right ? 

Following this issue https://github.com/slevomat/coding-standard/issues/1156, the promotion property support is added in dev-master, so we can expect support soon :slightly_smiling_face:

**Comment by tarlepp** [comment]
@Jibbarth First of all, thanks for quick reply! I didn't look for the root cause for this, just reporting issue - and it seems like you're right with that issue on that slevomat repository (or at least it seems to be the issue) - So we just need to wait that they release new version `7.0.0` (if I understand that correctly) and then PHP Insights needs to update that dependency to next major and release new version.

So it's just waiting game here :D
