### ISSUE TITLE
`CyclomaticComplexityIsHigh` doesn't respect `exclude`

### ISSUE THREAD

**Issue by MatanYadaev** [nunomaduro/phpinsights#458]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| Library version  | dev-feature/php8-and-github-action

Excluding files from being tested in the `CyclomaticComplexityIsHigh` sniff isn't preventing the error message.

This is the regular output, before excluding any file:
```
...

• [Complexity] Having `classes` with more than 5 cyclomatic complexity is prohibited - Consider refactoring:
  src/Factory.php: 9 cyclomatic complexity

...
```

And this is after excluding `src/Factory.php`

```
...

• [Complexity] Having `classes` with more than 5 cyclomatic complexity is prohibited - Consider refactoring:

...
```

As you can see, the "Having classes with more than ..." error message is still there even though there are no files that failed at this test.

**Comment by Jibbarth** [comment]
Hey ! Thanks for reporting.

Maybe this is related to #367 ?
