### ISSUE TITLE
Type hint not detected when using @var on property

### ISSUE THREAD

**Issue by Borlabs-Ben** [nunomaduro/phpinsights#462]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| Library version  | 1.14.1

When writing a type hint on a property using @var, PHPInsights doesn't detect the native type.

```
/** @var array<int, string> $myStringArray */
private $myStringArray = [];
```

This doesn't restrict to arrays, strings, int, object, bool and NULL do not work too. 
Only callable works for the moment.

## Example Code
```
<?php

namespace MyDemo;

/**
 * Class MySingleton
 *
 * @package MyDemo
 */
final class MySingleton
{
    /** @var callable $instance */
    private static $instance;

    public static function getInstance(): MySingleton
    {
        if (self::$instance === null) {
            self::$instance = new self();
        }

        return self::$instance;
    }

    /** @var array<int, string> $myStringArray */
    private $myStringArray = [];

    /*
        Property \Demo\MySingleton::$myStringArray does not have native type
        hint for its value but it should be possible to add it based
        on @var annotation "array<int, string>".
    */

    /** @var string $myString */
    private $myString = '';

    /*
        Property \Demo\MySingleton::$myString does not have native type
        hint for its value but it should be possible to add it based
        on @var annotation "string".
    */

    public function __construct()
    {
        $this->myStringArray = [0 => 'foo', 1 => 'bar'];
    }
}
```

<!--
Love PHP Insights? Please consider supporting us via Patreon or OpenCollective:
👉  https://www.patreon.com/nunomaduro
👉  https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=66BYDWAT92N6L
--

**Comment by Jibbarth** [comment]
Hi :wave: 

I think it's the desired comportment. 

Here is the official explanation of the sniff: https://github.com/slevomat/coding-standard#slevomatcodingstandardtypehintspropertytypehint-

When using PHP7.4, this sniff enforce you to use native type, so you should do the following:

```patch
    /** @var array<int, string> $myStringArray */
-    private $myStringArray = [];
+    private array $myStringArray = [];

-    /** @var string $myString */
-    private $myString = '';
+    private string $myString = '';
```

In case you don't want use native type hint, you may configure the sniff with `'enableNativeTypeHint' => false`
