### ISSUE TITLE
Checkstyle report: convert "source" attribute to dot notation format

### ISSUE THREAD

**Issue by dsamburskyi** [nunomaduro/phpinsights#463]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| Library version  | 1.14.0

"source" attribute in checkstyle.xml report is just an insight title, for example `source="Element name minimal length"`.
```
<error severity="error" source="Element name minimal length" line="42"
      message="Variable name &quot;s&quot; is only 1 chars long. Must be at least 3."/>
```

It seems to be a common convention to use a dot notation for the "source" attribute.
Examples:

- Checkstyle repo https://github.com/checkstyle/checkstyle/blob/e09397dab3c24c294e7559aeb28fcd461b9cd9e1/src/test/resources/com/puppycrawl/tools/checkstyle/ant/checkstyleanttask/ExpectedCheckstyleAntTaskXmlOutput.xml#L4
  `source="com.puppycrawl.tools.checkstyle.checks.sizes.LineLengthCheck"`
- PHP_CodeSniffer does similar `source="Squiz.Commenting.FunctionComment.MissingParamComment"`

This impacts different Checkstyle parsing tools to not define the category and type of the error.
Jenkins CheckStyle plugin does the [following](https://github.com/jenkinsci/analysis-model/blob/18a6d7cdb4fa1cb485d36a2f328667f171354102/src/main/java/edu/hm/hafner/analysis/parser/checkstyle/CheckStyleParser.java#L88-L99)
```
    @CheckForNull
    private String getCategory(@CheckForNull final String source) {
        return StringUtils.capitalize(getType(StringUtils.substringBeforeLast(source, ".")));
    }

    @CheckForNull
    private String getType(@CheckForNull final String source) {
        if (StringUtils.contains(source, '.')) {
            return StringUtils.substringAfterLast(source, ".");
        }
        return source;
    }
```
See empty Category on the screenshot
<img width="660" alt="image" src="https://user-images.githubusercontent.com/25210529/110165333-c9eedf00-7dc0-11eb-9b45-4ebd4f370586.png">

It'd be nice to have the source attribute be formatted in a parseable way.
I can try to come up with a PR for this if you decide this is desired change :)

<!--
Love PHP Insights? Please consider supporting us via Patreon or OpenCollective:
👉  https://www.patreon.com/nunomaduro
👉  https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=66BYDWAT92N6L
--

**Comment by Jibbarth** [comment]
Hi @dsamburskyi :wave: 

This seems legit :+1: 

If you can submit a PR, it'll be very appreciated. 

I think we should use `$insight->getInsightClass()` (with backslash transformation in dot) instead of `$insight->getTitle()` in `src/Application/Console/Formatters/Checkstyle.php` and in message, pass `getTitle` in case there is no message. WDYT ?

**Comment by dsamburskyi** [comment]
Thanks for the advise, this saved my time :)
I've submitted https://github.com/nunomaduro/phpinsights/pull/464
