### ISSUE TITLE
Ordered imports may consider function import to be at this end of the import list

### ISSUE THREAD

**Issue by hermann8u** [nunomaduro/phpinsights#465]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| Library version  | 1.14.1

Hi !

When I use function import, for example with the php function method_exists, I get this issue :

```
• [Style] Ordered imports:
  src/Listener/ContainerAwareListener.php:  
@@ -8,0 +8 @@
+use function method_exists;
@@ -10 +11,0 @@
-use function method_exists;
```

The parser expects my function imports to be alphabetically sorted mixed with my classes import. However it's common to put function import after class imports. I think it's in the PSR-12 but can't remember precisely.

I guess it will be a nice feature to have the control on this.

For reference : https://phpinsights.com/insights/style.html#ordered-imports

Thank you for your feedbacks

**Comment by Jibbarth** [comment]
Hi :wave: 

Isn't already the case ? 

This Fixer can be configured : 
![image](https://user-images.githubusercontent.com/3168281/111904236-22bbaa00-8a46-11eb-814b-b521dfaea805.png)

You can see also https://mlocati.github.io/php-cs-fixer-configurator/?#version:2.17|configurator|fixer:ordered_imports

Can you provide a reproducer ?

**Comment by JustSteveKing** [comment]
Question was answered, now stale - documentation improvements could highlight this
