### ISSUE TITLE
VisibilityRequiredFixer on PHP 8 union types

### ISSUE THREAD

**Issue by hwmatthewa** [nunomaduro/phpinsights#466]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| Library version  | dev-master

Suggestion for VisibilityRequiredFixer is incorrect and sniff does not recognize union types correctly.

Minimal code reproduction:
```php
<?php

declare(strict_types=1);

class ExampleBug
{
    private array | null $exampleArray;
}
```

Output:
```
@@ -7 +7 @@
-    private array | null $exampleArray;
+    private array | public null $exampleArray;
```

**Comment by cfinnestad** [comment]
union type defacto standard (99% use case examples) is not to has spaces around the |

private array|string|null $myVar;

public function example(): array|null
{
    return [];
}

PHPInsights still can't handle it in many different rules
* ParameterTypeHintSpacingSniff
* PropertyDeclarationSniff
* BinaryOperatorSpacesFixer (this is not a binary operator but it thinks it is and wants spaces around it)

**Comment by Jibbarth** [comment]
Hi :wave: Thanks for reporting.

However, I think this should reported in [PHP-CS-Fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer) repository.

For space around pipe, you may use [this advice](https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/5495#issuecomment-777187487)

```php
// phpinsights.php

return [
    // ...
    'config' => [
        \PhpCsFixer\Fixer\Operator\BinaryOperatorSpacesFixer::class => [
            'operators' => [
                '|' => null,
            ],
        ],
    ],
]
```

**Comment by Jibbarth** [comment]
Hi :wave: 

The latest version now use PHP-CS-Fixer v3, it seems the initial issue is fixed. I'm closing this issue
