### ISSUE TITLE
Useless variable and empty if statement detection

### ISSUE THREAD

**Issue by RobertEcker** [nunomaduro/phpinsights#468]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request?      | no
| Library version?      | dev-master

```
$sql = <<<SQL
...
SQL;
return $sql;
```

It says "Useless variable $sql."

```
if (
    $result === 'test'
    || ($result === 'test1' && $test === 'abc')
   )
```
It says "Empty IF statement detected"
I guess because of the newline formatting (including 4 spaces)

**Comment by Jibbarth** [comment]
Hi @RobertEcker :wave: 

```
$sql = <<<SQL
...
SQL;
return $sql;
```
The tool is right to say the variable is useless :wink: 

You can do the following : 

```
return <<<SQL
...
SQL;
```
See [example](https://3v4l.org/Z1WH4)

---

```
if (
    $result === 'test'
    || ($result === 'test1' && $test === 'abc')
   )
```
Can you provide your full `if` ? If you `if` has no brace with something in it, I'm afraid that the tool is right again :sweat_smile:
