### ISSUE TITLE
class property visibility false positive

### ISSUE THREAD

**Issue by bitgandtter** [nunomaduro/phpinsights#469]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| Library version  | master

I think there is a false positive on classes using php8 annotations, for example:

```
<?php

declare(strict_types=1);

namespace AppX;

use Symfony\Component\Validator\Constraints\Email;
use Symfony\Component\Validator\Constraints\Length;
use Symfony\Component\Validator\Constraints\NotBlank;

class UserDTO implements DTOInterface
{
    #[Email]
    #[NotBlank]
    public string $email;

    #[NotBlank]
    #[Length(min: 8)]
    public string $password;
}
```

raises `UserDTO.php,line=15::* [Property declaration] Visibility must be declared on property "$email"`

**Comment by Jibbarth** [comment]
Hello @bitgandtter 

I just try with your sample, I don't get the same result. 

It raise to me only unused use.

![image](https://user-images.githubusercontent.com/3168281/115110806-8241a280-9f7d-11eb-8e62-7bc9ddf8919b.png)

However, this issue shouldn't be raise also. I have to check on [slevomat/coding-standard](https://github.com/slevomat/coding-standard) if we can bypass this.

**Comment by JustSteveKing** [comment]
Closing for now, reopen if still causing issue.
