### ISSUE TITLE
Allow same-line braces for empty constructors

### ISSUE THREAD

**Issue by Crell** [nunomaduro/phpinsights#475]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | yes?
| Library version  | 1.14.1

I'm not sure if this is more feature request or bug.  Refile as needed.

With constructor promotion in PHP 8, it's now common to have a constructor with no body.  The most natural way to write that is this:

```php
    public function __construct(
        public ?int $priority,
        public ?string $id = null,
        public ?string $type = null,
    ) {}
```

However, the `PhpCsFixer\Fixer\Basic\BracesFixer` check complains about the curly braces being on the same line.  It wants you to write it like this instead:

```php
    public function __construct(
        public ?int $priority,
        public ?string $id = null,
        public ?string $type = null,
    ) {
    }
```

And... no, I will not say that is an improvement no matter how much you pay me. :smile: 

Can the braces check detect that an empty set of braces does not, in fact, need to be split to multiple lines?  (This likely applies to empty exceptions, too, but I've not hit that yet myself.)

**Comment by Jibbarth** [comment]
Hello @Crell 

You are totally right, this rule become quite annoying on PHP8.

However, this fixer is lead by [PHP-CS-Fixer]() and I didn't find yet a way to disable this brace check on empty constructor... 

For reference, here is all options that we can add to this fixer: https://mlocati.github.io/php-cs-fixer-configurator/?version=2.12#version:2.18|configurator|fixer:braces

You may should remove this rule manually in your `phpinsights.php` for now, sorry about that :sweat_smile:

**Comment by Crell** [comment]
Referred over to the PHP-CS folks, then: https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/5632

**Comment by JustSteveKing** [comment]
PHP CS Fixer is not going to change this, will investigate options further. Closing for now, feel free to reopen if this becomes a priority
