### ISSUE TITLE
Get ready for PHP-CS-Fixer v3

### ISSUE THREAD

**Issue by Jibbarth** [nunomaduro/phpinsights#476]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| Library version  | dev-master

The PHP-CS-Fixer v3 is incoming :tada: 

This issue to check if it can be already used as dependency.

TODO: 

- [ ] Require the beta on local env (see https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/3.0/UPGRADE-v3.md)
- [ ] Check if there is changed fixer definition or deprecated fixer that we already use
- [ ] Check if phpinsights still work :rocket: 
- [ ] Add v3 as dependency in composer.json
- [ ] ...

<!--
Love PHP Insights? Please consider supporting us via Patreon or OpenCollective:
👉  https://www.patreon.com/nunomaduro
👉  https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=66BYDWAT92N6L
--

**Comment by akosglue** [comment]
The first problem is that I cannot install v3.
composer.json updated to:
`"friendsofphp/php-cs-fixer": "^3.0.x-dev",`
then run composer update.
However:

`  Problem 1
    - symplify/easy-coding-standard[9.1.0, ..., 9.2.0] require friendsofphp/php-cs-fixer ^2.17.3 -> found friendsofphp/php-cs-fixer[dev-master, v2.17.3, ..., 2.19.x-dev (alias of dev-master)] but it conflicts with your root composer.json require (^3.0.x-dev).
    - symplify/easy-coding-standard[9.2.1, ..., v9.2.15] require friendsofphp/php-cs-fixer ^2.18.2 -> found friendsofphp/php-cs-fixer[dev-master, v2.18.2, ..., 2.19.x-dev (alias of dev-master)] but it conflicts with your root composer.json require (^3.0.x-dev).
    - symplify/easy-coding-standard[v9.2.16, ..., v9.3.0] require friendsofphp/php-cs-fixer ^2.18.5 -> found friendsofphp/php-cs-fixer[dev-master, v2.18.5, v2.18.6, 2.18.x-dev, 2.19.x-dev (alias of dev-master)] but it conflicts with your root composer.json require (^3.0.x-dev).
    - Root composer.json requires symplify/easy-coding-standard ^9.1 -> satisfiable by symplify/easy-coding-standard[9.1.0, ..., v9.3.0].
`

**Comment by 50bhan** [comment]
@akosglue Yes, you are right. It's because the required version is ^2.0 for now. I believe after the PHP-CS-Fixer releases version 3.0, they will update the version and we are good to go.

**Comment by 50bhan** [comment]
@Jibbarth As you know, they've released the PHP-CS-Fixer v3. Do you think can we update this before the new release? Or even it's a good idea?

**Comment by akosglue** [comment]
I think it is still not installable:

symplify/easy-coding-standard v9.3.1 requires composer/xdebug-handler ^2.0

composer/composer 2.0.13 require composer/xdebug-handler ^1.1

**Comment by Jibbarth** [comment]
Well, simplify is only used in dev-dependency. If their dependencies are too agressive, maybe we can remove it ? Not totally, but install it in an  other place. I'll try to test this this weekend 🤞

**Comment by Jibbarth** [comment]
Well, the last version of symplify/easy-coding-standard replace php-cs-fixer and php-codesniffer. 

![image](https://user-images.githubusercontent.com/3168281/117855059-64b8dd80-b28a-11eb-9d3c-39a1bd7929df.png)


We'll probably remove it :roll_eyes:
