### ISSUE TITLE
[Question] Security issues found on dependencies

### ISSUE THREAD

**Issue by Gabe122** [nunomaduro/phpinsights#485]
How can i resolve this without updating laravel version.

version: Laravel Framework 7.30.4

![image (5)](https://user-images.githubusercontent.com/83697252/117116540-122a7d80-adc1-11eb-8c1d-be07efd6938a.png)

reference: https://github.com/laravel/framework/security/advisories/GHSA-4mg9-vhxq-vm7j

**Comment by nunomaduro** [comment]
That question is not related to PHP Insights.

**Comment by Gabe122** [comment]
but running php insights give me this security issue. is there any workaround in insights to resolve this?

**Comment by nunomaduro** [comment]
No - you need to update.

**Comment by 50bhan** [comment]
@Gabe122 It seems you're using Laravel v7.30.4. So, `PhpInsights` is complaining about the security issue. So, as @nunomaduro said, in order to get rid of this message, you need to update your Laravel (actually to be safe).
