### ISSUE TITLE
SyntaxCheck insight isn't excluding files correctly

### ISSUE THREAD

**Issue by dshoreman** [nunomaduro/phpinsights#486]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| Library version  | dev-master

## Update

**This issue is mostly a fault-finding log at this point; for a tl;dr, check the related PR: #487.**

### Original text

I recently added phpinsights to the arsenal of CS/SA tools in my project, using the `laravel` preset in my config.

When I run phpinsights, I get this false positive on **_ide_helper.php**, which is excluded by the preset:
```
• [Style] Syntax Check: (NunoMaduro\PhpInsights\Domain\Insights\SyntaxCheck)
  ./_ide_helper.php:18832: PHP syntax error: Cannot use Illuminate\Support\Arr as Arr because the name is already in use
```

I tried adding '_ide_helper.php' to my own `exclude` array, but with that making no difference I dumped `$cmdLine`:
```
/usr/bin/php '/path/to/vendor/bin/parallel-lint' --no-colors \
   --no-progress --json --exclude 'vendor' --exclude 'tests' \
   --exclude 'Tests' --exclude 'test' --exclude 'Test' .
```

...so *some* things are excluded, but not all.

My next attempt was using the insight's `exclude` option:
```
'config' => [
    SyntaxCheck::class => [
        'exclude' => ['_ide_helper.php'],
    ],
],
```
...which *did* add an extra `--exclude` arg, but with the *fully resolved* path which parallel-lint doesn't understand.

---

I don't have time to dig deeper right now, but the issue seems to lie somewhere in setting `$this->excludedFiles`:
https://github.com/nunomaduro/phpinsights/blob/d4f92e93a2a5ddf90664eb6a4cb9d159440abbcf/src/Domain/Insights/SyntaxCheck.php#L40-L43

**Comment by 50bhan** [comment]
@dshoreman I think the way you're using the exclude is not quite right. Can you please use this way:

```
    'exclude' => [
        //  'path/to/directory-or-file'
    ],
```

Doc: https://phpinsights.com/insights/#configure-insights

**Comment by dshoreman** [comment]
@50bhan That's what I tried first, but it doesn't get picked up. Only the fully-resolved insight-specific excludes are included in `$this->excludedFiles`, not ones from the root-level exclude list.

That said, manually excluding it shouldn't be required, because it's already excluded in the preset on line 39:
https://github.com/nunomaduro/phpinsights/blob/d4f92e93a2a5ddf90664eb6a4cb9d159440abbcf/src/Application/Adapters/Laravel/Preset.php#L30-L43

**Comment by dshoreman** [comment]
Now that I think about it, there could actually be two bugs here:

1. `root.exclude` items aren't passed at all because they're missing from `$this->excludedFiles`
2. `config.<SyntaxCheck::class>.exclude` items *are* passed, but as full paths where parallel-lint expects relative ones

**Comment by dshoreman** [comment]
@50bhan I'm digging into this atm, and the issue seems to be introduced by the [large project patch][1] in #437.

Prior to that patch, the command didn't use `--exclude`, but passed the entire list of **filtered files** to be scanned. That resulted in arg lists that were too long, so naturally it was inverted.

Now that it's "opt-out", the filtered file list is no longer used. I've just figured out a patch for that part so I'll fork and PR shortly, but the resolved paths would still be an issue if someone ever tried to use that.

Sorry for the spam!

[1]: https://github.com/nunomaduro/phpinsights/commit/6790309f35db1619aac198c25897a40e7e473d70#diff-e6762b772abf220ab4ea67e9373cc8bbb3d3ac0d79bbe951ff6a6216b093b131
