### ISSUE TITLE
maxLinesLength seems to be ignored for sniff FunctionLengthSniff

### ISSUE THREAD

**Issue by osteel** [nunomaduro/phpinsights#488]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| Library version  | master ([85a5670](https://github.com/nunomaduro/phpinsights/commit/85a5670ab2492cfe489eff23b5a14d4c9364ac3f))

I'm using the `SlevomatCodingStandard\Sniffs\Functions\FunctionLengthSniff` for which I set a custom value like this:

```
FunctionLengthSniff::class => [
    'maxLinesLength' => 30,
],
```

But the analysis still uses the default value (20):

```
[Architecture] Function length:
app/Models/Image.php:26: Your function is too long. Currently using 33 lines. Can be up to 20 lines.
```

**Comment by 50bhan** [comment]
@osteel Thank you for reporting this. Already opened a PR for fixing this.
