### ISSUE TITLE
PHP Warning:  Undefined array key "scope_closer" in vendor\slevomat\coding-standard\SlevomatCodingStandard\Helpers\UseStatementHelper.php on line 195

### ISSUE THREAD

**Issue by RobertEcker** [nunomaduro/phpinsights#493]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| Library version  | master

Still have
PHP Warning:  Undefined array key "scope_closer" in vendor\slevomat\coding-standard\SlevomatCodingStandard\Helpers\UseStatementHelper.php on line 195

if using "match" in source code
```
        $result = match ($match) {
            0 => 'a',
            default => 'b',
        };
```
also

Useless parentheses for "`$result = match ($match) {`" - not sure why

**Comment by Jibbarth** [comment]
Hi ! I just tested with your reproducer, I'm not able to reproduce. Do you have any hint ? 

![Peek 25-05-2021 19-19](https://user-images.githubusercontent.com/3168281/119553905-5e535700-bd9c-11eb-80e1-7e24b2ddd69c.gif)

**Comment by RobertEcker** [comment]
[test.php.txt](https://github.com/nunomaduro/phpinsights/files/6542248/test.php.txt)

hi :), a minimum examples - without trait it works (thought it is cause of match - maybe i will find also another example)

**Comment by JustSteveKing** [comment]
Couldn't reproduce, changes in third part code standards causing issues - there will be an investigation into how we approach this.
