### ISSUE TITLE
Add support for "Code Climate" format output (GitLab.com Code Quality)

### ISSUE THREAD

**Issue by guywarner** [nunomaduro/phpinsights#495]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| Library version  | 2.0

Add a new format for output `codeclimate`. While not used a lot, it's the format required to use the Code Quality widget in GitLab.com. 

https://github.com/codeclimate/platform/blob/master/spec/analyzers/SPEC.md#data-types

While gitlab.com only requires a few of the fields, it'd be nice to have them all for future integrations.

Gitlab example
```
[
  {
    "description": "'unused' is assigned a value but never used.",
    "fingerprint": "7815696ecbf1c96e6894b779456d330e",
    "severity": "minor",
    "location": {
      "path": "lib/index.js",
      "lines": {
        "begin": 42
      }
    }
  }
]
```

Per Code Quality docs they have the following fields available:

```
type -- Required. Must always be "issue".
check_name -- Required. A unique name representing the static analysis check that emitted this issue.
description -- Required. A string explaining the issue that was detected.
content -- Optional. A markdown snippet describing the issue, including deeper explanations and links to other resources.
categories -- Required. At least one category indicating the nature of the issue being reported.
location -- Required. A Location object representing the place in the source code where the issue was discovered.
trace -- Optional. A Trace object representing other interesting source code locations related to this issue.
remediation_points -- Optional. An integer indicating a rough estimate of how long it would take to resolve the reported issue.
severity -- Optional. A Severity string (info, minor, major, critical, or blocker) describing the potential impact of the issue found.
fingerprint -- Optional. A unique, deterministic identifier for the specific issue being reported to allow a user to exclude it from future analyses
```

In 2019 phpstan added it (https://github.com/phpstan/phpstan/pull/2381). 

From a quick glance at things, it appears to be adding a new Formatter in the style of the JSON one. The one issue I could see to not add it is that it would require some kind of hashing for the fingerprint which isn't required for Code Quality but is required for GitLab. PHPStan solved it by requiring hash in the composer-require. Then just using:

```
'fingerprint' => hash(
					'sha256',
					implode(
						[
							$fileSpecificError->getFile(),
							$fileSpecificError->getLine(),
							$fileSpecificError->getMessage(),
						]
					)
				),
```

If this is something that makes sense in this project, I'd more than love to open a PR for it and test it in the wild with our apps hosted on Gitlab.

**Comment by Jibbarth** [comment]
That would be an awesome new feature ! 
For the fingerprint, a md5 should work or it has to be in sha256 ? As we already use md5, I think there is no need to add `hash` in composer require.

Do you need some help to implement the new formatter ?

**Comment by guywarner** [comment]
md5 would be fine for the hash. I'll get a PR up shortly!
