### ISSUE TITLE
A removed fixable sniff is being fixed when running `phpinsights fix`

### ISSUE THREAD

**Issue by adrianb93** [nunomaduro/phpinsights#499]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| Library version  | master (2.0)

I am using the Laravel adapter with the `config/insights.php` config. I removed the `DeclareStrictTypes` sniff which works for linting/analysing:

```
<?php

...
use SlevomatCodingStandard\Sniffs\TypeHints\DeclareStrictTypesSniff;
...

return [
    'preset' => 'laravel',
    ...
    'remove' => [
        ....
        DeclareStrictTypesSniff::class,
        ...
    ],
    ...
];
```

When I run `vendor/bin/phpinsights fix`, it is adding `declare(strict_types=1);` to all my files.

Given I removed the "fixable" `DeclareStrictTypesSniff` sniff, I expected the fix command would not have run that fix.

Should the fix command be taking into account the configuration? Or did I miss something in the v2 documentation?

**Comment by Jibbarth** [comment]
When you use `vendor/bin/phpinsights fix`, it looks for a `phpinsights.php` config file at the root. 

To use it with your config file, you have to pass it the path : 

```
vendor/bin/phpinsights fix --config-path=config/insights.php
# or 
php artisan insights --fix
```
