### ISSUE TITLE
Distribute through phive

### ISSUE THREAD

**Issue by szepeviktor** [nunomaduro/phpinsights#5]
in a PHAR file phpinsights would not conflict with the project's deps

https://github.com/phar-io/phive

**Comment by nunomaduro** [comment]
No plans at the moment.

**Comment by szepeviktor** [comment]
@nunomaduro I'm very sad.

Modern PHP tools **tend** to go PHAR-only, e.g. PHPStan

There would be only these steps:

- add 1 phive config
- release process: add a phar file
- release process: add a GPG signature

What do you think?

**Comment by nunomaduro** [comment]
It’s a good idea.

It’s just I don’t have plans to do it in the next weeks.

Let’s reconsider this.

**Comment by mihai-stancu** [comment]
@nunomaduro regarding the help wanted tag, I'm guessing this would mean implementing the necessary configuration for `humbug/box` building the phar itself, signing it and implementing the necessary `phive` configuration?

Do you forsee anything else? Automated build steps to be added? The signature would still need your manual input as far as I can imagine.

I haven't done this before but i'd give it a shot.

**Comment by szepeviktor** [comment]
@mihai-stancu If you get Box working I'll add the rest.

**Comment by mihai-stancu** [comment]
Conundrum:
- `php-scoper` moves every class into a unique namespace
- `./you-project/phpinsights.php` -- (the configuration file) references the original class names to add / remove metrics and sniffs et.al..

I need to find a way to fetch the current `php-scoper` unique namespace root, and to try to prefix everything in the config file with it.

**Comment by szepeviktor** [comment]
Why do we need `php-scoper`?

**Comment by nunomaduro** [comment]
Let's re-open this issue, eventually if someone decides to work on this.

**Comment by JoyceBabu** [comment]
> Let's re-open this issue, eventually if someone decides to work on this.

@nunomaduro Did you really intend to close this?
