### ISSUE TITLE
Please introduce AWS CodeBuild-compatible report formats

### ISSUE THREAD

**Issue by AdamMarton** [nunomaduro/phpinsights#500]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| Library version  | TBD

Would be great to have any of the formats supported by PHPInsights [listed here](https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html#build-spec.reports.file-format).

I'll happily contribute too, if possible.

**Comment by Jibbarth** [comment]
Hello :wave: 

Any idea which report should be the best ? 

You can grab information from the issue #495 (and related PR #498) which integrate a new formater for codeclimate if you want to contribute :slightly_smiling_face:
