### ISSUE TITLE
Question: Is there a way to apply phpinsights only over modified code?

### ISSUE THREAD

**Issue by federf** [nunomaduro/phpinsights#503]
Hi. I'm trying to integrate PHP Insights into our CI and I'm having a hard time trying to apply the library only over modified code.

I've only managed to limit the execution to modified files but we have some pretty old legacy code that might be troublesome to refactor as of now and would like to avoid checking the whole file in those cases.

Is there a way to limit the execution of the library only over the modified lines?

Thanks in advance

**Comment by 50bhan** [comment]
@federf I believe there is no way at the moment with the tool. But you can use a script to get a diff between your branches and then pass that list of files to the `analyse` command in `PhpInsights`:

https://phpinsights.com/get-started.html#analyse-multiple-paths

**Comment by federf** [comment]
@50bhan thanks for replying. that's actually what im doing right now. I made this script to get and process every modified php file on its own.

```
files=$(git diff origin/master... --name-only -- '*.php')

for file in $files; do
    echo "\n"
    echo $file

    if ! php -d memory_limit=-1 ./vendor/bin/phpinsights --no-interaction --min-quality=80 --min-complexity=80 --min-architecture=80 --min-style=80 analyse $file
    then
        exit 1
    fi
done
exit 0;
```

It works fine but I still need to find a way to "limit" the code evaluation to only the modified lines for "legacy code" files.

**Comment by 50bhan** [comment]
@federf Ah OK. I think it's not possible for `PhpInsights` to work on line level. Because it's a wrapper around different tools and those tools are working on file level. Although there are some ways to work around this on some of those tools, but I believe it's not possible to use them with `PhpInsights`.

**Comment by Jibbarth** [comment]
I'm closing this issue, @50bhan answered right.

May be our next step will be to add a "baseline" to exclude some already raised issues, like on `phpstan`
