### ISSUE TITLE
Wrong namespace in documentation FunctionLengthSniff

### ISSUE THREAD

**Issue by hdcore** [nunomaduro/phpinsights#506]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| Library version  | 2.0.0

The documentation for "Architecture / Function length" contains the bad namespace part "Files" instead of "Functions"  for the Insight Class v2.0 line. In #489 the configuration line was already corrected.

**Comment by 50bhan** [comment]
@hdcore Hah! I must forget this one 😄  Thank you for reporting this!

**Comment by Jibbarth** [comment]
Thank you for reporting, fixed in #507 👌
