### ISSUE TITLE
Logic Exception unable to find data within Laravel project

### ISSUE THREAD

**Issue by longestdrive** [nunomaduro/phpinsights#511]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| Library version  | 2.0

HI
I'm using php insights for the first time. I've installed the package within my Laravel project and published the config file.

On first run I get this error:
```
 LogicException 

  Unable to find data for /home/vagrant/code/wedleague/app/Http/Controllers/Admin/RoleController.php

  at vendor/nunomaduro/phpinsights/src/Domain/Runner.php:184
    180â–•     {
    181â–•         $cacheKey = 'insights.' . $this->cacheKey . '.' . md5($file->getContents());
    182â–•         // Do not use cache if fix is enabled to force processors to handle it
    183â–•         if (! $this->cache->has($cacheKey)) {
  âžœ 184â–•             throw new \LogicException('Unable to find data for ' . $file->getPathname());
    185â–•         }
    186â–• 
    187â–•         $this->loadDetailsCache($cacheKey);
    188â–• 

      +4 vendor frames 
  5   [internal]:0
      NunoMaduro\PhpInsights\Domain\Insights\InsightCollectionFactory::NunoMaduro\PhpInsights\Domain\Insights\{closure}()

      +17 vendor frames 
  23  artisan:35
      Illuminate\Foundation\Console\Kernel::handle()
```

I'm not sure where to start working out what's gone wrong. The controller exists - what does this error mean? 

Sorry for vague question.

Running on a vagrant machine with homestead php7.4 if that's any help.

Any pointers appreciated

Thank you

<!--
Love PHP Insights? Please consider supporting us via Patreon or OpenCollective:
👉  https://www.patreon.com/nunomaduro
👉  https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=66BYDWAT92N6L
--

**Comment by thanosalexander** [comment]
same situation @longestdrive . I receive same error for an existing file. Someone to help?

**Comment by 50bhan** [comment]
@longestdrive @thanosalexander Could you please provide a code sample to reproduce the issue?

**Comment by thanosalexander** [comment]
I realised when i comment out this function
![image](https://user-images.githubusercontent.com/6491808/123589399-d674c880-d7f1-11eb-905f-772a7bc1becf.png)
inside BaseCryptModel
then it passes!

**Comment by 50bhan** [comment]
@thanosalexander Is it your namespace? `//app/app/Logic/Base/BaseCryptModel.php`? And how did you called the `PhpInsights` when you got the error? Using Laravel artisan command or `analyse`?

**Comment by thanosalexander** [comment]
i use docker (lando specifically) and app's root lives in `/app`
I use insights with `php artisan insights` command in Laravel. (maybe i'll try analyze later)

**Comment by 50bhan** [comment]
@thanosalexander Thank you for your feedback. I think the problem might be related to another issue: #509. Because of this, we have a problem when the path is `/app`. But I already opened a PR for it: #509.

**Comment by thanosalexander** [comment]
nice @50bhan , thank you!
So do you think the problem is on directory path structure instead of this `DB::statement(sprintf("SET @AESKEY = '%s'", $key));` line? Because when i comment it out it works!

**Comment by 50bhan** [comment]
@thanosalexander That's weird 😄  But I'm sure that we have this problem with `/app`. And by the way, I couldn't reproduce the issue, so I believe it happens because of this directory path.

**Comment by thanosalexander** [comment]
got it.. so we'll be waiting till next commit to be fixed!

**Comment by longestdrive** [comment]
Hi - I fixed my issues by making some edits to the file where that failed - some just editing the dependancies, others just adding or editing a comment. Use of `php artisan insights` then failed on another file - I kept going through appx 20 files and then it now works ok
I did a dump-autoload at one point and wonder if there is a cache or similar that insights is pulling from?

**Comment by 50bhan** [comment]
@longestdrive Of course we have cache on `PhpInsights` right now. Now I'm wondering if this error is related to the cache or something else.

**Comment by AntonLugtenburg** [comment]
I get the same error no matter which file im checking - on laravel and php 8, also in new Project...

**Comment by wiklog** [comment]
In my case it's because some files are in Windows mode (crlf) not linux (lf). I applyed a dos2unix command to fix the error

**Comment by billypoke** [comment]
Pinning `friendsofphp/php-cs-fixer` at `3.9.5` worked for me as a temporary solution. `3.9.6` and `3.10.0` are both giving the error

**Comment by billypoke** [comment]
@M1Screw sure thing. I had run a composer update only a few minutes before, and thankfully that was the only package that was updated so it was easy to backtrack to the problem

**Comment by pkarastelev** [comment]
> @M1Screw sure thing. I had run a composer update only a few minutes before, and thankfully that was the only package that was updated so it was easy to backtrack to the problem

This worked for me. Thanks!

**Comment by eta-orionis** [comment]
I also confirm that pinning friendsofphp/php-cs-fixer at 3.9.5 solves the problem
(running on normal filesystem, no /app or docker)

**Comment by jeremyFreeAgent** [comment]
I also confirm that pinning friendsofphp/php-cs-fixer at 3.9.5 solves the problem.

**Comment by trianity** [comment]
I also confirm that pinning friendsofphp/php-cs-fixer at 3.9.5 solves the problem.

**Comment by pelmered** [comment]
I still have this problem with friendsofphp/php-cs-fixer at `v3.10.0` and PHPInsights at `"v2.4.0`

```
php artisan insights  --flush-cache

 848/848 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%

   LogicException

  Unable to find data for /***/phpinsights.php

  at vendor/nunomaduro/phpinsights/src/Domain/Runner.php:184
    180▕     {
    181▕         $cacheKey = 'insights.' . $this->cacheKey . '.' . md5($file->getContents());
    182▕         // Do not use cache if fix is enabled to force processors to handle it
    183▕         if (! $this->cache->has($cacheKey)) {
  ➜ 184▕             throw new \LogicException('Unable to find data for ' . $file->getPathname());
    185▕         }
    186▕
    187▕         $this->loadDetailsCache($cacheKey);
    188▕

      +4 vendor frames
  5   [internal]:0
      NunoMaduro\PhpInsights\Domain\Insights\InsightCollectionFactory::NunoMaduro\PhpInsights\Domain\Insights\{closure}("PHP_CodeSniffer\Standards\Generic\Sniffs\CodeAnalysis\UnnecessaryFinalModifierSniff")

      +17 vendor frames
  23  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
```

**Comment by cAstraea** [comment]
Getting consistent errors like this across all my projects
   LogicException 

  Unable to find data for /Users/***/Sites/***-ip-api/routes/admin/auth.php

  at vendor/nunomaduro/phpinsights/src/Domain/Runner.php:184
    180▕     {
    181▕         $cacheKey = 'insights.' . $this->cacheKey . '.' . md5($file->getContents());
    182▕         // Do not use cache if fix is enabled to force processors to handle it
    183▕         if (! $this->cache->has($cacheKey)) {
  ➜ 184▕             throw new \LogicException('Unable to find data for ' . $file->getPathname());
    185▕         }
    186▕ 
    187▕         $this->loadDetailsCache($cacheKey);

**Comment by tj-a** [comment]
The issue seems to be caused by the presence of the `@` char (for whatever reason) in scanned PHP scripts. Removing this character appeared to resolve the issue for me.

**Comment by ITMobilityControl** [comment]
> Still experiencing this issue. None of the above solutions worked for me. Ended up just commenting out lines 183 - 185 in vendor/nunomaduro/phpinsights/src/Domain/Runner.php to allow for the report to be fully generated.
> 
> ```
> // if (! $this->cache->has($cacheKey)) {
> //     throw new \LogicException('Unable to find data for ' . $file->getPathname().'. $file='.var_export($file, true). ':: $cacheKey='.var_export($cacheKey, true).' :: $this->cacheKey='.$this->cacheKey.' :: $file->getContents()='.$file->getContents());
> // }
> ```

Worked as a temporary fix for me!

**Comment by XedinUnknown** [comment]
Is this really closed with a temporary fix that requires editing files in `vendor`? :/

**Comment by XedinUnknown** [comment]
So, I dug around the code, and the most sane solution seems to be exactly what the comment says yet the code doesn't do: skip the cache check if in fix mode.

Until this is merged, you can use the [PR's patch](https://patch-diff.githubusercontent.com/raw/nunomaduro/phpinsights/pull/682.patch) with https://github.com/cweagans/composer-patches, meaning that it's now safe to distribute solutions based on this fix with your project - without people having to modify their `vendor` by hand.

**Comment by XedinUnknown** [comment]
Ok, so the symptoms are now happening to me regardless of whether I'm fixing or just analysing. What seems to be the problem here? It's a cache miss, OK. In which case, cache should be re-generated and then subsequently used, no? How can I auto-fix my code? As every file seems to be throwing this now.
