### ISSUE TITLE
Visibility required vs. Syntax Check

### ISSUE THREAD

**Issue by RobertEcker** [nunomaduro/phpinsights#512]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| Library version  | master

Given:
`private array | null $request;`

**[Code] Visibility required:**

(-)    private array | null $request;
(+)   private array | public null $request;

I change it to:
`private array | public null $request;`

**[Style] Syntax Check:**

- PHP syntax error: syntax error, unexpected token "public"

So whatever I do It shows an error.

**Comment by Jibbarth** [comment]
:wave: It seem related to #466 

Can you check if the PHP-CS-Fixer version used is the v3 ?

**Comment by RobertEcker** [comment]
👋 i installed it from scratch and it is working now :) thanks
