### ISSUE TITLE
InvalidArgumentException when initially doing composer require... 

### ISSUE THREAD

**Issue by tshubbard** [nunomaduro/phpinsights#513]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| Library version  | master

I just tried to run `composer require nunomaduro/phpinsights --dev` and I'm getting the following error:

```
  [InvalidArgumentException]
  Could not find a matching version of package nunomaduro/phpinsights. Check the package spelling, your version constraint and that the package is available in a stability which matches your minimum-stability (stable).
```

I am using 
PHP: 7.4.12
composer: 2.1.3

I have seen from some other posts that PHPUnit 9.0+ is required and I am using 9.5. 

Any ideas? Thanks!

**Comment by 50bhan** [comment]
@tshubbard Just installed `PhpInsights` without any problem based on your mentioned configuration:
![Uploading Screen Shot 2021-06-28 at 23.54.57.png…]()

**Comment by tshubbard** [comment]
ah my bad... after looking thru the composer.json there was a block in repositories for 
```
"repositories": [
   {
      "packagist.org": false
   },
```
that is what was messing this up. old codebase troubles... Thanks!
