### ISSUE TITLE
Undefined constant 'T_MULTIPLY' when trying to remove a PHP_CodeSniffer Sniff via configuration file

### ISSUE THREAD

**Issue by SlyDave** [nunomaduro/phpinsights#517]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| Library version  | 2.0.1

'preset' => 'laravel',

adding `\PHP_CodeSniffer\Standards\PSR2\Sniffs\Classes\PropertyDeclarationSniff::class` to remove section of configuration results in 

Undefined constant 'T_MULTIPLY'

  at vendor\nunomaduro\phpinsights\src\Domain\InsightLoader\SniffLoader.php:29

I'm looking to disable the `There must be 1 space after the property type declaration;` sniff, but it appears to be bundled in with all the PropertyDeclarationSniff stuff, and I can't see a way to just disable that one check?

**Comment by 50bhan** [comment]
@SlyDave Unfortunately There is no way to remove a specific part of a sniff. So, if you don't want this check, you have to remove the entire sniff.

**Comment by SlyDave** [comment]
That's what I expected, it'd be good to get those sniffs broken down into more granular sniffs for better control.

and unfortunately it doesn't stop the fact that attempting to disable the whole sniff causes the error mentioned above. 😢

**Comment by stayallive** [comment]
Adding `PHP_CodeSniffer\Standards\PSR2\Sniffs\Classes\PropertyDeclarationSniff::class,` to the `remove` section causes that error, it is also listed here as just that: https://phpinsights.com/insights/code.html#property-declaration.

What else could be disabled that includes this one causing the error?

**Comment by Jibbarth** [comment]
Removing this rule make that the file `PHP_CodeSniffer\Util\Tokens` is never used. 

As this file define lot of Token, others sniff are break. 

A workaround would be to force call `(new Token())` inside the SniffLoader, or we have to find a way to always integrate it.

**Comment by JustSteveKing** [comment]
Closing as PRs are open

**Comment by lengjunbin-trec** [comment]
I checked `v2.2.0` kernel.php doesn't have this fixed.error happened.
@JustSteveKing 
![image](https://user-images.githubusercontent.com/61955063/188039680-2ab161c5-e4a3-4bba-8fd1-fa90074290d5.png)
