### ISSUE TITLE
Laravel configuration reports the laravel way of doing things as an issue...

### ISSUE THREAD

**Issue by SlyDave** [nunomaduro/phpinsights#518]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| Library version  | 2.0.1

    'preset' => 'laravel',

default laravel configuration reports "Do not use public properties. Use method access instead." for $incrementing, $timestamps, $preventsLazyLoading, $exists, $wasRecentlyCreated, $timestamps, $snakeAttributes, $encrypter, $timestamps - which is not idiomatic for laravel.

**Comment by alvarezmario** [comment]
Any updates on this? I wanted to add this awesome library to my project, but I'm getting the same errors as @SlyDave. It'll be awesome to get them solved before installing the library

**Comment by nunomaduro** [comment]
Sure - @alvarezmario @SlyDave can you try to solve those issues?

**Comment by 50bhan** [comment]
@SlyDave @alvarezmario @nunomaduro I believe there is no way to ignore specific variables with this sniff. We can only remove it from the Laravel preset.

```
    'remove' => [
        ForbiddenPublicPropertySniff::class,
    ],
```

**Comment by SlyDave** [comment]
That's not ideal, Should it not be possible to determine if the class being inspected extends Model and test the properties against the list of public properties in Model ignoring them if they match. Yes I understand it'll need specific Laravel sniffs. But without that the Laravel preset is useless no?

**Comment by 50bhan** [comment]
@SlyDave Yes, it's not ideal but at the moment we have no other choice but to remove it. And Laravel preset is just a boilerplate for assigning specific sniffs to a Laravel project and nothing more.

**Comment by JustSteveKing** [comment]
Sounds like the preset for Laravel caused the original issue, but it also limited. Will need to investigate how we run sniffs to see if we can create custom overrides? Closing for now, but will happily reopen should we need to.

There is a lot to go through with this library now with new PRs and changes that are in planning. Documentation on creating custom sniffs might be a good use of time here @cmgmyr ?

Will close this for now, and move this conversation over to our internal chat on how we can approach

**Comment by cmgmyr** [comment]
@JustSteveKing agreed about the documentation here. We might be able to eventually make custom sniffs that are more specific to Laravel too
