### ISSUE TITLE
Wrong 'unused function parameter' issue

### ISSUE THREAD

**Issue by VladimirBerezkin** [nunomaduro/phpinsights#52]
Hi, Nuno! Great package, congrats with release! 
I think I found a minor bug when using compact() function in controllers in Laravel, here is the example from BlogPostController:
```php
public function show(PublishedBlogPost $blogPost)
{
   return view('blog.post', compact('blogPost'));
}
```

Issue that insights give me:
```
[Code] Unused function parameter:
app/Http/Controllers/BlogPostController.php:28: The method parameter $blogPost is never used
```

**Comment by olivernybroe** [comment]
@VladimirBerezkin This has been fixed now, thank you for reporting this! 

The issue was that we were using to sniffs to check for unused parameters and one of them did not support compact methods.
