### ISSUE TITLE
A failing security check inside a GitLab pipeline does not return a error message

### ISSUE THREAD

**Issue by jonassiewertsen** [nunomaduro/phpinsights#520]
| Q                | A
| ---------------- | -----
| Bug report?      | maybe
| Feature request? | yes
| Library version  | 2.0.1

If running inside a GitLab Pipeline and failing the Security Check, no error message will be shown. 
It will simply exit without any further information.

![Screenshot 2021-07-23 at 17 32 24](https://user-images.githubusercontent.com/38906163/126805908-001d5879-549f-4ecd-9f08-5e69f9e4bb3e.png)

Is this expected behavior (maybe for security reasons)?

**Comment by guywarner** [comment]
Can you provide any code that fails the security? Using it on GitLab and not experiencing this.

**Comment by jonassiewertsen** [comment]
You are getting error messages if a security check fails @guywarner ?

**Comment by guywarner** [comment]
They aren't, but I think that'll be fixed in the next release (you can try using master and see).

But, you can download the Artifact from GitLab and open the codeclimate json and search for security to see what the issue is being reported.

**Comment by JustSteveKing** [comment]
Closing as issue has gone stale. If this issue still persists we will investigate the reporting of these issue to see what improvements are needed.
