### ISSUE TITLE
Version conflict with psr/cache v3

### ISSUE THREAD

**Issue by mikemand** [nunomaduro/phpinsights#522]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| Library version  | 2.0.1

Trying to install PHP Insights into a project that already has `psr/cache` installed at v3 causes Composer to complain. It appears that `symfony/cache`, which this package relies on, locks `psr/cache` to `^1.0|^2.0`. It looks like I already have `doctrine/annotations:^1.13.1` installed in my project (which doesn't limit which version of `psr/cache` to use), which is in turn required by PHP-CS-Fixer, and (oddly) `symfony/routing`.

Maybe this is an issue for `symfony/cache` instead, but I figure this would be a good place to start.

A very simple fix for anyone else that has this problem but still wants to use PHP Insights: `composer require --dev --with-all-dependencies nunomaduro/phpinsights` - which should automatically downgrade `psr/cache` to v2 for you. If that doesn't work, simply require `psr/cache:^2.0` and then install this package.

**Comment by tuarrep** [comment]
On my side `psr/cache` is a dependency required by `php-cs-fixer` (through `doctrine/annotations`) too.

I've installed `nunomaduro/phpinsight` with `--with-all-dependencies` flag and my `php-cs-fixed` still works.

**Comment by LocalHeroPro** [comment]
Update psr/simple-cache to v3 from v1 (2017 year)

```bash
$ composer require psr/simple-cache
Using version ^3.0 for psr/simple-cache
./composer.json has been updated
Running composer update psr/simple-cache
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires nunomaduro/phpinsights ^2.1 -> satisfiable by nunomaduro/phpinsights[v2.1.0].
    - nunomaduro/phpinsights v2.1.0 requires psr/simple-cache ^1.0 -> found psr/simple-cache[1.0.0, 1.0.1] but it conflicts with your root composer.json require (^3.0).


Installation failed, reverting ./composer.json to its original content.
```
or
```bash
$ composer outdated
Color legend:
- patch or minor release available - update recommended
- major release available - update possible
psr/simple-cache 1.0.1 3.0.0 Common interfaces for simple caching
```

**Comment by JustSteveKing** [comment]
It sounds like circular dependencies are causing an issue. One of the upcoming tasks is to assess dependencies and see how we can handle these - so closing for now for further investigation.

**Comment by f-lombardo** [comment]
It seems I'm exeperiencing the opposite problem. I use psr/simple-cache v 2.0 and I'm getting this error:
```
Fatal error: Uncaught LogicException: psr/simple-cache 3.0+ is not compatible with this version of symfony/cache. Please upgrade symfony/cache to 6.0+ or downgrade psr/simple-cache to 1.x or 2.x. in /var/www/symfony/vendor/symfony/cache/Psr16Cache.php:23
```
