### ISSUE TITLE
CodeClimate report has correct format?

### ISSUE THREAD

**Issue by Lootjs** [nunomaduro/phpinsights#526]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| Library version  | 2.0.1

How phpinsights generate report now:
```json
{
    "checkname": "PhpCsFixer\\Fixer\\Whitespace\\NoWhitespaceInBlankLineFixer",
    "description": "@@ -15,3 +15,3 @@\n     {\n-        \n+\n     }",
    "fingerprint": "4e554182dabc87569a0250f6fc23165a",
    "location": {
      "path": "Providers/AppServiceProvider.php",
      "lines": {
        "begin": null
      }
    },
    "category": "Style"
  }
```
And CodeClimate spec (https://github.com/codeclimate/platform/blob/master/spec/analyzers/SPEC.md#data-types) requires:

1. **check_name**. not checkname
2. **content** field
3. **categories**, not **category**. And field must be array

**Comment by 50bhan** [comment]
@Lootjs Could you please provide a fix for this? As I'm personally not an expert at CodeClimate.

**Comment by guywarner** [comment]
I'll have a fix-up tomorrow.
