### ISSUE TITLE
Unable to locate publishable resources.

### ISSUE THREAD

**Issue by jrean** [nunomaduro/phpinsights#528]
After a fresh install,
- "nunomaduro/phpinsights": "^2.0"

As stated in the documentation:
- `php artisan vendor:publish --provider="NunoMaduro\PhpInsights\Application\Adapters\Laravel\InsightsServiceProvider"`

Outputs:

```
Unable to locate publishable resources.
Publishing complete.
```

**Comment by guywarner** [comment]
Ran that command and got:

```
php artisan vendor:publish --provider="NunoMaduro\PhpInsights\Application\Adapters\Laravel\InsightsServiceProvider"
Publishing complete.
```

Maybe try composer update and try again?
