### ISSUE TITLE
--fix introduce bugs of static properties

### ISSUE THREAD

**Issue by lloricode** [nunomaduro/phpinsights#529]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| Library version  | 2.0.1

Hi @nunomaduro , i found this with `--fix`, just notice this when running check by phpstan/larastan

![Screenshot from 2021-08-27 09-19-25](https://user-images.githubusercontent.com/8251344/131056385-95f57d7e-7b64-4d78-8753-7c70c1706e7f.png)

Thank you

**Comment by Jibbarth** [comment]
Hey @lloricode, thanks for reporting.  

This rules is provided by Slevomat\CodingStandard (https://github.com/slevomat/coding-standard#slevomatcodingstandardcontrolstructuresdisallowshortternaryoperator-), so I think you should create an issue there.

**Comment by lloricode** [comment]
Thank you
