### ISSUE TITLE
Missing docs on configure Insights in phpinsights.php

### ISSUE THREAD

**Issue by viezel** [nunomaduro/phpinsights#53]
First of all: Great product!!

im trying to configure the `phpinsights.php` but missing  docs on how to configure built in insights?

e.g. I dont want a space after NOT operator. 
`if (!in_array(...))` should be `if (! in_array(...))`

So docs on how to disable it.

**Comment by pxgamer** [comment]
You should be able to add `SpaceAfterNotSniff::class` to the `remove` key in your config.

I agree it would be good to document this too (it is mentioned in the [`phpinsights.php`](https://github.com/nunomaduro/phpinsights/blob/78ed2bca258cdff74aa1ed3a5d0c57ccc019fbfc/phpinsights.php#L40) file, but it could perhaps do with some more clarity in the docs). 👍

**Comment by viezel** [comment]
I see. an idea would be to state which insight class that belongs to the issue. This will help guide the user. e.g.:

```bash
my/namespace/MyClass.php:210: Expected 1 space(s) after NOT operator; 0 found (SpaceAfterNotSniff Insight)
```

**Comment by nunomaduro** [comment]
@viezel Can you double check the docs on `phpinsights.com` and check if is better now?

**Comment by viezel** [comment]
@nunomaduro yes, much better 🎉 
love the new `vendor/bin/phpinsights -v`
