### ISSUE TITLE
[Question] Any progress on baseline feature ?

### ISSUE THREAD

**Issue by mirzazeyrek** [nunomaduro/phpinsights#535]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| Library version  | all

Thank you for the good work on this analysis tool. I would like to integrate it in an existing project but it seemed a bit difficult without baseline feature.

Couple of months ago phpmd also included a baseline feature as in phpstan. Jenkins also has similar features. I was wondering if there is any progress or plan for such feature ?

Thanks in advance!

**Comment by nunomaduro** [comment]
No plan or progress at this time.
