### ISSUE TITLE
[Question] Where can I get information on reported errors?

### ISSUE THREAD

**Issue by rslanzi** [nunomaduro/phpinsights#536]
For a number of errors reported by phpinsight, I cannot find any references on the web to understand how to solve them. For example "Forbidden setter" and "The use of traits is prohibited".

PS: it would be nice if for each rule there was a link for further information.

**Comment by 50bhan** [comment]
@rslanzi I believe it's straightforward. The rule says that you shouldn't use any `setter` in your code. One way is to avoid setters and remove them from your code and the other way is to remove this rule and get rid of the errors. I don't know which way do you prefer.

**Comment by rslanzi** [comment]
No, sorry, I misspoke. I meant that I would like to understand why setters (and traits...) are to be avoided and therefore how to refactor the code to pass the test. Is there a book or a site with these "new" best practices?

**Comment by 50bhan** [comment]
@rslanzi Oh, now I got your point. This is something different and out of the scope of `PhpInsights`. It's more like as you said, best practices. I can't refer to one specific resource, but something like avoiding setters is related to object immutability which you lose if use setters. By the way, you can find some of these best practices in books like `Object Design Style Guide`.

**Comment by eleftrik** [comment]
And what about avoiding traits? I can't get the point. Laravel itself uses traits widely.

**Comment by 50bhan** [comment]
@eleftrik Of course. IMHO, using these rules is relative and you can use them or not. Depending on your project, team, technical decisions, etc. But there is a reason behind every rule. For instance: 

`Traits make it very easy to write bloated classes that have too much responsibility. A Trait is essentially a way to “copy and paste” code between classes. By having a way to very simply add another group of methods to a class, it’s very easy to diverge from the single responsibility principle.` [Traits in PHP](https://www.culttt.com/2014/06/25/php-traits#:~:text=Other%20drawbacks%20to%20using%20Traits,be%20crutch%20for%20lazy%20programming.)

So, use these rules based on your judgment.

**Comment by eleftrik** [comment]
> @eleftrik Of course. IMHO, using these rules is relative and you can use them or not. Depending on your project, team, technical decisions, etc. But there is a reason behind every rule. For instance:
> 
> > Traits make it very easy to write bloated classes that have too much responsibility. A Trait is essentially a way to “copy and paste” code between classes. By having a way to very simply add another group of methods to a class, it’s very easy to diverge from the single responsibility principle. [Traits in PHP](https://www.culttt.com/2014/06/25/php-traits#:~:text=Other%20drawbacks%20to%20using%20Traits,be%20crutch%20for%20lazy%20programming.)
> 
> So, use these rules based on your judgment.

Thanks for your kind reply.
I'm still perplexed, because "Use of traits is prohibited" sounds very dogmatic and less prone to interpretation...
