### ISSUE TITLE
[QUESTION] Exclude sub sniff in config

### ISSUE THREAD

**Issue by mattheo-geoffray** [nunomaduro/phpinsights#537]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| Library version  | 1.14.1

Hello,

I would like to know how to exclude a specific sub sniff from a main sniff?   

For exemple the sniff `\SlevomatCodingStandard\Sniffs\TypeHints\ReturnTypeHintSniff` contains sub sniffs like:  
- MissingAnyTypeHint  
- MissingNativeTypeHint
- MissingTraversableTypeHintSpecification
- UselessAnnotation   

Through XML configuration it is possible to exclude one of them with:
```xml
<rule ref="/path/to/SlevomatCodingStandard/TypeHints/ReturnTypeHintSniff.php">
    <exclude name="Sniffs.TypeHints.ReturnTypeHint.UselessAnnotation"/>
</rule>
```

How can I translate that into PHP Insights config file?

Thank you!

<!--
Love PHP Insights? Please consider supporting us via Patreon or OpenCollective:
👉  https://www.patreon.com/nunomaduro
👉  https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=66BYDWAT92N6L
--

**Comment by 50bhan** [comment]
@mattheo-geoffray I believe at the moment it's not possible. @Jibbarth Can you confirm that?

**Comment by Jibbarth** [comment]
Yep, I'm afraid it can't be done. 

Maybe by using the phpcsSuppress annotation ? 

```
/**
 * @phpcsSuppress SlevomatCodingStandard.TypeHints.ReturnTypeHint.UselessAnnotation
 */
```

but i'm not sure.
