### ISSUE TITLE
"vendor" is hard-coded

### ISSUE THREAD

**Issue by olleharstedt** [nunomaduro/phpinsights#544]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| Library version  |PHP Insights v1.14.1

Can't use this nice lib in our repo, since we're using a custom vendor folder in our composer.json:

```json
    "config": {
        "vendor-dir": "third_party",
```

Can you adapt the tool so it reads this config instead of having vendor hard-coded?

The tool works when manually replacing "vendor" with "third_party" in:

nunomaduro/phpinsights/src/Domain/Kernel.php
nunomaduro/phpinsights/bin/phpinsights

I can also make a PR if you wish, should be short. :)

**Comment by JustSteveKing** [comment]
Please provide a PR for this if you can, extending the complexity for none standard usage is something that increases library maintainance quite a lot.
