### ISSUE TITLE
Average complexity misleading?

### ISSUE THREAD

**Issue by mkoske** [nunomaduro/phpinsights#547]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | yes
| Library version  | x.y.z

Isn't the average complexity a bit misleading? If you have many simple classes, like entities with just getters and setters, with very low complexity and then some classes that have high complexity, the average will still be low.

E.g. I have average complexity of 1.51 and then I have e.g. one class with complexity of 36. At least report something else with it, like max, min, and std.

<!--
Love PHP Insights? Please consider supporting us via Patreon or OpenCollective:
👉  https://www.patreon.com/nunomaduro
👉  https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=66BYDWAT92N6L
--

**Comment by JustSteveKing** [comment]
None issue - documentation needs clarifying what complexity measures and means
