### ISSUE TITLE
Removing insights (classes) via config isn't removing removed insights' checks

### ISSUE THREAD

**Issue by emjayess** [nunomaduro/phpinsights#548]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| Library version  | ^2.0

Per the documentation on [removing insights](https://phpinsights.com/insights/#remove-insights), I do:
```php
    'remove' => [
        //  ExampleInsight::class,
        
        // ignore strict_type check
        \SlevomatCodingStandard\Sniffs\TypeHints\DeclareStrictTypesSniff::class,
    ],
```

And then run insights: 
`$ phpinsights analyse my_code -c=~/myinsights.php -v`

And in the output, still get:
```bash
• [Code] Declare strict types: (SlevomatCodingStandard\Sniffs\TypeHints\DeclareStrictTypesSniff)
  class.PortalControllerBrand.php:1: Missing declare(strict_types=1).
```

#### Why not removed / ignored??

**Comment by JustSteveKing** [comment]
Supporting the tilde symbol is not possible as this will only work on *nix systems not on all supported platforms. Closing as this is a none fix
