### ISSUE TITLE
A new Laravel project gives me a bunch of warnings/errors

### ISSUE THREAD

**Issue by stefankaters** [nunomaduro/phpinsights#554]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| Library version  | 2.0.1

Hey Nuno (if you are reading this),

I would like to start off by saying that I really appreciate your work and contributions to the open-source community.
I think you did a fantastic job on these projects and I would to thank you for that. I would also like to thank the other contributors for their efforts as well, thanks!

I don't have an issue per se, but I do have have a question about the Laravel integration of this tool.
When I start a new Laravel project (version 8.74.0) and install PHP Insights with the following command: `composer require nunomaduro/phpinsights --dev` and then execute the following command (described by the documentation): `php artisan vendor:publish --provider="NunoMaduro\PhpInsights\Application\Adapters\Laravel\InsightsServiceProvider"` everything works fine like expected, but when I execute this command `php artisan insights` I get a bunch of warnings about the default Laravel code that is included with every new Laravel project.

My question is, why don't I get 100% on every aspect (Code, Complexity, Architecutre and Style)? Is the default Laravel code  by default not 'perfect'?

**Comment by 50bhan** [comment]
@katerss1 No, no code is perfect and of course, it depends. Because of the sniffs that you are using, the result would be different and it's not related to the code perfection. It's related to your expectation and config that you've chosen.
