### ISSUE TITLE
Syntax error in SyntaxCheck.php line 56 on docker image

### ISSUE THREAD

**Issue by lucabartoli** [nunomaduro/phpinsights#556]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| Library version  | Docker image : latest

Tried
`docker run -it --rm -v "$(pwd):/app" nunomaduro/phpinsights`

on a laravel project (wanted to run an analysis without actually running the project or loading dependencies)

I got
```
 13/64 [▓▓▓▓▓░░░░░░░░░░░░░░░░░░░░░░░]  20%

In SyntaxCheck.php line 56:

  Syntax error


analyse [-c|--config-path [CONFIG-PATH]] [-s|--summary] [--min-quality [MIN-QUALITY]] [--min-complexity [MIN-COMPLEXITY]] [--min-architecture [MIN-ARCHITECTURE]] [--min-style [MIN-STYLE]] [--disable-security-check] [--format FORMAT] [--composer [COMPOSER]] [--fix] [--flush-cache] [--] [<paths>...]
```

There are no other info, but please ask if something has to be checked.

**Comment by JustSteveKing** [comment]
@lucabartoli which PHP version are you running this on? Typically I see syntax errors on packages built in one PHP version ran in another one. Please check version support - and let me know if this is still an issue

**Comment by lucabartoli** [comment]
@JustSteveKing it's a laravel project v^8.0, usually running on a normal 8.0-fpm-alpine

**Comment by cmgmyr** [comment]
I verified the issue locally as well. The docker image is php 7.4. Once I changed it locally to 8.0 and rebuilt the image everything ran fine. I'm not sure why that line would be failing on 7.4

I'm going to need push access to docker hub first, but I think it might be a good idea to have tags for different php versions: 74, 80, 81

**Comment by lucabartoli** [comment]
@cmgmyr great, thanks for your test!
If using a different php version for testing a codebase could be an issue, I too agree about creating different compiled images tagged by php version.
The strange thing is that laravel 8 is php ^7.3|^8.0 compatible, so I can run the same codebase with a php 7.4 and I can't understand why this could be an issue.

**Comment by cmgmyr** [comment]
@lucabartoli yes, it's very strange. Right now I just bumped the PHP version in a new PR, but I've already pushed the new `latest` tag. Can you give it a try at your convenience? I've run it on a few projects and seems to be working fine on my end.

**Comment by lucabartoli** [comment]
@cmgmyr it works, thanks!

**Comment by Messhias** [comment]
I'm using this version:

```
PHP 8.1.6 (cli) (built: May 12 2022 23:30:39) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.6, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.6, Copyright (c), by Zend Technologies
```

And I'm getting this error as well on an Apple with M1.

Same error:
```
docker run -it --rm -v "$(pwd):/app" nunomaduro/phpinsights                       
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

 668/671 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░]  99%

In SyntaxCheck.php line 56:
                
  Syntax error  
                

analyse [-c|--config-path [CONFIG-PATH]] [-s|--summary] [--min-quality [MIN-QUALITY]] [--min-complexity [MIN-COMPLEXITY]] [--min-architecture [MIN-ARCHITECTURE]] [--min-style [MIN-STYLE]] [--disable-security-check] [--format FORMAT] [--composer [COMPOSER]] [--fix] [--flush-cache] [--] [<paths>...]

```

**Comment by markkimsal** [comment]
Can confirm this happens on php 7.4.29 when running against a single blank file (just php open tag).

This version packaged via phpqa with php 7.4 does not work
```
echo '<?php' > empty.php
docker run --init -ti -v $(pwd):/app -w /app --rm  jakzal/phpqa:1.72.2-php7.4-alpine  phpinsights analyse  -- empty.php
```
```
docker run --init -ti -v $(pwd):/app -w /app --rm  jakzal/phpqa:1.72.2-php7.4-alpine  phpinsights --version
PHP Insights v2.2.0
```

This packaged version that is also v2.2.0 DOES work ... ?
```
echo '<?php' > empty.php
docker run --init -ti -v $(pwd):/app -w /app --rm  nunomaduro/phpinsights  analyse -- empty.php
```
```
docker run --init -ti -v $(pwd):/app -w /app --rm  nunomaduro/phpinsights  analyse --version
PHP Insights v2.2.0
```

**Comment by sebastiansulinski** [comment]
I've just experienced the same on php 8.4 

```shell
687/754 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░]  91%

   JsonException

  Syntax error

  at vendor/nunomaduro/phpinsights/src/Domain/Insights/SyntaxCheck.php:57
     53▕         }
     54▕         $configuration = Container::make()->get(Configuration::class);
     55▕         $process->setTimeout($configuration->getTimeout())->run();
     56▕
  ➜  57▕         $output = json_decode($process->getOutput(), true, 512, JSON_THROW_ON_ERROR);
     58▕         $errors = $output['results']['errors'] ?? [];
     59▕
     60▕         foreach ($errors as $error) {
     61▕             if (preg_match('/^.*error:(.*) in .* on line [\d]+/m', $error['message'], $matches) === 1) {
```
