### ISSUE TITLE
PHP 8.1 ENUMS are detected as GOTO Statements

### ISSUE THREAD

**Issue by BlackScorp** [nunomaduro/phpinsights#557]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| Library version  | v2.1.0

I use in my current Project PHP 8.1 new Feature enums

```php
enum Status: string{
case DEFAULT = 'default';
case DRAFT = 'draft';
}
```
running phpinsights leads the part with enum Status: string into "Use of the GOTO language construct is discouraged" error

<!--
Love PHP Insights? Please consider supporting us via Patreon or OpenCollective:
👉  https://www.patreon.com/nunomaduro
👉  https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=66BYDWAT92N6L
--

**Comment by julianstark999** [comment]
[squizlabs/PHP_CodeSniffer](https://github.com/squizlabs/PHP_CodeSniffer) currently does not support Enums.
There is an Issue to Issue to track what needs to be done. https://github.com/squizlabs/PHP_CodeSniffer/issues/3479

**Comment by BlackScorp** [comment]
Ah okay thank you, i close this ticket then

**Comment by patrickomeara** [comment]
Just a note that the support has been merged into PHPCS but not yet released  https://github.com/squizlabs/PHP_CodeSniffer/pull/3478
