### ISSUE TITLE
Remove composer/composer dependency

### ISSUE THREAD

**Issue by Seldaek** [nunomaduro/phpinsights#559]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| Library version  | x.y.z

Please do not rely on composer/composer, this tends to make a mess like https://github.com/composer/composer/discussions/10502 

The way I see it from a quick look in the source, the only use case is checking for lock file validity, which really should be done via `composer validate`, you can run that as an external process perhaps and look if the output contains the lock file warning? 

`composer validate --no-check-publish --no-check-all --no-check-version --strict --file path/to/composer.json` is probably the best way to run it for this use case to avoid other noise.

**Comment by JustSteveKing** [comment]
It sounds like the best approach for this is going to be building up a class around using composer as a process over using the library itself. Will move this to investigation stage - @Seldaek do you have any materials we can use to do a deeper integration with composer here?

**Comment by Seldaek** [comment]
Not really sorry. I'm happy to help if you have specific questions.

**Comment by JustSteveKing** [comment]
Thanks @Seldaek - I will chat with the other maintainer to see what we can do around this, and come back with any questions we might have.
