### ISSUE TITLE
ForbiddenGlobals ignores exclude config

### ISSUE THREAD

**Issue by Borlabs-Ben** [nunomaduro/phpinsights#560]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| Library version  | 2.1.0

The file in `exclude` is ignored by the [ForbiddenGlobals](https://phpinsights.com/insights/code.html#forbidden-globals) rule.

```
'config' => [
    NunoMaduro\PhpInsights\Domain\Insights\ForbiddenGlobals::class => [
        'exclude' => [
            'Adapter/WPDB.php',
        ],
    ],
```

Example code:
```
final class WPDB {
    public static function getInstance(): \wpdb
    {
        global $wpdb;
    
        return $wpdb;
    }
}
```

**Comment by 50bhan** [comment]
@Borlabs-Ben I don't know what your problem is. Could you elaborate?

Because based on your explanation, the `WPDB` file is ignored and it's because it's in the `exclude` section. Isn't it the expected behavior?

**Comment by Borlabs-Ben** [comment]
The file is not ignored by the rule but it should. I still get the message of using global in WPDB.php
