### ISSUE TITLE
Enum definition triggers Discourage Goto error

### ISSUE THREAD

**Issue by lupinitylabs** [nunomaduro/phpinsights#578]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| Library version  | 2.2.0

```php
<?php

declare(strict_types=1);

namespace App\Enums;

enum SqlOrderDirection: string
{
    case Ascending = 'asc';
    case Descending = 'desc';
}
```

This Enum will trigger the following error:
```
• [Code] Discourage goto:
  app/Enums/SqlOrderDirection.php:7: Use of the GOTO language construct is discouraged
```

Looking at the Sniff class, it appears that it is listening for the T_GOTO_LABEL token, which does not seem to be listed in the official token list at https://www.php.net/manual/en/tokens.php, nor in the PHPTokenizerInternal class.

It is defined as `define('T_GOTO_LABEL', 'PHPCS_T_GOTO_LABEL');` in `PHP_CodeSniffer\Util\Tokens`, and I have no idea why this should be confused with T_ENUM at all.

**Comment by JustSteveKing** [comment]
Unfortunately I think Enum support in all tools is going to be slow progress to be introduced. This is an issue with a 3rd party dependency not the insights code, closing for now, but will keep an eye on the issue
