### ISSUE TITLE
Complexity is more than 100% incase of empty projects

### ISSUE THREAD

**Issue by rajengla** [nunomaduro/phpinsights#58]
The method to **getComplexity()** reports complexity percentage > 100 when average_complexity_per_method is less than 1.

**Comment by nunomaduro** [comment]
This is weird, the `average_complexity_per_method` should never be mess than 1.

**Comment by rajengla** [comment]
I ran the PHP Insights analyzer for an empty project or **.php** files with no content. The Divide function inside Collector.php returns zero in case we don't have any method complexity records.

We can report complexity = 100% for such cases.

**Comment by nunomaduro** [comment]
Can you make a pull request on that?

**Comment by nunomaduro** [comment]
This issue has been fixed on the version `v1.5.0`.
