### ISSUE TITLE
SuperfluousInterfaceNamingSniff - false possitive

### ISSUE THREAD

**Issue by LocalHeroPro** [nunomaduro/phpinsights#588]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| Library version  | 2.4.0

```
• [Architecture] Superfluous interface naming: (SlevomatCodingStandard\Sniffs\Classes\SuperfluousInterfaceNamingSniff)
  Contracts/CollectionOrderInterface.php:5: Superfluous suffix "Interface".
  Contracts/DatatablesRepositoryInterface.php:7: Superfluous suffix "Interface".
  Contracts/ImportMailingSubscribersInterface.php:7: Superfluous suffix "Interface".
  Contracts/ImportOrdersInterface.php:9: Superfluous suffix "Interface".
```
and
https://www.php-fig.org/bylaws/psr-naming-conventions/

So why I can't have that suffux?

**Comment by JustSteveKing** [comment]
This is coming from this package: `slevomat/coding-standard` which you are able to disable in config to get around.

**Comment by LocalHeroPro** [comment]
I don't wanna go around. I wanna correct tests, so please reopen.

**Comment by JustSteveKing** [comment]
You need to disable this check within your config

**Comment by LocalHeroPro** [comment]
Why? That check working as expected with PHP FIG standards?

**Comment by JustSteveKing** [comment]
From the `slevomat/coding-standard` docs:

```
SlevomatCodingStandard.Classes.SuperfluousInterfaceNaming
Reports use of superfluous prefix or suffix "Interface" for interfaces.
```

This sniff will report on interfaces that suffix their name with `Interface`, which is why your code is being caught out here. I would recommend, as you are using a Contracts namespace, to rename these to Contract to avoid this sniff complaining

**Comment by LocalHeroPro** [comment]
I fully understand that, but I want to know if that rule is compatible with FIG standards?

**Comment by JustSteveKing** [comment]
@LocalHeroPro this sniff is not completely compatible with FIG
