### ISSUE TITLE
Add support for slevomat/coding-standard 8.x

### ISSUE THREAD

**Issue by mrVrAlex** [nunomaduro/phpinsights#604]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| Library version  | latest

Will propose add support to composer slevomat/coding-standard for 8.x versions: https://github.com/slevomat/coding-standard/releases/tag/8.0.0
If phpinsights not use sniffs which listed in BC breaks, then it will be easy in composer.json

**Comment by specialtactics** [comment]
Bump on this please!
