### ISSUE TITLE
Unable to find data for 

### ISSUE THREAD

**Issue by cAstraea** [nunomaduro/phpinsights#609]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| Library version  | latest

Trying to run this in a laravel project but if I'm running it as php artisan insights this part throws in 
throw new \LogicException('Unable to find data for ' . $file->getPathname());

https://flareapp.io/share/VmeOaMz7#F24

```
    private function processFile(SplFileInfo $file): void
    {
        $cacheKey = 'insights.' . $this->cacheKey . '.' . md5($file->getContents());
        // Do not use cache if fix is enabled to force processors to handle it
        if (! $this->cache->has($cacheKey)) {
            throw new \LogicException('Unable to find data for ' . $file->getPathname());
        }
```

If i run it directly as ./vendor/bin/phpinsights analyse it completes without error

<!--
Love PHP Insights? Please consider supporting us via Patreon or OpenCollective:
👉  https://www.patreon.com/nunomaduro
👉  https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=66BYDWAT92N6L
--

**Comment by zeinlol** [comment]
Same error when try to scan  https://github.com/digininja/DVWA
I use docker image, and receive
```
In Runner.php line 184:

  Unable to find data for /wd/target/DVWA-master/external/phpids/0.6/docs/examples/example.php
```
