### ISSUE TITLE
Implement output-format option

### ISSUE THREAD

**Issue by nunomaduro** [nunomaduro/phpinsights#61]
People may want to see the results from PHP Insights within a beautiful `html` page, or may want to check the results using the `json` format.

All the classes from PHP Insights are `internal`, so we are able to refactor without making a breaking change.

**Comment by joseph1125** [comment]
I would be satisfied with a simple TXT file listing all of the problems

**Comment by stephenlake** [comment]
JSON or any structured format would be appreciated so we can hook up test results to slack/any other post CI integration with notifications to moan at someone for degrading scores.

**Comment by titomiguelcosta** [comment]
I personally do not like the implementation done in some of the symfony commands, for example, in [lint:twig](https://github.com/symfony/twig-bridge/blob/master/Command/LintCommand.php), the command itself has methods to displayTxt and displayJson. 

I do not know how's the internal structure, if the current implementation is coupled with the console, but hopefully there is an abstraction layer, is that the case? If so, we only need to create classes that will generate the output for a specific format, ex: TxtFormatter, XmlFormatter, and accept the internal structure as input. In the command itself, it will just determine which formatter to use based on the optional argument --format.

**Comment by godsgood33** [comment]
I like the idea of optional `--html` or `--json` flags.  But I think definitely, I'd like to see the total summarized at the end of the report.  Meaning, you see the "+x issues omitted", just total all of the items in the category and show that total at the end

```
Code: 2 issues
Complexity: 400 issues
Architecture: 345 issues
Style: 5000 issues
```

**Comment by karljakober** [comment]
As a workaround just pipe the output of the script to a log file, tail the file in another terminal, then hit enter a few times where you ran the command. worked great for me!

**Comment by titomiguelcosta** [comment]
@karljakober I normally run `php vendor/bin/phpinsights -n 2> /dev/null` so it does not paginate and hides the progress bar, but the output is not easily parsable, so that's why being able to dump json or xml would be great.

**Comment by nuernbergerA** [comment]
an option for Checkstyle xml would be awsome

**Comment by nuernbergerA** [comment]
@nunomaduro any idea how to implement (structure) different formats?

**Comment by nunomaduro** [comment]
Not yet, I am open for ideas.

**Comment by godsgood33** [comment]
How about something like this for JSON?

```
[
  "summary" : {
    "code" : 42,
    "complexity" : 42,
    "architecture" : 42,
    "style" : 42
  },
  "code" : [
    {
      "file" : "/src/path/file.php",
      "line" : 42,
      "type" : "error"  // use standard warning levels to indicate severity,
      "msg" : "Invalid stuff",
      // I don't know if there is anything else that you have access to that might be helpful
    },
    {
    }
  ],
  "complexity" : [
    // use similar structure as code but with any special details
  ],
  "architecture" : [
  ],
  "style" : [
  ]
]
```

**Comment by nuernbergerA** [comment]
How about an `--format=checkstyle` and `--file=checkstyle-result.xml`.
Without `--file` it will echo to stdout.

Other formats cold be
 * console (default)
 * json
 * html
 * text

We can put each formater in a formaters directory.

All formaters implement an interface.

Naming decisions have to been made.
Possible names are:
 * Format
 * Style
 * Output

**Comment by olivernybroe** [comment]
Yes, let's go for format, and a interface called format. 
There's no need for having our own Output interface, as we can just use Symfonys interface for that.

**Comment by olivernybroe** [comment]
Just added support for json formatting in my PR. Feel free to check it out and see if the output satisfies the need.

**Comment by abishekrsrikaanth** [comment]
Any chance of this being available sooner?

**Comment by orlyapps** [comment]
This would be very helpful!

**Comment by olivernybroe** [comment]
Out of curiosity, what do you guys need the functionality for?
The pr we have open adds a Json format that we created ourself.

**Comment by nunomaduro** [comment]
I will check this pr, next week. Promise. 👍🏻

**Comment by nunomaduro** [comment]
Pull request has been merged. Working on the release during today/tomorrow.
