### ISSUE TITLE
PHP 8.2.0 (e.g.,  "Using ${var} in strings is deprecated") and find this in my source

### ISSUE THREAD

**Issue by RobertEcker** [nunomaduro/phpinsights#615]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| Library version  | latest (downloaded yesterday, or where can I check the version?)

1)
I am using PHP 8.2.0
Deprecated: Using ${var} in strings is deprecated, use {$var} instead
e.g.,
src\Application\Console\Formatters\Console.php on line 200
src\Application\Console\Formatters\Console.php on line 383
src\Application\Console\Formatters\Console.php on line 422

2) find such used ${var} in my source code

**Comment by RobertEcker** [comment]
@trovster thank you for the fix, when will it be available?

**Comment by trovster** [comment]
@RobertEcker I opened the pull-request over two weeks ago but I wasn't merged. I have been tidying up my GitHub repositories and removed the phpinsights one, so it looks like the PR is no longer available.

**Comment by wilbur-yu** [comment]
I also encountered these errors in PHP version 8.2 Is the PR still in the process of merging?
