### ISSUE TITLE
Step up version for support slevomat/coding-standard:8.0

### ISSUE THREAD

**Issue by mechemsi** [nunomaduro/phpinsights#618]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| Library version  | 2.6.1

Hi, I have issue that I cannot install package, because I have already slevomat/coding-standard v8.7 and php insights 2.6.1 version requires v7. And I see in master branch composer updated to  support slevomat/coding-standard:8.0, so I would like request step up version of package to 2.6.2 for updated composer
`Problem 1
    - Root composer.json requires nunomaduro/phpinsights ^2.6 -> satisfiable by nunomaduro/phpinsights[v2.6.0, v2.6.1].
    - nunomaduro/phpinsights[v2.6.0, ..., v2.6.1] require slevomat/coding-standard ^7.0.8 -> found slevomat/coding-standard[7.0.8, ..., 7.2.1] but it conflicts with your root composer.json require (^8.7).`

<!--
Love PHP Insights? Please consider supporting us via Patreon or OpenCollective:
👉  https://www.patreon.com/nunomaduro
👉  https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=66BYDWAT92N6L
--

**Comment by renky** [comment]
2.7.0 is out - so now this should be solved...
