### ISSUE TITLE
phploc/phploc is abandoned

### ISSUE THREAD

**Issue by denydias** [nunomaduro/phpinsights#622]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| Library version  | 2.7.0

Sadly, on Jan'10th 2023 [sebastianbergmann/phploc](https://github.com/sebastianbergmann/phploc) was archived. As a side-effect **phpinisights** is now in trouble.

```console
$ composer update
Loading composer repositories with package information
Updating dependencies
Nothing to modify in lock file
Installing dependencies from lock file (including require-dev)
Nothing to install, update or remove
Package phploc/phploc is abandoned, you should avoid using it. No replacement was suggested.
Generating optimized autoload files

$ composer show --tree nunomaduro/phpinsights
nunomaduro/phpinsights v2.7.0 Instant PHP quality checks from your console.
├──composer/semver ^3.3
│...
├──phploc/phploc ^5.0|^6.0|^7.0
│...
└──symfony/process ^5.4|^6.0
```

**Comment by cmgmyr** [comment]
I have an email out to Sebastian to see if he'd be willing to give me access to the repo to continue maintaining the package. If I don't hear back within the next week or so, I'll be working on putting together some alternative ideas.

**Comment by eclipse313** [comment]
Thank you for the Update!

Am 18.02.2023 um 02:08 schrieb Chris Gmyr ***@***.***>:

﻿

I have an email out to Sebastian to see if he'd be willing to give me access to the repo to continue maintaining the package. If I don't hear back within the next week or so, I'll be working on putting together some alternative ideas.

**Comment by denydias** [comment]
> I have an email out to Sebastian to see if he'd be willing to give me access to the repo to continue maintaining the package. If I don't hear back within the next week or so, I'll be working on putting together some alternative ideas.

That's unexpected, @cmgmyr!

- Last commit was only 12h ago made by Nuno himself;
- PHP Insights was featured in Laravel News just [yesterday](https://laravel-news.com/getting-started-with-phpinsights).

By all means this repo doesn't appear to be in the need of a maintainer or a fork due the lack of inactivity. But what do I know, right?

**Comment by repat** [comment]
@nunomaduro @cmgmyr any progress on this? :)

**Comment by cmgmyr** [comment]
@repat I have a forked repo set up for phploc, I have to finish a few tasks and make a PR here with the updates. I'm hoping to get this done this week

**Comment by cmgmyr** [comment]
@tarlepp What's not working? If it's specific to `phploc`, please feel free to open an issue on the new repo https://github.com/cmgmyr/phploc
