### ISSUE TITLE
Allow memory size exhausted.

### ISSUE THREAD

**Issue by Koopabro** [nunomaduro/phpinsights#63]
This error pops up:

PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 33554440 bytes) in [projectfolder]/vendor/nunomaduro/phpinsights/src/Domain/Collector.php on line 349

**Comment by nunomaduro** [comment]
Check the readme here: https://github.com/nunomaduro/phpinsights/blob/master/README.md#allowed-memory-size-of-x-bytes-exhausted.

**Comment by wlarch** [comment]
I have encountered the memory limit using PHP command line interface ( CLI ) and has a hard time finding how to increase the memory limit. After trying to modify the loaded `php.ini` file or specifying the memory as a CLI parameter `php -d memory_limit=2G ./vendor/bin/phpinsights`, I realized the memory limit stayed the same 134217728 bytes (128M).

I found out I had a previous `phpcs.xml` file for PHP Code Sniffer in which the following flag was specified : 
`<ini name="memory_limit" value="128M"/>`

After removing the `ini` flag, everything is good ! I hope it can help others.

It may be worth of mention in the docs @nunomaduro ?

https://github.com/nunomaduro/phpinsights/compare/master...wlarch:patch-1

**Comment by realtek2** [comment]
[wlarch](https://github.com/wlarch), [nunomaduro](https://github.com/nunomaduro) I have the same error on version 2.12.0. I ran `php -d memory_limit=2000M vendor/bin/phpinsights --no-interaction`. But my `phpcs.xml` does not contain any `<ini>` tags. 

Can you please help me with this issue? 

I have tried to increase memory limit to 4000M but my BitBucket pipeline says that I need allocate 2097160 bytes.

Error dump:
```
+ php -d memory_limit=2000M vendor/bin/phpinsights --no-interaction
   0/504 [░░░░░░░░░░░░░░░░░░░░░░░░░░░░]   0%
In Runner.php line 161:
                                                                               
  The command "'/usr/local/bin/php' '/opt/atlassian/pipelines/agent/build/ven  
  dor/bin/phpinsights' 'internal:processors' 'thread-1-f70af204a88f2896934f10  
  610fae6330'" failed.                                                         
                                                                               
  Exit Code: 255(Unknown error)                                                
                                                                               
  Working directory: /opt/atlassian/pipelines/agent/build                      
                                                                               
  Output:                                                                      
  ================                                                             
                                                                               
  Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to all  
  ocate 2097160 bytes) in /opt/atlassian/pipelines/agent/build/vendor/friends  
  ofphp/php-cs-fixer/src/Tokenizer/Analyzer/SwitchAnalyzer.php on line 34      
                                                                               
                                                                               
  Error Output:                                                                
  ================       
```
