### ISSUE TITLE
Still can't install the 2.8.0 version with phpunit 10

### ISSUE THREAD

**Issue by Xor767** [nunomaduro/phpinsights#635]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| Library version  | 2.8.0

Hi! I still can't install phpinsights with laravel 10 / phpunit 10 because of the sebastian/cli-parser package.

<img width="1406" alt="error" src="https://user-images.githubusercontent.com/104351908/226276765-e87bed5f-e38a-4850-98d0-165def42cc2a.png">

**Comment by cmgmyr** [comment]
`8.0.2` is the latest release of `cmgmyr/phploc` and has the update to the `sebastian/cli-parser` dependency. I was able to install `phpinsights` in a new L10 project. Can you try

`composer update -W`

if that doesn't work, try removing and reinstalling `phpinsights`

`composer remove nunomaduro/phpinsights && composer require nunomaduro/phpinsights --dev`
