### ISSUE TITLE
Command will fail on models that contain only properties with inheritdoc comments

### ISSUE THREAD

**Issue by hfatahi** [nunomaduro/phpinsights#65]
Running `php artisan insights` on a Laravel 5.8 app, I got the following error message
![image](https://user-images.githubusercontent.com/8626733/57850630-58d5d600-77ac-11e9-8f1c-ab1bb895a44c.png)
The command failed at this file
```php
<?php

namespace App\Models\MasterData;

use App\Models\BaseModel;

class Organization extends BaseModel
{
    /**
     * {@inheritdoc}
     */
    public $timestamps = false;
}
```
I was able to confirm that:
- the command will run successfully if I removed the inheritdoc comment.
- the command will fail only if the model contains no methods, only properties. If the model has one or more methods then the command will run successfully 

To reproduce, add the provided model code above to your application and try running the command.

**Comment by nunomaduro** [comment]
Thanks for this great description!

**Comment by nunomaduro** [comment]
Can you try with the latest master and re-create a new issue with the same content if you are still having this issue?
