### ISSUE TITLE
Replace PHP cs fixer to Laravel pint?

### ISSUE THREAD

**Issue by medeiroz** [nunomaduro/phpinsights#659]
is it possible to replace php cs fixer with laravel pint?

**Comment by d8vjork** [comment]
+1 on this, me and my team we're struggling with syncing the PHPInsights code style config to the one in Pint as we use it locally in our VSCode to format all the code while working and is hard to maintain ourselves

**Comment by nunomaduro** [comment]
PRs open.

**Comment by jonathanpmartins** [comment]
Was this published? I only use laravel pint. I dont use phpcs.
How can I integrate my `pint.json` with insights?
