### ISSUE TITLE
insights command hangs at 80%

### ISSUE THREAD

**Issue by PepijnDeWachter** [nunomaduro/phpinsights#66]
Hi, I'm using the laravel preset on windows,
The command hangs at 80% (527/652 files?) with no log or error.

Could you let me know where in the code I could temporarily inject a log function that spits out the currently analyzed file/method?

Thank you

**Comment by nunomaduro** [comment]
Please try `artisan insights -vvv` to get more information the error.

**Comment by PepijnDeWachter** [comment]
It seemed to be inside the phpdocx package, which isn't available on a repository so I didn't put that into the vendor folder, excluding the package's folder in the config fixed the issue 👍
