### ISSUE TITLE
Differences between switch and match sentences, impact on Cyclomatic Complexity

### ISSUE THREAD

**Issue by EnriqueSanVic** [nunomaduro/phpinsights#661]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| Library version  | 2.8.0

I have been testing with my development team the insights package to handle cyclomatic complexity and we have found that match statements have a different impact than switch statements. 

For example: 

```php
function fooMatch(string $foo = 'a'): string {

    return match ($foo){
        'a' => 'first',
        'b' => 'second',
        'c' => 'third',
        default => 'none'
    };
}

function fooSwitch(string $foo = 'a'): string {

    switch ($foo){
        case 'a':
            return 'first';
        case 'b': 
            return 'second';
        case 'c': 
            return 'third';
        default:
            return 'none';
    }
}
```

I think that in both functions the cyclomatic complexity should be the same but phpinsigths evaluates it different. 
Could you tell me why?

<!--
Love PHP Insights? Please consider supporting us via Patreon or OpenCollective:
👉  https://www.patreon.com/nunomaduro
👉  https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=66BYDWAT92N6L
--

**Comment by soymgomez** [comment]
We have seen this too! @nunomaduro  can you keep an eye on it?

**Comment by palamar** [comment]
I believe it's because `match` would end after the first matched case, whereas `switch` may execute all cases if there is no break or return statement also strict comparison in `match` and weak comparison in `switch` have to add diff. as well.
As I remember `if` -> `else` and ternary operator have diff complexity as well.
