### ISSUE TITLE
Support Symfony 7

### ISSUE THREAD

**Issue by tacman** [nunomaduro/phpinsights#664]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| Library version  | current

Symfony 7 is in beta.  composer.json restricts the symfony components to 4-6.

Arguable Symfony 4 could be dropped, since it's EOL, and the minimum could be 5.4.  But if someone is analyzing old code, maybe we should continue to support it (and redirect them to https://github.com/rectorphp/rector!)

**Comment by damien-louis** [comment]
Symfony 7 was released today

**Comment by nunomaduro** [comment]
PRs are welcome.

**Comment by damien-louis** [comment]
@nunomaduro: 
not sure if it's enough https://github.com/nunomaduro/phpinsights/pull/666

(Damn, PR 666 ^^)

**Comment by damien-louis** [comment]
Merged.
https://github.com/nunomaduro/phpinsights/pull/666
https://github.com/nunomaduro/phpinsights/releases/tag/v2.11.0
