### ISSUE TITLE
Add links to details or examples

### ISSUE THREAD

**Issue by tacman** [nunomaduro/phpinsights#665]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes

What a cool tool!

I'm getting this warning:

    Usage of array type hint syntax in "Term[]" is disallowed, use generic type hint syntax instead.

It comes from the stubs created by the symfony maker

     bin/console make:entity Term

```php
/**
 * @extends ServiceEntityRepository<Term>
 *
 * @method Term|null find($id, $lockMode = null, $lockVersion = null)
 * @method Term|null findOneBy(array $criteria, array $orderBy = null)
 * @method Term[]    findAll()
 * @method Term[]    findBy(array $criteria, array $orderBy = null, $limit = null, $offset = null)
 */
```

First, since it's coming from the Symfony generator and works with PhpStorm, I would think that it was in fact a good practice.  If there's a better way, I'm interested.  And that got me thinking, maybe you could add something like PHPStan that provides a link to some common errors and their solutions.

Thanks for your consideration, and for creating this!

**Comment by Jibbarth** [comment]
In this case, you should use 

```
@method array<Term> findAll()
```

Or you can disable this insight :wink: (https://phpinsights.com/insights/code.html#disallow-array-type-hint-syntax)

**Comment by tacman** [comment]
Does either approach work?  Symfony tends to follow best practices, but I've found generics confusing and keep waiting for a version of PHP that supports them natively.   Like when attributes came out, I couldn't wait to rid my code of annotations, which often tripped me up.
