### ISSUE TITLE
PHP CodeSniffer alternative

### ISSUE THREAD

**Issue by vladimir-borduja** [nunomaduro/phpinsights#669]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| Library version  | x.y.z

The package `squizlabs/PHP_CodeSniffer` is abandoned and will no longer be supported.
@nunomaduro Do you have plans to migrate to the other code-style tool/project?

**Article about the fate of PHP CodeSniffer.**
https://github.com/squizlabs/PHP_CodeSniffer/issues/3932

[Pull request about marking CodeSniffer abandoned](https://github.com/squizlabs/PHP_CodeSniffer/issues/3932)

**New package or the** @jrfnl(profile: https://github.com/jrfnl)
| Where                 | URI
| ---------------- | ------------------------------------------------------------
| GitHub                | https://github.com/PHPCSStandards/PHP_CodeSniffer
| Packagist           | [no](https://packagist.org/packages/phpcsstandards/php_codesniffer)

Regards, Vlad

<!--
Love PHP Insights? Please consider supporting us via Patreon or OpenCollective:
👉  https://www.patreon.com/nunomaduro
👉  https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=66BYDWAT92N6L
--

**Comment by jrfnl** [comment]
@vladimir-borduja The package is_not_ being abandoned, it is being **continued in a new fork**. Please don't spread misinformation.

It is also on Packagist (yes), though it now seems [likely the Composer name will remain the same](https://github.com/squizlabs/PHP_CodeSniffer/issues/3932#issuecomment-1842531678).

I suggest you wait until there is a release (as also suggested in the announcement) before taking any action. The changelog of the 3.8.0 release will contain all the relevant information for all supported installation manners.

**Comment by vladimir-borduja** [comment]
@jrfnl My bad, thx for the reply.
