### ISSUE TITLE
Deprecated creation of dynamic property in SniffLoader

### ISSUE THREAD

**Issue by manchenkoff** [nunomaduro/phpinsights#674]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| Library version  | 2.11.0

Installed library on a fresh PHP project and got these warnings:

```bash
PHP Deprecated:  Creation of dynamic property SlevomatCodingStandard\Sniffs\TypeHints\DeclareStrictTypesSniff::$newlinesCountBeforeDeclare is deprecated in /.../vendor/nunomaduro/phpinsights/src/Domain/InsightLoader/SniffLoader.php on line 40
```

Everything still works, but wanted to let you know in case it is possible to fix the warning.

**Comment by Jibbarth** [comment]
Will be fixed with #697
