### ISSUE TITLE
Dockerized version

### ISSUE THREAD

**Issue by fruitl00p** [nunomaduro/phpinsights#68]
Hi :)

Just a quick heads up: i've created a [dockerized version](https://hub.docker.com/r/gekkie/phpinsights) to more easily run this in CI / locally or wherever on any type of project so it can more easily help with (i.e.) transitioning code to newer PHP versions.

This also lowers the barrier of getting everything up and running to test it out :)

One can simply run `docker run -v $(pwd):/app gekkie/phpinsights` to get going

**Comment by nunomaduro** [comment]
This issue is solved.
