### ISSUE TITLE
[Insight] Verify if all php files contain `declare(strict_types=1);`

### ISSUE THREAD

**Issue by nunomaduro** [nunomaduro/phpinsights#7]
To solve this issue, you should create a pull request adding the following insight:  Verify if all php files contain `declare(strict_types=1);`.

This will be later an optional `Insight`.

**Comment by xuanquynh** [comment]
You can add `declare(strict_types=1); " directive to all php files by using the [friendsofphp/php-cs-fixer](https://packagist.org/packages/friendsofphp/php-cs-fixer) package.

This is the sample of .php_cs file
```php
<?php

$finder = PhpCsFixer\Finder::create()
    ->files()
    ->name('*.php')
    ->exclude('tests/fixtures')
    ->in(__DIR__.'/src')
    ->in(__DIR__.'/tests')
;

return PhpCsFixer\Config::create()
    ->setUsingCache(true)
    ->setRiskyAllowed(true)
    ->setFinder($finder)
    ->setRules([
        'declare_strict_types' => true,
    ])
;
```

**Comment by nunomaduro** [comment]
I am not find of tools that touch on my code automatically. Specially because that directive changes the behaviour of the code itself. Ideally would be cool to find a phpcs sniff for this, and add it here: https://github.com/nunomaduro/phpinsights/blob/e4530f13eb081e2464748490720624a94fbafb74/src/Domain/Metrics/LinesOfCode/SourceCode.php#L50.

**Comment by xuanquynh** [comment]
I don't really understand all stuff here. I am a little bit busy, too but I will spend time reading phpinsights source code soon and then try to think about a solution. I have created my own sniffs before. It may be helpful.

**Comment by nunomaduro** [comment]
It's done already.
