### ISSUE TITLE
array_keys() expects parameter 1 to be array, null given in src/Application/Adapters/Laravel/Preset.php

### ISSUE THREAD

**Issue by mjpramos** [nunomaduro/phpinsights#70]
I'm trying to install phpinsights on a non framework project and although my PHP version is 7.2.10 (MAMP on MacOS), I get the error stating that my PHP version is 7.1.23.

**Comment by nunomaduro** [comment]
That's because you are using a different php binary in your CLI. Let's keep this open, maybe someone would like to help you.

**Comment by ManojKiranA** [comment]
Hey dude that's​ not issue.Actually I was running my project in php 7.1.23 but still I had installed package and it's was working fine . Just try  ```composer require nunomaduro/phpinsights --dev --ignore-platform-reqs```

**Comment by mjpramos** [comment]
I updated my PHP CLI following the answer here [url]https://stackoverflow.com/questions/3973271/terminal-displays-wrong-php-version-snow-leopard(url).
Installation ran smoothly.

But now, when I try to use it, it gives me:
```
Fatal error: Uncaught TypeError: array_keys() expects parameter 1 to be array, null given in /Applications/MAMP/htdocs/cr/vendor/nunomaduro/phpinsights/src/Application/Adapters/Laravel/Preset.php:70
Stack trace:
#0 /Applications/MAMP/htdocs/cr/vendor/nunomaduro/phpinsights/src/Application/Adapters/Laravel/Preset.php(70): array_keys(NULL)
#1 /Applications/MAMP/htdocs/cr/vendor/nunomaduro/phpinsights/src/Application/ConfigResolver.php(67): NunoMaduro\PhpInsights\Application\Adapters\Laravel\Preset::shouldBeApplied(Array)
#2 /Applications/MAMP/htdocs/cr/vendor/nunomaduro/phpinsights/src/Application/ConfigResolver.php(36): NunoMaduro\PhpInsights\Application\ConfigResolver::guess('/Applications/M...')
#3 /Applications/MAMP/htdocs/cr/vendor/nunomaduro/phpinsights/src/Application/Console/Commands/AnalyseCommand.php(88): NunoMaduro\PhpInsights\Application\ConfigResolver::resolve(Array, '/Applications/M...')
#4 /Applications/MAMP/htdocs/cr/vendor/nunomaduro/phpinsights/src/Application/Console/Commands/AnalyseCommand.php(68): NunoM in /Applications/MAMP/htdocs/cr/vendor/nunomaduro/phpinsights/src/Application/Adapters/Laravel/Preset.php on line 70
```

Thanks/Obg

**Comment by ManojKiranA** [comment]
> I updated my PHP CLI following the answer here [link](https://stackoverflow.com/questions/3973271/terminal-displays-wrong-php-version-snow-leopard)
> Installation ran smoothly.
> 
> But now, when I try to use it, it gives me:
> 
> ```
> Fatal error: Uncaught TypeError: array_keys() expects parameter 1 to be array, null given in /Applications/MAMP/htdocs/cr/vendor/nunomaduro/phpinsights/src/Application/Adapters/Laravel/Preset.php:70
> Stack trace:
> #0 /Applications/MAMP/htdocs/cr/vendor/nunomaduro/phpinsights/src/Application/Adapters/Laravel/Preset.php(70): array_keys(NULL)
> #1 /Applications/MAMP/htdocs/cr/vendor/nunomaduro/phpinsights/src/Application/ConfigResolver.php(67): NunoMaduro\PhpInsights\Application\Adapters\Laravel\Preset::shouldBeApplied(Array)
> #2 /Applications/MAMP/htdocs/cr/vendor/nunomaduro/phpinsights/src/Application/ConfigResolver.php(36): NunoMaduro\PhpInsights\Application\ConfigResolver::guess('/Applications/M...')
> #3 /Applications/MAMP/htdocs/cr/vendor/nunomaduro/phpinsights/src/Application/Console/Commands/AnalyseCommand.php(88): NunoMaduro\PhpInsights\Application\ConfigResolver::resolve(Array, '/Applications/M...')
> #4 /Applications/MAMP/htdocs/cr/vendor/nunomaduro/phpinsights/src/Application/Console/Commands/AnalyseCommand.php(68): NunoM in /Applications/MAMP/htdocs/cr/vendor/nunomaduro/phpinsights/src/Application/Adapters/Laravel/Preset.php on line 70
> ```
> 
> Thanks/Obg

Are you trying in laravel app or some other can​ you specify that

**Comment by nunomaduro** [comment]
Can I see your composer.json? I think I know the issue.

**Comment by mjpramos** [comment]
As I said in my first post, it's non framework. Just some simple PHP classes.
My composer.json:

`{
    "require-dev": {
        "nunomaduro/phpinsights": "^1.0"
    }
}
`

**Comment by nunomaduro** [comment]
Alright, we need to prepare the class https://github.com/nunomaduro/phpinsights/blob/master/src/Application/ConfigResolver.php and all presets https://github.com/nunomaduro/phpinsights/tree/master/src/Application/Adapters to that type of composer.json.

**Comment by Jibbarth** [comment]
@mjpramos Can you run a `composer update` and tell us if it's fixed for you ?

**Comment by mjpramos** [comment]
Thanks! Works perfectly now :)

**Comment by nunomaduro** [comment]
Thanks @Jibbarth for this!
