### ISSUE TITLE
Missing feature to ignore certain issues

### ISSUE THREAD

**Issue by sandulat** [nunomaduro/phpinsights#78]
Hi guys. Thank you so much for developing such an **awesome package**!

When running PHP Insights in Laravel 5.8 I get the following warning:
```
• [Code] Unused function parameter:
  app/Http/Resources/UserResource.php:29: The method parameter $request is never used
```

My resource class:
```
class UserResource extends JsonResource
{
    public function toArray($request)
    {
        return [
            'id' => $this->id,
            'name' => $this->name,
            'email' => $this->email,
        ];
    }
}
```

Even though the `$request` variable isn't used, the implementation of Laravel's API resources forces me to indicate this variable. 

Would be cool to have feature that allow to ignore certain issues, and maybe include some of those `ignores` on the Laravel preset.

**Comment by nunomaduro** [comment]
Absolutely, I am open for a pull request on this.

**Comment by dsentker** [comment]
Have you tried

```php
class UserResource extends JsonResource
{
    public function toArray($request) // phpcs:ignore
    {
        
    }
}
``` ?

**Comment by olivernybroe** [comment]
You can now exclude a sniff on a file, this might help you with this. https://phpinsights.com/insights/#remove-insights
