### ISSUE TITLE
Add optionally a description to an `Insight`

### ISSUE THREAD

**Issue by nunomaduro** [nunomaduro/phpinsights#8]
To solve this issue, you should create an interface called `HasDescription`, that can be added to an `Insight`. The goal: If an `Insight` contains the interface `HasDescription`, then we description somewhere why the `Insight` exists, why is bad, suggestion on how can be fixed; etc.

**Comment by akosglue** [comment]
It would be nice by this enhancement if you could include a link to explanations.
For example: if you get this advice: Disallow yoda comparison, there should be a link that will show you the explanation: https://github.com/slevomat/coding-standard#slevomatcodingstandardcontrolstructuresdisallowyodacomparisonrequireyodacomparison-

**Comment by JacobDB** [comment]
I'd very much like this as well &ndash; phpinsights in my first foray in to automated testing of PHP, so I've been routinely confused by the notices that pop up, and unable to track down any documentation for most of them.

**Comment by Jibbarth** [comment]
@akosglue & @JacobDB 

Since your comments, we have work on [documentation](https://phpinsights.com) to list all Insights used in phpinsights with their className and their meaning :wink:

**Comment by nunomaduro** [comment]
No plans to work on this at this time.
