### ISSUE TITLE
Cmder as Vscode terminal format issue

### ISSUE THREAD

**Issue by delta1186** [nunomaduro/phpinsights#81]
Not sure the difference and if it's even an issue with Insight.  Nice tool BTW.  As you can see from the image below when running Cmder alone the formatting displays.  However, I Cmder setup as my Vscode terminal and you can see that the output there appears to be encoded. 

![image](https://user-images.githubusercontent.com/421307/57896812-311c5780-7818-11e9-8620-133b5a9dfd48.png)

![image](https://user-images.githubusercontent.com/421307/57896845-5e690580-7818-11e9-8b2f-e80cb611e859.png)

Probably not an issue here, but figured I would post just in case.

**Comment by olivernybroe** [comment]
This sounds like a vscode issue :) 

However I see another issue with your Cmder example, the emoji for black square is missing. Are you using a custom font?

**Comment by delta1186** [comment]
Cmder was just Consolas, but I just changed it to the default for the vscode text editor: Consolas, 'Courier New', monospace.  

It did appear to fix the Cmder window, but did not do anything for vscode.

![image](https://user-images.githubusercontent.com/421307/58810192-0f2a1f80-85e3-11e9-95ec-cdc7e6ca8949.png)

**Comment by olivernybroe** [comment]
![image](https://user-images.githubusercontent.com/5870441/58810555-731e0980-861e-11e9-8bc4-4572bb724275.png)
Annoying that it doesn't used filled out squares for you.

Are you running the latest vscode version?

Check out this article https://winsmarts.com/using-cmder-as-integrated-shell-in-vscode-c3340714fe3c, it might fix it for you by also setting the font family inside of vscode.

**Comment by delta1186** [comment]
Well, now I am determined it is related to Cmder.  I removed Cmder as vscode terminal and used the default powershell and got this.

![image](https://user-images.githubusercontent.com/421307/58812639-e193a500-85e7-11e9-9d09-d5df9c81d5ca.png)

**Comment by olivernybroe** [comment]
Haha, yep that looks much better.

Hmm yeah, sounds like it. I think we will close this issue then as it doesn't seem like this package is at fault.

Hope you find a solution!
