### ISSUE TITLE
Overwrite suggested method/properties count

### ISSUE THREAD

**Issue by tomasnorre** [nunomaduro/phpinsights#82]
It would be great if I could overwrite suggested method and properties count, for e.g. domain model and repository. 

I see that it should be kept simple, but some models requires way more than 10 properties.

https://twitter.com/enunomaduro/status/1128686091693895682

**Comment by nunomaduro** [comment]
Humm, per file?

**Comment by tomasnorre** [comment]
I don't know how this should be done. 

I've thought about, 
* Annotation - Don't like the idea that much due to dependency to your tool then
* Configuration - Per file and/or directory perhaps?

**Comment by nunomaduro** [comment]
This is already possible, please re-open the issue if something doesn't work.

**Comment by tomasnorre** [comment]
Can you link me to the documentation on how this is possible ?

**Comment by nunomaduro** [comment]
Here is an example: https://phpinsights.com/insights/architecture.html#property-per-class-limit.
