### ISSUE TITLE
Possible to write to file 

### ISSUE THREAD

**Issue by Tjoosten** [nunomaduro/phpinsights#83]
Hi first of all thanks for the great package. 

But i'm worndering is there is a possibility to write the output to a file. Because for me personally is it messy to view the output on the terminal.

**Comment by akosglue** [comment]
I think it will be handled within https://github.com/nunomaduro/phpinsights/issues/61

**Comment by nunomaduro** [comment]
Duplicate of https://github.com/nunomaduro/phpinsights/issues/61.
