### ISSUE TITLE
Command "insights" is not defined

### ISSUE THREAD

**Issue by atiladelcanton** [nunomaduro/phpinsights#86]
Good morning friends!

I'm having this problem while running the command

`php artisan insights`

**Comment by andrewnclark** [comment]
You sire you ran `php artisan vendor:publish --provider="NunoMaduro\PhpInsights\Application\Adapters\Laravel\InsightsServiceProvider"`

**Comment by nunomaduro** [comment]
@atiladelcanton What is `this problem`?

**Comment by nunomaduro** [comment]
Fell free to re-open the issue if you need help.

**Comment by muntasir1677** [comment]
Please help - 

php artisan vendor:publish --provider="NunoMaduro\PhpInsights\Application\Adapters\Laravel\InsightsServiceProvider"

Publishing complete.

php artisan insights

Command "insights" is not defined._

**Comment by pushpalmazumder** [comment]
I am getting this - 

_php artisan vendor:publish --provider="NunoMaduro\PhpInsights\Application\Adapters\Laravel\InsightsServiceProvider"_

**Publishing complete.**

_php artisan insights_

**Command "insights" is not defined.**  

Please help.
