### ISSUE TITLE
Empty PHP statement: superfluos semicolon duplicated as Disallow multiple statements

### ISSUE THREAD

**Issue by maxalmonte14** [nunomaduro/phpinsights#93]
Hi Nuno and the rest of the community 👋, I'm trying Insights in a huge Laravel legacy codebase and I noticed that `Empty PHP statement: superfluos semicolon` is duplicated as `Disallow multiple statements`, I don't know if this is the desired behavior provided that they're are referring to the same issue, and fixing the former also fixes the latter, also a solo semicolon is not an statement at all.

Just BTW there's a typo in superfluos, it should be **superfluous**, but that's an easy fix, and not the point here 😅

Here I add some of my output.

Congratulations for the release of the package, I love it! Keep on the good work 👏 

```
• [Code] Empty p h p statement:
  app/Models/AlteredModelName.php:82: Empty PHP statement detected: superfluous semi-colon.
  app/Models/AlteredModelName.php:141: Empty PHP statement detected: superfluous semi-colon.
  app/Models/AlteredAnotherModelName.php:38: Empty PHP statement detected: superfluous semi-colon.
```

---

```
• [Code] Disallow multiple statements:
  app/Models/AlteredModelName.php:82: Each PHP statement must be on a line by itself
  app/Models/AlteredModelName.php:141: Each PHP statement must be on a line by itself
  app/Models/AlteredAnotherModelName.php:38: Each PHP statement must be on a line by itself

```

**Comment by maxalmonte14** [comment]
In a second quick review there's a third rule throwing the same results for this edge-case `Useless semicolon`, here is the output:

```
• [Code] Useless semicolon:
  app/Models/AlteredModelName.php:82: Useless semicolon.
  app/Models/AlteredModelName.php:141: Useless semicolon.
  app/Models/AlteredAnotherModelName.php:38: Useless semicolon
```

**Comment by nunomaduro** [comment]
Can you copy paste the code if this file  `app/Models/AlteredModelName.php` ?

**Comment by maxalmonte14** [comment]
I already modified the files, but essentially was something like this:

```php
public function foo()
{
    $foo = 'foo';; // <- here the warning is generated because there is an extra semicolon
    // other operations
}

```

**Comment by nunomaduro** [comment]
Ahh, understood now. I think it's fine, as `Disallow multiple statements` also applies to other kind of things, such us:

```php
$a = 1; $b =2;
```

**Comment by maxalmonte14** [comment]
Perfect 👌
