### ISSUE TITLE
Disallow short ternary operator and Require short ternary operator both active by default

### ISSUE THREAD

**Issue by maxalmonte14** [nunomaduro/phpinsights#94]
Hi Nuno and the rest of the community 👋

It looks like both rules are active by default (at least in Laravel), they cause conflicts with each other in the way the code should look.

**Comment by nunomaduro** [comment]
Fixed via: https://github.com/nunomaduro/phpinsights/commit/7e10c186ed0923423e4650151644f12daa9875ed

**Comment by maxalmonte14** [comment]
Awesome 👏
