### ISSUE TITLE
Expected 1 space(s) after NOT operator; 0 found

### ISSUE THREAD

**Issue by cloudstudio** [nunomaduro/phpinsights#96]
Hello Guys! I think maybe is a Bug.

I this this error 

``Expected 1 space(s) after NOT operator; 0 found``

With this code : 

![Captura de pantalla 2019-05-18 a las 19 20 42](https://user-images.githubusercontent.com/3589377/57972986-0f4edc00-79a2-11e9-948f-9606d75e2543.png)

**Comment by nunomaduro** [comment]
That says that you should you should add a space after a NOT condition:

```php
if (! $request...
```

**Comment by cloudstudio** [comment]
This happend in some Laravel core files, so I send some pull request :P

**Comment by nunomaduro** [comment]
What version of Laravel?

**Comment by cloudstudio** [comment]
I use in this project : 

```
        "laravel/framework": "5.7.*",

```
