### ISSUE TITLE
Issue - Command "insights" is not defined.

### ISSUE THREAD

**Issue by pushpalmazumder** [nunomaduro/phpinsights#99]
I am getting this -

_php artisan vendor:publish --provider="NunoMaduro\PhpInsights\Application\Adapters\Laravel\InsightsServiceProvider"_

**Publishing complete.**

_php artisan insights_

**Command "insights" is not defined.**

Please help.

**Comment by nunomaduro** [comment]
I have no idea on how to solve your problem.

**Comment by pxgamer** [comment]
What version of Laravel are you using?

**Comment by nunomaduro** [comment]
@pxgamer Good point. Maybe he needs to register the service provider manually.

**Comment by adampatterson** [comment]
Same problem for me, I am running Laravel 5.7

```
$ php artisan vendor:publish --provider="NunoMaduro\PhpInsights\Application\Adapters\Laravel\InsightsServiceProvider"

Publishing complete.
```

```
artisan insights
Command "insights" is not defined.
```

**Comment by pushpalmazumder** [comment]
I am using Laravel 5.8.

**Comment by nunomaduro** [comment]
You have auto discovery enabled?

**Comment by adampatterson** [comment]
> You have auto discovery enabled?

Yes, I deleted my `composer.lock` file and reinstalled. Seems to work now.

**Comment by nunomaduro** [comment]
Great!
